### ISSUE TITLE
[@types/validator] New version of types is missing isMACAddress

### ISSUE THREAD

**Issue by kaiyoma** [DefinitelyTyped/DefinitelyTyped#40928]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tgfjt @chrootsu @IOAyman @louy @kacepe @deptno @builtinnya @qqilihq @keatz55 @MunifTanjim

I'm currently using version 10.11.3 of this package and everything is working fine, but if I upgrade to the latest version (12.0.1), I start getting this error:

```
error TS2614: Module '".../node_modules/@types/validator"' has no exported member 'isMACAddress'. Did you mean to use 'import isMACAddress from ".../node_modules/@types/validator"' instead?
```

Is the type for that function no longer being exported?

**Comment by winterNebs** [comment]
Having a similar issue with `isEmail`, i had to import it like this
```typescript
import * as val from "validator";
...
val.default.isEmail(); // this works
```

**Comment by Rogier076** [comment]
We had a similar issue with `isIP`, `isFQDN` and `isNumeric` , so it probably applies to all exports.
This happened probably after upgrading typescript to 3.7.5 or NodeJS to v12, but not sure.
importing (default) from `validator/lib/isFQDN` etc. solved the problem.

**Comment by adgoncal** [comment]
I just had the same issue with `isEmail`.
I am using `validator@^13.0.0` and `@types/validator@13.0.0`.

@Rogier076 solution worked for me.
```
import isEmail from 'validator/lib/isEmail';
```

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
