### PR TITLE
Re-added exports and "chai" module to chai types

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes issues with downstream typings and projects that relied on the chai module (partially reverts DefinitelyTyped/DefinitelyTyped#21879).

A bunch of downstream dependencies are broken. IMO we should wait until https://github.com/Microsoft/TypeScript/issues/14844 is to resolved to reconsider how best to do this.

@mceachen @segayuu can you confirm this fixes the issues for you?

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks!

**Comment by segayuu** [comment]
thanks!

**Comment by robertmain** [comment]
That's relieving. My build started failing yesterday(including historically working builds). Turns out when the build server ran `npm install` it was updating the packages at the same time and installing the version of `@types/chai` v4.0.7. I thought I was going crazy!

**Comment by natesilva** [comment]
Please re-open this. The problem is back in 4.0.9, released a few minutes ago. 🙁

**Comment by ottokruse** [comment]
Yup alas it is back in 4.0.9

**Comment by mceachen** [comment]
The regression is from PR #21951

**Comment by minestarks** [comment]
Reverted #21951

**Comment by patsissons** [comment]
Thank you @minestarks, this regression had me very confused for a short while.

**Comment by demisx** [comment]
I'm running chai 4.0.10 and all latest modules. I am still seeing this error. Can you please tell me what I should do to fix it:

```
node_modules/@types/chai-as-promised/index.d.ts(27,49): error TS2304: Cannot find name 'NumericComparison'.
node_modules/@types/chai-as-promised/index.d.ts(27,68): error TS2304: Cannot find name 'TypeComparison'.
```

**Comment by demisx** [comment]
Please disregard my whining above. I've removed `node_modules` and re-run `npm i` again. The errors went away.
