### PR TITLE
[node] Adds type definition for process.env.

### LINKED ISSUE #11615: Type of process.env should be { [key: string]: string }
This will allow to typescript to trigger compile error :

``` js
    const x: number = process.env.x;
```

See Microsoft/TypeScript/issues/11239

### PR DESCRIPTION
**Pull request by tomc974**
Fixes #11615

This should work in TypeScript 2.2+ (see TypeScript issue [#12596](https://github.com/Microsoft/TypeScript/issues/12596))

### CODE REVIEW

**Comment by tomc974** [comment]
Unsure what to do about the CI error...

**Comment by sandersn** [comment]
Changing node kicks off tests of all dependents, which takes over an hour right now. I've been scanning the log manually looking for errors. For this change, I found these two kinds of errors:

```ts
Testing dockerode
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js 
	/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/dockerode/dockerode-tests.ts
ERROR: 12:21  expect  TypeScript compile error: Property 'DOCKER_PORT' does not exist on type '{ [variable: string]: string; }'.
ERROR: 21:21  expect  TypeScript compile error: Property 'DOCKER_PORT' does not exist on type '{ [variable: string]: string; }'.

publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
	jake-tests.ts(56,27): error TS2339: Property 'qux' does not exist on type '{ [variable: string]: string; }'.
jake-tests.ts(56,44): error TS2339: Property 'frang' does not exist on type '{ [variable: string]: string; }'.
Package compiles in TypeScript 2.3 but not in 2.0.
You can add a line '// TypeScript Version: 2.3' to the end of the header to specify a newer compiler version.
```

The first failure is a good catch of an incorrect test that assumes `process.env.DOCKER_PORT` is a number when it's actually a string.

The second failure occurs because Typescript 2.2 started allowing the syntax `process.env.qux` as an equivalent to `process.env['qux']` when a type has a string indexer. Before that, it was not allowed. But it looks like lots of tests rely on this syntax, which is of course allowed when the type is just `env: any`.

I don't think this change adds enough value to require TS 2.2+ for packages that use node (which is many of them). It catches a couple of type errors, but breaks a bunch of packages in exchange. Do you agree?

**Comment by mdebruijne** [comment]
@tomc974; If you want you can close this pull request, because this is being addressed in #17458

**Comment by tomc974** [comment]
@mdebruijne Sure, since you are already on this issue, I'm closing the PR. :-)
