### PR TITLE
Karma v0.13.9

### PR DESCRIPTION
**Pull request by tkqubo**

### CODE REVIEW

**Comment by horiuchi** [comment]
@tkrotoff Could you review this pull request?

**Comment by vvakame** [comment]
if we can't get reviewer's answer, We'll merge this PR.

**Comment by tkrotoff** [comment]
@vvakame good for me. Would be nice to have both karma-0.12.d.ts and karma-0.13.d.ts

**Comment by tkqubo** [comment]
@tkrotoff Thanks for reviewing my PR!

> nice to have both karma-0.12.d.ts and karma-0.13.d.ts

In a case like above, is it enough to simply preserve the original file with filename `karma-0.12.d.ts`?
Then I will submit a new commit for that.

**Comment by tkrotoff** [comment]
> is it enough to simply preserve the original file with filename karma-0.12.d.ts?

Yes, plus karma-tests-0.12.d.ts. There are other definitions (angular for example) that use the same pattern, check how they did it.

As for version 0.13, name it karma.d.ts and karma-tests.ts (no need to have 0.13 in the name unlike my previous suggestion).

**Comment by tkqubo** [comment]
@tkrotoff Thanks for your kindness.  I added a few commits to include karma-0.12.

By the way, when I tried to complie the karma-tests-0.12.ts in the command line like this,
```bash
tsc --target es5 --module commonjs --noImplicitAny karma/karma-tests-0.12.ts
```
the tsc says:
```bash
karma/karma-0.12.d.ts(23,5): error TS2300: Duplicate identifier 'export='.
karma/karma.d.ts(367,5): error TS2300: Duplicate identifier 'export='.
```

How come the said identifier duplication comes up while `karma/karma.d.ts` is never referenced from `karma-0.12.d.ts`?  I don't know if I provided wrong command line options but somehow Travis CI build passed :disappointed:

**Comment by tkqubo** [comment]
Sorry, the extra issue I commented above was simply because I was using older tsc version (1.5).
After I updated tsc up to 1.6.0-beta, the compilation succeeded in local environment.  Sorry for bothering you

**Comment by vvakame** [comment]
@tkrotoff thanks!
@tkqubo thanks mate!
