### ISSUE TITLE
_.zipWith in `@types/lodash@4.14.86` not work

### ISSUE THREAD

**Issue by laispace** [DefinitelyTyped/DefinitelyTyped#21884]
I tried using the `@types/lodash` package and had problems.

It's not work in `@types/lodash@4.14.86`:
```
const fakeValueArray = [
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
  ];
const totalValueArray = _.zipWith(...fakeValueArray, (...args: number[]): number => _.sum(args));
// totalValueArray =>  [6, 15, 24]
```
> TS2345:Argument of type '(...args: number[]) => number' is not assignable to parameter of type 'ArrayLike<number>'.
  Index signature is missing in type '(...args: number[]) => number'.

But it's work in older `@types/lodash@4.14.77`.

I saw the definition of `_.zipWith` but still confused.

**Comment by trickeyone** [comment]
I'm getting a similar error for `@types/lodash@4.14.88` when trying to use `_.find`.
```
const arr = [
    {
        value: 1,
        disabled: false
    },
    {
        value: 2,
        disabled: false
    }
];
let found = _.find(arr, {value: 2});
console.log(found.disabled);
```
When attempting to access a property of the returned value, I get this error. This did not occur with v4.14.77.
> Error:(240, 38) TS2339:Property 'disabled' does not exist on type 'number | (() => string) | { (...items: ReadonlyArray<StartType>[]): StartType[]; (...items: (Star...'.
  Property 'disabled' does not exist on type 'number'.

**Comment by andnp** [comment]
@trickeyone I cannot reproduce this error with the code you provided. I see the error `Object is possibly 'undefined'`, but cannot get to the error that you are seeing.

I am using `@types/lodash@4.14.88` and tsc version `2.6.1` and `2.6.2`.

**Comment by trickeyone** [comment]
My apologies. The example should contain instanced objects, rather than plain objects.

```js
class MyObject
{
  constructor(public value: number, public disabled: boolean) {}
}

const arr = [
    new MyObject(1, false),
    new MyObject(2, false)
];
let found = _.find(arr, {value: 2});
console.log(found.disabled);
```

I see the error, both, in my IDE (PHPStorm) and when I attempt to compile.

**Comment by andnp** [comment]
I think these are two unrelated errors, would you mind opening a new issue to track yours as well? This way we can make sure that neither ends up accidentally getting ignored.

**Comment by trickeyone** [comment]
No problem. Created #22114.

**Comment by andnp** [comment]
@laispace Basically `_.zipWith` is going to be impossible to type correctly. The function relies on a feature of javascript that typescript (correctly imo) does not allow. You pass in an array of arguments where the first `n-1` args are arrays, and the last `n`th arg is a function. Typescript cannot replicate that yet with its tuple type.

One option I can see is keeping the current overloads which allow you to do:
```ts
_.zipWith(arr1, arr2, arr3, (...x) => _.sum(x))
```
but that isn't the same as what you are trying, and if your matrix can be larger than 3 rows, this won't work for you.

Another option is weakening the types of `_.zipWith`:
```ts
_.zipWith(...array: Array<T | (...x: T[]) => T>): T[]
```
sort of thing. This will lose a bit of type safety by allowing you to incorrectly put the iterator function anywhere, but I don't see any way around that right now.

**Comment by andnp** [comment]
In fact, it seems the typings currently have that last option available, albeit incorrectly so. I'll fix that bug in a PR, since that seems to be the way the authors were previously trying to go.
