### PR TITLE
fixes #11929

### LINKED ISSUE #11929: Breaking change to React StatelessComponent definition
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `react/index.d.ts`. (on the types-2.0 branch)
  - The authors of that type definition are cc/ @aozgaa 

Using `typescript@2.0.3` with `strictNullChecks=true`.

After updating from `@types/react@0.14.40` to `0.14.41` (PR #11912 from @donaldpipowitch), I've started getting errors on code which worked before:

For example,

``` bash
$ tsc -p .
src/app/test.tsx(9,7): error TS2605: JSX element type 'ReactElement<any> | null' is not a constructor function for JSX elements.
  Type 'null' is not assignable to type 'ElementClass'.
```

``` tsx
import * as React from 'react';
import { StatelessComponent } from 'react';

const ElementA: StatelessComponent<any> = (props: {}) => (<div />);

function ElementB(props: {}): JSX.Element {
  return (
    <div>
      <ElementA />
    </div>
  );
}
```

It works fine if I use `createElement(ElementA, {})` instead of the TSX form.

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Revert breaking change made in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11912.

I'll file an issue about that in the TypeScript repository later as I think this a bug in the way how the TypeScript compiler uses TSX. It works fine if you don't use TSX and it is "correct" to return `null` in the way the JS API behaves.

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Reported issue: https://github.com/Microsoft/TypeScript/issues/11566

**Comment by donaldpipowitch** [comment]
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11935
