### ISSUE TITLE
Error when rebuilding with lodash

### ISSUE THREAD

**Issue by akhilmalla** [DefinitelyTyped/DefinitelyTyped#14985]
- [ ] I tried using the `@types/lodash` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

The following are the errors I get when doing a rebuild

/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(244,13): error TS2300: Duplicate identifier '_'.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(248,19): error TS2300: Duplicate identifier '_'.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,21): error TS1005: ']' expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,22): error TS1005: ';' expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,23): error TS1128: Declaration or statement expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,33): error TS1005: ']' expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,34): error TS1005: ')' expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,35): error TS1128: Declaration or statement expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(11451,37): error TS1128: Declaration or statement expected.
/Users/amalla/workspace/sparqapp/node_modules/@types/lodash/index.d.ts(19448,1): error TS1128: Declaration or statement expected.

**Comment by tovganesh** [comment]
I get similar errors when doing the rebuild.

/Users/.../node_modules/@types/lodash/index.d.ts(11451,21): error TS1005: ']' expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,22): error TS1005: ';' expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,23): error TS1128: Declaration or statement expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,33): error TS1005: ']' expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,34): error TS1005: ')' expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,35): error TS1128: Declaration or statement expected.
/Users/.../node_modules/@types/lodash/index.d.ts(11451,37): error TS1128: Declaration or statement expected.
/Users/.../node_modules/@types/lodash/index.d.ts(19448,1): error TS1128: Declaration or statement expected.

**Comment by tovganesh** [comment]
EDIT: After updating Typescript to 2.1 the error is no longer there.

**Comment by aj-r** [comment]
Ping authors: @bczengel, @chrootsu, @stepancar, @ericanderson

Should we close this issue then?

**Comment by ericanderson** [comment]
Yes please

**Comment by aj-r** [comment]
@andy-ms this should be closed.
