### ISSUE TITLE
16.4.4 version introduced an issue with setting state in a constructor

### ISSUE THREAD

**Issue by dshuvaev** [DefinitelyTyped/DefinitelyTyped#26898]
After updating typings to @types/ 16.4.4. we got set of these errors:
error TS2540: Cannot assign to 'state' because it is a constant or a read-only property.
The code that was broken:

```TypeScript
constructor(props) {
        super(props);
        this.state = {
            stateProperty: initialValue
        }
    }

```
The fix is to use

```TypeScript
constructor(props) {
        super(props);
        this.setState({
            stateProperty: initialValue
        });
    }
```
Previous version we used was @types/ 16.0.40
ReadOnly property should be allowed to set in a constructor. 

Authors: @johnnyreilly, @bbenezech, @pzavolinsky, @digiguru, @ericanderson, @morcerf, @tkrotoff, @DovydasNavickas, @onigoetz, @theruther4d, @guilhermehubner, @ferdaber, @jrakotoharisoa

**Comment by ferdaber** [comment]
Looks to be introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26813

**Comment by afc163** [comment]
+1

**Comment by alamothe** [comment]
Actually that is not a fix... https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26813#issuecomment-400795486 is the correct fix

**Comment by Ky6uk** [comment]
Yeah. `v16.4.2` of the type definitions is still working fine when `v16.4.4` just break a lot of existing codebase in my project.

**Comment by janvandenberg** [comment]
+1

**Comment by dshuvaev** [comment]
The fix I suggested is not entirely correct as it is stated [here](https://stackoverflow.com/questions/51074355/cannot-assign-to-state-because-it-is-a-constant-or-a-read-only-property) and the reason is [React documentation](https://reactjs.org/docs/react-component.html#constructor)

**Comment by johnnyreilly** [comment]
PRs welcome folks!

**Comment by MagnusBrzenk** [comment]
+1

**Comment by shincysl** [comment]
+1.
state: **null |** Readonly<S>;
The null here also introduce errors when using react-redux connect().

**Comment by pstrh** [comment]
#26945 contains a PR to fix this major issue

**Comment by dshuvaev** [comment]
Fixed in 16.4.6

**Comment by dshuvaev** [comment]
#26946 fixed it. Thank you very much @Hotell, @ferdaber, and @johnnyreilly !
