### PR TITLE
Fix types for `emoji-mart` emojiIndex

### PR DESCRIPTION
**Pull request by elvis-wolcott**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
* https://github.com/missive/emoji-mart#headless-search
Documentation showing that `emojiIndex.search()` returns an array of emoji
* https://github.com/missive/emoji-mart/blob/master/src/utils/emoji-index/nimble-emoji-index.js#L39-L50
Source showing that the `emojiIndex.emojis` returns an object of `EmojiData` when multiple skin tones exist.
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by Nicell — COMMENTED** [review]
It looks like search has returned an array since the first version of emoji-mart. I'm wondering if we should make a new release on 2.8 with this change, and then we could have another release that adds the functionality for multiple skin tones for version 2.11. I'm not really sure how this is normally handled. I don't know if we want to force people to upgrade to 2.11 to have headless search types fixed.

Thoughts @Jessidhia?

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by johnryan** [comment]
After updating to 2.11.0 with typescript v3.6.2 I'm seeing:

```
../node_modules/@types/emoji-mart/dist-es/utils/emoji-index/nimble-emoji-index.d.ts:32:52 - error TS2322: Type 'EmojiSkin' is not assignable to type 'string'.
  Type '1' is not assignable to type 'string'.

32 export type EmojiEntry = EmojiData | { [variant in EmojiSkin]: EmojiData }; // emoji with skin tones will return
```

Was this issue introduced by this PR?

**Comment by Nicell** [comment]
It would've been this PR, but I can't reproduce this with v2.11.0 and TS v3.6.2. @johnryan

**Comment by johnryan** [comment]
@Nicell thanks for the response. Turns out I had `keyofStringsOnly: true` in my tsconfig which caused the error in case anyone else ends up here.
