### PR TITLE
[redux-form] Add asyncChangeFields to ConfigProps

### PR DESCRIPTION
**Pull request by shepmaster**
Mirroring change in erikras/redux-form#3531

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: erikras/redux-form#3531
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by shepmaster** [comment]
`npm run lint redux-form` did fail for `TypeScript@next`, but it seems unrelated

```
> definitely-typed@0.0.1 lint /Users/shep/Projects/DefinitelyTyped
> dtslint types "redux-form"

Error: /Users/shep/Projects/DefinitelyTyped/types/redux-form/lib/Field.d.ts
ERROR: 12:26   expect  TypeScript@next compile error:
Cannot find module 'redux'.

/Users/shep/Projects/DefinitelyTyped/types/redux-form/lib/Form.d.ts
ERROR: 2:26    expect  TypeScript@next compile error:
Cannot find module 'redux'.

/Users/shep/Projects/DefinitelyTyped/types/redux-form/lib/actions.d.ts
ERROR: 1:24    expect  TypeScript@next compile error:
Cannot find module 'redux'.

/Users/shep/Projects/DefinitelyTyped/types/redux-form/lib/reducer.d.ts
ERROR: 1:33    expect  TypeScript@next compile error:
Cannot find module 'redux'.

/Users/shep/Projects/DefinitelyTyped/types/redux-form/lib/reduxForm.d.ts
ERROR: 10:26   expect  TypeScript@next compile error:
Cannot find module 'redux'.

/Users/shep/Projects/DefinitelyTyped/types/redux-form/redux-form-tests.tsx
ERROR: 3:34    expect  TypeScript@next compile error:
Cannot find module 'redux'.
ERROR: 14:5    expect  TypeScript@next compile error:
Duplicate identifier 'BaseFieldProps'.
ERROR: 18:5    expect  TypeScript@next compile error:
Duplicate identifier 'BaseFieldProps'.
ERROR: 312:1   expect  TypeScript@next compile error:
Cannot invoke an expression whose type lacks a call signature. Type 'FormReducer' has no compatible call signatures.
ERROR: 318:20  expect  TypeScript@next compile error:
Property 'type' does not exist on type 'FormAction'.
ERROR: 341:1   expect  TypeScript@next compile error:
Cannot invoke an expression whose type lacks a call signature. Type 'FormReducer' has no compatible call signatures.
```

**Comment by shepmaster** [comment]
> it seems unrelated

Yes, the same tests fail with master.

**Comment by shepmaster** [comment]
Pinging listed authors because I don't see the bot chiming in...

@carsonf
@aikoven
@LKay
@bancek
@alsiola

**Comment by shepmaster** [comment]
Failures seem to be addressed by #20982
