### PR TITLE
Make dom-mediacapture-record work on TS 4.4's DOM

### PR DESCRIPTION
**Pull request by sandersn**
TS 4.4 changes mediacapture-record types. This PR makes it match those
upcoming types.

Needed after microsoft/TypeScript#44684 is merged.

### CODE REVIEW

**Comment by boris-petrov** [comment]
This PR [removes](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54096/files#diff-b6c2fb96ad8f44f996374dc5fa419a45396eaacd5e77c982e40a41639aa8e3b1L37) the type `RecordingState` and hence the error when I use the new package version:

```
node_modules/@types/dom-mediacapture-record/index.d.ts:58:21 - error TS2304: Cannot find name 'RecordingState'.

58     readonly state: RecordingState;
                       ~~~~~~~~~~~~~~
```

**Comment by donpark** [comment]
Ran into same error over `RecordingState`  although I have not yet located where it was defined before.

**Comment by sandersn** [comment]
@boris-petrov you should only update to the latest if you have TS 4.4, which is still a day from shipping its beta.
You need to specify exact versions of any DOM polyfill package since the types have to match exactly.

However, it's a better fix to inline the RecordingState type so that it works with older versions as well. I did that here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54152
