### ISSUE TITLE
Symbol commented out in node/index.d.ts

### ISSUE THREAD

**Issue by anthonyvercolano** [DefinitelyTyped/DefinitelyTyped#29380]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....@simonschick

lerna ERR! node_modules/@types/node/index.d.ts(609,10): error TS2304: Cannot find name 'Symbol'.

There is a change to the node types definition.

The declaration for Symbol at line 177 seems to have been commented out.

Latest version that seemed to work for this file was 8.9.4

This is happening while trying to build with node v6.9.4, npm  v3.10.10 and various typescript version.

**Comment by SimonSchick** [comment]
There was a conflict when I was working on the typings, I can look into that in a bit.

**Comment by SimonSchick** [comment]
@anthonyvercolano I think this can be closed.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
