### ISSUE TITLE
[@types/uuid] - v7.0.0 breaks `uuid/v4`

### ISSUE THREAD

**Issue by pburkindine** [DefinitelyTyped/DefinitelyTyped#42634]
- [X] I tried using the `@types/uuid` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @iamolivinius, @felipeochoa, @cjbarth, @rauno56, @LinusU, and @ctavan

Imports of `uuid/v4` broke today as no declaration file found after update to @types/uuid v7.0.0

```
Could not find a declaration file for module 'uuid/v4'. '/Users/pete.burkindine/git/ccxp/ccxp-client/node_modules/uuid/v4.js' implicitly has an 'any' type.
  Try `npm install @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid/v4';`
```

**Comment by pburkindine** [comment]
For anyone else experiencing this,
```
import { v4 as uuid } from 'uuid';
```

rather than
```
import * as uuid from 'uuid/v4';
```

The changelog for uuid indicates
```
Explicitly note that deep imports of the different uuid version functions are deprecated and no longer encouraged and that ECMAScript module named imports should be used instead. Emit a deprecation warning for people who deep-require the different algorithm variants.
```

... however I received no deprecation notice before or after updating `@types/uuid`

**Comment by ctavan** [comment]
@pburkindine good catch, seems like I was a bit too fast when updating the types.

We could easily bring back types for the deep imports as long as we make sure they result in a depreciation warning. I admit that we should not treat typescript users differently than JS users.

I can look into this later this week but would be equally happy to review a pull request.

**Comment by gokhantaskan** [comment]
Could not find a declaration file for module 'uuid/v4'. 'c:/.../node_modules/uuid/v4.js' implicitly has an 'any' type.

Try `npm install @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid/v4';

----
```js
import { v4 as uuidv4 } from "uuid/v4";

...


export function randomId(): string {
  return uuidv4();
}
```
----
`TypeError: Object(...) is not a function at randomId`

**Comment by LinusU** [comment]
@gokhantaskan 

```diff
-import { v4 as uuidv4 } from "uuid/v4";
+import { v4 as uuidv4 } from "uuid";
```

The deep requires have been deprecated as of UUID version 7.x

**Comment by gokhantaskan** [comment]
> @gokhantaskan
> 
> ```diff
> -import { v4 as uuidv4 } from "uuid/v4";
> +import { v4 as uuidv4 } from "uuid";
> ```
> 
> The deep requires have been deprecated as of UUID version 7.x

But it still gives the same error

**Comment by ctavan** [comment]
@gokhantaskan this is really weird! The unit test of the type declarations uses 

```js
import { v4 as uuidv4 } from "uuid";
```

and it just works fine. What error do you get when using the above code?

See: https://github.com/ctavan/DefinitelyTyped/blob/5a59a59b867088e492e59e9f52ec681a9ff5b7a2/types/uuid/uuid-tests.ts#L3

**Comment by zbianca** [comment]
This breaks other packages that build over uuid like: https://github.com/VitorLuizC/vue-uuid
It works with @types/uuid v7.0.4.

**Comment by ctavan** [comment]
@zbianca I think this can easily be fixed in `vue-uuid` by changing

```ts
import v1 from 'uuid/v1';
import v4 from 'uuid/v4';
import v5 from 'uuid/v5';
```

to

```ts
import { v1, v4, v5 } from 'uuid';
```

in https://github.com/VitorLuizC/vue-uuid/blob/master/index.d.ts and https://github.com/VitorLuizC/vue-uuid/blob/master/index.js

This is something that has to be done in the `vue-uuid` package though, so I think you may have to raise an issue or send a pull request over there.

**Comment by zbianca** [comment]
@ctavan Thanks for the quick reply!

I'll raise an issue over there 🙂

**Comment by dwjohnston** [comment]
Incase anyone has come here from google - make sure your `@types/uuid` matches the version of your `uuid`.

**Comment by Ellenyyyy** [comment]
1. yarn add @types/uuid -D
2.declare module 'uuid'; in d.ts file
use these two steps error disappear

**Comment by julianportelli** [comment]
> 1. yarn add @types/uuid -D
>    2.declare module 'uuid'; in d.ts file
>    use these two steps error disappear

This solved the issue for me.

**Comment by mromero-convoso** [comment]
> This breaks other packages that build over uuid like: https://github.com/VitorLuizC/vue-uuid However they continue to work by installing @types/uuid v7.0.4 ✅

Thanks! Ended up going with 7.0.3 as @types/uuid@7.0.3 and uuid@7.0.3 exist - uuid@7.0.4 does not exist and I read a couple comments down from yours that the versions of types/uuid and uuid should match.  or maybe just go with the most recent of the 7.0.x branch?

**Comment by David0z** [comment]
> > This breaks other packages that build over uuid like: https://github.com/VitorLuizC/vue-uuid However they continue to work by installing @types/uuid v7.0.4 ✅
> 
> Thanks! Ended up going with 7.0.3 as @types/uuid@7.0.3 and uuid@7.0.3 exist - uuid@7.0.4 does not exist and I read a couple comments down from yours that the versions of types/uuid and uuid should match. or maybe just go with the most recent of the 7.0.x branch?

Did the same, restarted IDE, worked 👍

**Comment by kxrna** [comment]
In case this helps anyone in the future, I had the following enabled in my `tsconfig.json`:

```typescript
"strict": true,                                   /* Enable all strict type-checking options. */
```

Disabling that got rid of the error.

**Comment by collmomo** [comment]
> > 1. yarn add @types/uuid -D
> >    2.declare module 'uuid'; in d.ts file
> >    use these two steps error disappear
> 
> Step 1 solved the issue for me.

worked after I restarted my IDE (which normally shouldn't matter)

**Comment by bdelamotte** [comment]
> In case this helps anyone in the future, I had the following enabled in my `tsconfig.json`:
> 
> ```ts
> "strict": true,                                   /* Enable all strict type-checking options. */
> ```
> 
> Disabling that got rid of the error.

You are my hero and made my day. This helped me so much.
