### ISSUE TITLE
[CI] typescript throws TypeError: ts.unescapeIdentifier is not a function

### ISSUE THREAD

**Issue by Flarna** [DefinitelyTyped/DefinitelyTyped#27016]
Typescript throws an exception in CI builds:
```
The 'no-misused-new' rule threw an error in '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/node/index.d.ts':
TypeError: ts.unescapeIdentifier is not a function
    at getIdentifierText (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tsutils/util/util.js:872:15)
    at Object.getPropertyName (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tsutils/util/util.js:208:61)
    at cb (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tslint/lib/rules/noMisusedNewRule.js:51:27)
    at visitNodes (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/typescript/lib/typescript.js:15066:30)
    at Object.forEachChild (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/typescript/lib/typescript.js:15372:21)
    at cb (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tslint/lib/rules/noMisusedNewRule.js:67:19)
    at visitNodes (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/typescript/lib/typescript.js:15066:30)
    at Object.forEachChild (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/typescript/lib/typescript.js:15292:24)
    at walk (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tslint/lib/rules/noMisusedNewRule.js:49:15)
    at Rule.AbstractRule.applyWithFunction (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
```

see e.g. https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/399575834?utm_source=github_status&utm_medium=notification (PR: #27014)

@andy-ms @RyanCavanaugh

**Comment by mhegazy** [comment]
This is caused by https://github.com/Microsoft/TypeScript/pull/25333. please see my comment in https://github.com/Microsoft/TypeScript/pull/25333#issuecomment-402242763
