### ISSUE TITLE
Compilation errors in @types/jasmine v.2.5.42

### ISSUE THREAD

**Issue by ardiadrianadri** [DefinitelyTyped/DefinitelyTyped#14569]
- [x] I tried using the `@types/jasmine` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov, @theodorejb, @davidparsson

When I try to compile my project I get the next error:
```
ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:52
    TS1005: '=' expected.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:38
    TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:46
    TS2304: Cannot find name 'keyof'.
```
A workaround that I've found is to change to version 2.5.41. I guess that the problem is in the last update of the jasmine typings

**Comment by noomorph** [comment]
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14579

I think that this is not a bug of the new jasmine typing itself, rather a bug of compatibility checking between your TypeScript version and the published type (the typing states it needs 2.1+ using a special comment).

You could either downgrade the version of typing or upgrade your TS to 2.1+ (from 2.0).

However, it is still not clear why no kind of validation is triggered when you're updating `@types`, why you are not prevented from updating to an incompatible version... that's what is weird.

**Comment by noomorph** [comment]
Could you also examine this thread: https://github.com/Microsoft/types-publisher/issues/214 ?

If I get it right, according to the discussion, TypeScript 2.1 is a stable and a backward-compatible version with 2.0 and since 30 days grace period has already passed, so the best solution is to upgrade to `2.1`.

Otherwise, you can downgrade the `@types/jasmine` version, but at the end of the day, you'll have to upgrade to TS 2.1 sometime anyway.

**Comment by stajs** [comment]
Thanks to @noomorph, the suggestion to upgrade to v2.1.x (from v2.0.x) worked for me.

**Comment by isawk** [comment]
Had similar issues, downgraded to "@types/jasmine": "2.5.38"

**Comment by noomorph** [comment]
# Please upgrade TypeScript to 2.1

According [to the thread](https://github.com/Microsoft/types-publisher/issues/214) you should not restrict updating your `typescript` devDependency to numbers like `2.0.10` or `~2.0.10`.

Instead, you need to loosen the dependency on TypeScript version: `^2.0.0`, so the version you download will be `>=2.1.0`.

Using `2.0.x` is considered legacy since `2.1.x` is backwards-compatible.

P. S. If you insist on using `2.0.x`, only then you should downgrade `@types/jasmine` to `2.5.41`. Please mind that the latter is only a temporary solution because at the end of the day other typings will also start using new TypeScript syntax and by applying this kind of solution you may run into a more severe issue when you stop receiving typings for the updated libraries' versions without event noticing that.

Can we mark this thread as resolved, @andy-ms?

**Comment by Marooned-MB** [comment]
@noomorph, I have Typescript 2.1.1 and still issues with typings (lodash, jasmine, and probably other too), so your solution does not seems to work. Any hints?

**Comment by noomorph** [comment]
@Marooned-MB , it's hard to tell without any `package.json` or compilation errors.

**Comment by Marooned-MB** [comment]
`A parameter initializer is only allowed in a function or constructor implementation.` so the same error as in 1st post

**Comment by noomorph** [comment]
@Marooned-MB , by the way, TypeScript 2.1.1 indeed has an error:

```
index.d.ts(39,52): error TS1005: '=' expected.
```

Could try to update to 2.1.6 ?

**Comment by Marooned-MB** [comment]
After upgrading TS to 2.1.6 this seems to be resolved however I have lots of other issues with dependencies, so I guess I'm stuck a bit. Thanks anyway, I'll talk to the team about it. Thanks for your help.

**Comment by IvanYurchenko** [comment]
Upgrading TS version didn't work for me as well. Only downgrading the @types/jasmine version helped. Thanks for the workaround!

**Comment by Glennvdp** [comment]
I've encountered the same error. Downgrading to previous version also worked.

**Comment by TroelsL** [comment]
Same issue with:

├──  core-js (global)
├── jasmine (global)
├── jquery (global)
├── node (global)
└── signalr (global)

Downgrading to typescript 2.1.6 worked. Latest didn't.

**Comment by pantonis** [comment]
I have typescript 2.0.3 and jasmine 2.5.38. Have the same problem. Cant upgrade typescript becuase of angular 2.

**Comment by MovGP0** [comment]
I have the same issue with `Typescript 2.6.0-rc` and `Jasmine 2.6.2`. 

**tsconfig.json**
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "strict": true,
        "noFallthroughCasesInSwitch": true,
        "sourceMap": true,
        "rootDir": ".",
        "inlineSources": true,
        "noImplicitAny": true,
        "noUnusedLocals": true, 
        "noUnusedParameters": true, 
        "lib": [
            "es6",
            "dom"
        ],
        "target": "es5",
        "skipLibCheck": true,
        "types": [
            "jasmine",
            "node"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```

**package.json**
```json
    "devDependencies": {
        "@types/jasmine": "^2.6.2",
        "@types/node": "^8.0.47",
        "jasmine-core": "2.6.2",
        "karma": "1.7.0",
        "karma-jasmine": "^1.1.0",
        "tslint": "5.4.0",
        "typescript": "2.6.0-rc",
        "//": "..."
    }
```

**Comment by sssalib42** [comment]
I'm getting this same type of error after upgrading to TS 3.1. 

What version of @types/Jasmine should I be using now?

**Comment by vladimirbat** [comment]
I have had the same problem that SanjanaTailor with following versions:
      @types/jasmine 2.8.8
      @angular 5.2
      typescript 2.5.3
My solution has been upgrading typescript to 3.1.6.
The problen si that Angular shows a Warning because it expects a typescript version lower than 2.7.

**Comment by mariohmol** [comment]
I had this issue just in travis enviroment and changin to 2.5.38 worked!

https://travis-ci.org/mariohmol/ng-gantt/builds/459888259

**Comment by amrayoub** [comment]
@isawk works great, Thanks :)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
