### PR TITLE
Update webpack-dev-server to v4

### PR DESCRIPTION
**Pull request by lex111**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - Docs - https://webpack.js.org/configuration/dev-server/
  - Migration guide from v3 to v4 - https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
  - Source of `Server` class - https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by lex111** [comment]
It looks like some of webpack-dev-server dependent packages need to be fixed to match the new v4 of webpack-dev-server. In that regard, should I make changes to fix errors only related with upgrading webpack-dev-server to v4, or do I need to completely update types of according dependent packages to major version?

File: types/webpack-dev-server/package.json [hunk 1]
```diff
@@ -1,6 +1,7 @@
 {
   "private": true,
   "dependencies": {
+    "chokidar": "^3.5.2",
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/package.json:4]:
```suggestion
    "chokidar": "^3.5.1",
```
just to match the source

File: types/webpack-dev-server/index.d.ts [hunk 2]
```diff
@@ -355,24 +276,26 @@ declare module 'webpack' {
...
-    listen(port: number, hostname: string, callback?: (error?: Error) => void): http.Server;
+    start(): void;
+
+    startCallback(callback: () => void): void;
 
-    listen(port: number, callback?: (error?: Error) => void): http.Server;
+    stop(): void;
 
-    close(callback?: () => void): void;
+    stopCallback(callback: () => void): void;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:296]: is this supposed to be unified across module and accept optional `Error | null` param?, say:
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1785
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1845
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1919
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1924

File: types/webpack-dev-server/index.d.ts [hunk 3]
```diff
@@ -108,20 +182,11 @@ declare namespace WebpackDevServer {
         /**
          * Specify a host to use. By default this is localhost.
          */
-        host?: string | undefined;
+        host: string;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts]:
```suggestion
        host?: string | undefined;
```
how otherwise it could be defaulting to `localhost`? Also:
https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1381

File: types/webpack-dev-server/index.d.ts [hunk 4]
```diff
@@ -108,20 +182,11 @@ declare namespace WebpackDevServer {
...
-         * --hot option, this plugin will be added automatically, so you may
-         * not need to add this to your webpack.config.js.
          */
-        hot?: boolean | undefined;
-        /**
-         * Enables Hot Module Replacement (see devServer.hot) without page
-         * refresh as fallback in case of build failures.
-         */
-        hotOnly?: boolean | undefined;
+        hot?: boolean | string | undefined;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:189]:
```suggestion
        hot?: boolean | 'only'| undefined;
```

File: types/webpack-dev-server/index.d.ts [hunk 5]
```diff
@@ -133,93 +198,35 @@ declare namespace WebpackDevServer {
...
-                  [key: string]: string[];
-              }
-            | {
-                  typeMap?: {
-                      [key: string]: string[];
-                  } & {
-                      force: boolean;
-                  } | undefined;
-              } | undefined;
+        onAfterSetupMiddleware?: ((server: WebpackDevServer) => void) | undefined;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:215]:
```suggestion
        onAfterSetupMiddleware?: ((devServer: WebpackDevServer) => void) | undefined;
```

File: types/webpack-dev-server/index.d.ts [hunk 6]
```diff
@@ -133,93 +198,35 @@ declare namespace WebpackDevServer {
...
         /**
-         * With noInfo enabled, messages like the webpack bundle information
-         * that is shown when starting up and after each save,will be hidden.
-         * Errors and warnings will still be shown.
+         * Provides the ability to execute custom middleware prior to all other
+         * middleware internally within the server.
          */
-        noInfo?: boolean | undefined;
+        onBeforeSetupMiddleware?: ((server: WebpackDevServer) => void) | undefined;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:220]:
```suggestion
        onBeforeSetupMiddleware?: ((devServer: WebpackDevServer) => void) | undefined;
```

File: types/webpack-dev-server/index.d.ts [hunk 7]
```diff
@@ -133,93 +198,35 @@ declare namespace WebpackDevServer {
...
         /**
          * Provides an option to execute a custom function when
          * webpack-dev-server starts listening for connections on a port.
          */
         onListening?: ((server: WebpackDevServer) => void) | undefined;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:225]:
```suggestion
        onListening?: ((devServer: WebpackDevServer) => void) | undefined;
```
can we change this as well? thx!

File: types/webpack-dev-server/index.d.ts (hunk 4 above)
Comment (lex111) [reply types/webpack-dev-server/index.d.ts:189]: I did so originally, but in my project on which I tested the change (`hot: cliOptions.hotOnly ? 'only' : true,`), I got this error:

```
[server]   Types of property 'hot' are incompatible.
[server]     Type 'string | boolean' is not assignable to type 'boolean | "only" | undefined'.
```

That's why I gave up using allowed strings in all types.

File: types/webpack-dev-server/index.d.ts (hunk 2 above)
Comment (lex111) [reply types/webpack-dev-server/index.d.ts:296]: Honestly, I'm not sure about this, maybe it's legacy from v3?

File: types/webpack-dev-server/webpack-dev-server-tests.ts [hunk 8]
```diff
@@ -1,29 +1,61 @@
...
 // Configuration can be used as a type
 const config: WebpackDevServer.Configuration = {
     // webpack-dev-server options
-    inline: true,
-    // Toggle between the dev-server's two different modes --- inline (default, recommended for HMR) or iframe.
 
-    contentBase: '/path/to/directory',
-    // or: contentBase: "http://localhost/",
-    contentBasePublicPath: '/serve-content-base-at-this-url',
+    // Host and port is a required options.
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/webpack-dev-server-tests.ts]:
```suggestion
    // Host and port are required options.
```

File: types/webpack-dev-server/index.d.ts (hunk 7 above)
Comment (lex111) [reply types/webpack-dev-server/index.d.ts]: Of course, thanks for your suggestions!

File: types/webpack-dev-server/index.d.ts [hunk 9]
```diff
@@ -355,24 +276,26 @@ declare module 'webpack' {
...
 
-    static addDevServerEntrypoints(
+    static addAdditionalEntries(
         webpackOptions: webpack.Configuration | webpack.Configuration[],
         config: WebpackDevServer.Configuration,
-        listeningApp?: WebpackDevServer.ListeningApp,
     ): void;
 
-    listen(port: number, hostname: string, callback?: (error?: Error) => void): http.Server;
+    start(): void;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:290]:
```suggestion
    /** @async */
    start(): void;
```

File: types/webpack-dev-server/index.d.ts [hunk 10]
```diff
@@ -355,24 +276,26 @@ declare module 'webpack' {
...
+
+    startCallback(callback: () => void): void;
 
-    listen(port: number, callback?: (error?: Error) => void): http.Server;
+    stop(): void;
```
Comment (peterblazejewicz) [inline types/webpack-dev-server/index.d.ts:294]:
```suggestion
    /** @async */
    stop(): void;
```

File: types/webpack-dev-server/index.d.ts (hunk 2 above)
Comment (peterblazejewicz) [reply types/webpack-dev-server/index.d.ts:296]: OK, let's go with no params callbacks, as per readme:
https://github.com/webpack/webpack-dev-server/blob/47845fb4f859388249df78af63a37a306f866201/migration-v4.md

File: types/webpack-dev-server/index.d.ts (hunk 4 above)
Comment (peterblazejewicz) [reply types/webpack-dev-server/index.d.ts:189]: can you adapt playground, so I can see the problem?:
https://www.typescriptlang.org/play?ts=4.4.0-beta#code/JYOwLgpgTgZghgYwgAgMIHsQ2AcwK5RxjCbIDeAsAFDLIAW6YA-AFzIBG66ANhHCMgA+yAOSZuATxHC8IACYRsICHIDc1AL7VqoSLEQoA8gAdimAM7lqtBmEMhJbc2CigcQjl1791VLVWoYWQQzAQRMbHwoCAAKcKxcVjQI3AIiEhAASjINX2p452R0UwzzNhNQywBeKxp6RntHUXEpTXyUqNiczN94yIIu2zZiyoA6W0aJWiZmhylkNhc8FA1MoA
thx!

**Comment by peterblazejewicz** [comment]
> It looks like some of webpack-dev-server dependent packages need to be fixed to match the new v4 of webpack-dev-server. In that regard, should I make changes to fix errors only related with upgrading webpack-dev-server to v4, or do I need to completely update types of according dependent packages to major version?

No, you can fix their version using `types/webpack-dev-server@3` added via `package.json` as direct dependency or add paths resolution to their `tsconfig.json` poiting to `v3`.

**Comment by peterblazejewicz** [comment]
I as wrote in comments, I'm not sure why docs states `host`/`port` are somehow required, this is not a case, isn't it?

File: types/webpack-dev-server/index.d.ts (hunk 4 above)
Comment (lex111) [reply types/webpack-dev-server/index.d.ts:189]: Updated playground (see https://www.typescriptlang.org/play?ts=4.1.5#code/JYOwLgpgTgZghgYwgAgMIHsQ2AcwK5RxjCbIDeAsAFDLIAW6YA-AFzIBG66ANhHCMgA+yAOSZuATxHC8IACYRsICHIDc1AL7VqoSLEQoA8gAdimAM7lqtBmEMhJbTjz4CZ8xaBXqqWqtRhZBDMBBExsfCgIAAowrFxWNHDcAiISEABKMg0fajjzMGR0U3TzNhMQywBeKxp6RntHZDAoPAgAGk085MiY7IyfOIiCPts2YsqAOltGiVomUXEpZDYWtuQNDKA) -- although there are error, but I have it locally (on TS 4.1.5):

[server] Types of property 'hot' are incompatible.
[server] Type 'string | boolean' is not assignable to type 'boolean | "only" | undefined'.
[server] Type 'string' is not assignable to type 'boolean | 'only' | undefined'.

:man_shrugging:

**Comment by lex111** [comment]
> I as wrote in comments, I'm not sure why docs states host/port are somehow required, this is not a case, isn't it?

I was also confused by this, too, but missing of these options does not prevent webpack-dev-server from successful running, so I did not make these options required (I mean, if they do not prevent execution, then they are optional)

**Comment by lex111** [comment]
> No, you can fix their version using types/webpack-dev-server@3 added via package.json as direct dependency or add paths resolution to their tsconfig.json poiting to v3.

I see, thanks, chose the option with changing of `tsconfig.json` file, suppose it's better rather then modifying `package.json` file, yes?

> Error: webpack-shell-plugin has unused path mapping for webpack-dev-server

Could you please help with fix this error?

File: types/webpack-dev-server/index.d.ts (hunk 4 above)
Comment (lex111) [reply types/webpack-dev-server/index.d.ts]: As it turned out, my mistake was not having `WebpackDevServer.Configuration` type on config object. So I commit your suggested change, thanks.

File: types/webpack-dev-server/index.d.ts [hunk 11]
```diff
@@ -38,68 +89,91 @@ declare namespace WebpackDevServer {
...
+         */
+        username?: string | undefined;
+    }
+
+    interface Configuration {
+        /**
+         * This option allows you to whitelist services that are allowed to
+         * access the dev server.
+         */
+        allowedHosts?: string | string[] | undefined;
```
Comment (alan-agius4) [inline types/webpack-dev-server/index.d.ts:164]:
```suggestion
        allowedHosts?: string | string[] |  'all' | undefined;
```

File: types/webpack-dev-server/index.d.ts [hunk 12]
```diff
@@ -355,24 +276,28 @@ declare module 'webpack' {
...
 
-    constructor(webpack: webpack.Compiler | webpack.MultiCompiler, config?: WebpackDevServer.Configuration);
+    constructor(config: WebpackDevServer.Configuration, webpack?: webpack.Compiler | webpack.MultiCompiler);
 
-    static addDevServerEntrypoints(
+    static addAdditionalEntries(
         webpackOptions: webpack.Configuration | webpack.Configuration[],
         config: WebpackDevServer.Configuration,
-        listeningApp?: WebpackDevServer.ListeningApp,
     ): void;
```
Comment (alan-agius4) [inline types/webpack-dev-server/index.d.ts:289]: /** @deprecated - use `stopCallback` or `stop` instead **/
listen(port: number, hostname: string, callback?: (error?: Error) => void): http.Server;

File: types/webpack-dev-server/index.d.ts [hunk 13]
```diff
@@ -355,24 +276,28 @@ declare module 'webpack' {
...
+    /** @async */
+    start(): void;
+
+    startCallback(callback: () => void): void;
 
-    listen(port: number, callback?: (error?: Error) => void): http.Server;
+    /** @async */
+    stop(): void;
 
-    close(callback?: () => void): void;
```
Comment (alan-agius4) [inline types/webpack-dev-server/index.d.ts:373]:
```
/** @deprecated - use `stopCallback` or `stop` instead **/
close(callback?: () => void): void;
```

**Review by alan-agius4 — COMMENTED** [review]
Couple of nits otherwise LGTM

**Comment by lex111** [comment]
@alan-agius4 just committed your suggested changes, thanks

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by alan-agius4** [comment]
```
Error in webpack-dev-server
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/webpack-dev-server/index.d.ts:285:5
ERROR: 285:5  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 288:5  jsdoc-format  jsdoc is not formatted correctly on this line
ERROR: 291:5  jsdoc-format  jsdoc is not formatted correctly on this line
```

**Review by peterblazejewicz — APPROVED** [review]
LGTM!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by lex111** [comment]
Ready to merge

**Comment by otakustay** [comment]
Hi @lex111 I have some issues using this types:

1. `Server.stop` and `Server.start` is async, should return `Promise<void>`
2. It still have a dependency to `"@types/webpack": "^4"` and this conflicts with `webpack@5`'s built-in types, causing `new DevServer` fail to pass type check
3. It seems `devServer` property is missing from `webpack.Configuration` after upgraded to `@types/webpack-dev-sever@4.0.0`

**Comment by lex111** [comment]
@otakustay thanks for pointing that out. I'll fix it later, or you can
try to do that on our own by sending PR.

2021-08-24 16:21 GMT+03:00, Gray Zhang ***@***.***>:

**Comment by otakustay** [comment]
I prefer to remove `@types/webpack` dependency from `@types/webpack-dev-server` and add a `webpack: 5.x` to `peerDependencies`, but this may further break those still on `webpack@4`. 

If removing `@types/webpack` is reasonable, I'm willing to send a PR.

**Comment by lex111** [comment]
I'm not sure what the proper solution should be here, but
webpack-dev-server v5 can work with > webpack 4.37. In any case, PR is
welcome.

2021-08-24 16:53 GMT+03:00, Gray Zhang ***@***.***>:

**Comment by latin-1** [comment]
`devServer.static` should allow `string` type as value, according to the [doc](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md) and [options schema](https://github.com/webpack/webpack-dev-server/blob/v4.0.0/lib/options.json#L482).

> Default value of the `static` option is `path.resolve(process.cwd(), 'public')` directory and enabled by default.

**Comment by otakustay** [comment]
It's easy to fix type issues, but it seems we can't get rid of `@types/webpack` since it it auto generated by DefintelyTyped, but with `@types/webpack` depended, the definition isn't compatible with webpack 5's built-in ones.

`Compiler` type not compatible:

```
Argument of type 'Compiler' is not assignable to parameter of type 'Compiler | MultiCompiler | undefined'.
  Type 'Compiler' is missing the following properties from type 'Compiler': _pluginCompat, _plugins, plugin, apply, and 17 more.ts(2345)
```

Missing `devServer` property on `Configuration` since `@types/webpack-dev-server` meges to `@types/webpack`:

```
Property 'devServer' does not exist on type 'Configuration'.ts(2339)
```

Unfortunately I didn't find a solution to make `@types/webpack-dev-server` **NOT** depending on `@types/webpack`

**Comment by janv** [comment]
`static` should allow for an array of strings or an array of `Static` configuration objects:

```ts
static?: boolean | Static | Static[] | string | string[] | undefined;
```

**Comment by latin-1** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55350
I've submitted a pr for the `static` option.
