### ISSUE TITLE
[@types/styled-components] `as` prop have a type error

### ISSUE THREAD

**Issue by ymkz** [DefinitelyTyped/DefinitelyTyped#29197]
- [x] I tried using the `@types/styled-components@3.0.1` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat 

---
I have a problem about new `as` prop.
I tried it with styled-components 4.0.0-beta.9
The `as` property have a type error that is 

```
Property 'as' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any>, any, any>> & Readonly<...> & Readonly<...>'
```

My code is 
```
import * as React from 'react'
import styled from 'styled-components'

const ContentContainer = styled.div`
  margin: 32px 0;
`

const App = () => <ContentContainer as="ul">hello</ContentContainer>

export default App
```

Is a type definition introduced to solve this problem?
Or, does anyone have a solution or workaround?

Thanks styled-components contributors!

**Comment by Igorbek** [comment]
I think typings for `styled-components@4` is still in progress. `@types/styled-components@3` is not meant to be compatible with v4.

**Comment by ymkz** [comment]
@Igorbek I see. I seem to have jumped to the conclusion.
Wait for release v4 👍

**Comment by nickmccurdy** [comment]
This should be fixed after upgrading `styled-components` and `@types/styled-components` to 4.
