### PR TITLE
Fix AMD autobahn.d.ts

### PR DESCRIPTION
**Pull request by a904guy**
to JQueryStatic style export and fix AMD require.

### CODE REVIEW

**Comment by a904guy** [comment]
Guess the tests need work as well.

**Comment by vvakame** [comment]
*autobahn/autobahn.d.ts*

to authors(@darkl). could you review this PR?
:+1: or :-1:?

check list

* [ ] pass the Travic-CI test?

---

@a904guy please fix travis ci failed. https://travis-ci.org/borisyankov/DefinitelyTyped/builds/73117142 try with `--noImplicitAny` option.

**Comment by darkl** [comment]
Hi, I'm not familiar with jquery style, but your changes make the tests not compile. (it says "Cannot find name 'autobahn'.")

So its a :-1 for now, sorry.

**Comment by a904guy** [comment]
This isn't my repo, I just wanted to add "autobahn" (quotations around the module name), so that it worked with AMD require, tsc 1.5.3 -m amd. Which it did in the pull request below.

I was informed to change it to "jquery style":  https://github.com/borisyankov/DefinitelyTyped/pull/5082

That merge above worked exactly as expected with AMD and is about to be deployed into production on an application. I was just trying to help others. Perhaps the author of the typings would rather fix it.

**Comment by a904guy** [comment]
```
require.config({
	...
	'paths': {
		...
		'autobahn': '../../autobahn/autobahn-0.9.4-2',
		'when': '../../when/2.7.1/when'
		...
	},
	'shim': {
		...
		"autobahn": {'deps': ["when"]},
		...
	},
	findNestedDependencies: true,
});
```

```
import autobahn = require('autobahn');
```

**Comment by darkl** [comment]
I think that if you'll add a directive
```typescript
import autobahn = require("autobahn");
```
to the tests, they'll compile.

**Comment by a904guy** [comment]
Alright, lets try.

**Comment by a904guy** [comment]
Sweet, Thanks!

**Comment by darkl** [comment]
:+1: @vvakame, you can merge this :)

**Comment by darkl** [comment]
Hi @a904guy,
Is there any reason you renamed the autobahn module to autobahnModule?
I prefer it unrenamed (leave the name autobahn), it makes it easier to use.

Thanks

**Comment by a904guy** [comment]
I was trying to make like jQueryStatic from the @vvakame recommendation: https://github.com/borisyankov/DefinitelyTyped/pull/5082. I'll make the changes.

**Comment by a904guy** [comment]
Fixed.

**Comment by a904guy** [comment]
@darkl, Please check now.

**Comment by darkl** [comment]
:+1: Great!
@vvakame, you can merge it now.

**Comment by a904guy** [comment]
:+1: @vvakame  :accept:

**Comment by vvakame** [comment]
@darkl thanks!
@a904guy thanks mate!

**Comment by a904guy** [comment]
@vvakame No thank you! I have a bunch of other cool ones.

Can you give me some tips on adding them to this repo?

https://github.com/a904guy/Typescript-Typings

**Comment by vvakame** [comment]
simply, please send a PR. 1 library / 1 pull request.

**Comment by a904guy** [comment]
Understood, Thank you.
