### ISSUE TITLE
[yeoman-generator] error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

### ISSUE THREAD

**Issue by FredKSchott** [DefinitelyTyped/DefinitelyTyped#11424]
- [x] I tried using the latest `yeoman-generator/yeoman-generator.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/). 
- [x] I want to talk about `yeoman-generator/yeoman-generator.d.ts`.
  - The authors of that type definition are cc/ @armorik83
  - Regression introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10888  cc/ @BurtHarris 

When running typescript on a project using the latest `dt~yeoman-generator` and latest `typescript`, I get the following error:

`
node_modules/@types/yeoman-generator/index.d.ts(36,46): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
`
#10888 seemed to have been an automatic repo-wide change that this got swept up in, @BurtHarris any objections to switching this back?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
