### PR TITLE
Improved meteor/mongo typings.

### PR DESCRIPTION
**Pull request by radekmie**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.meteor.com/api/collections.html#Mongo-Collection-rawCollection
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

I couldn't run the tests because of the `Cannot find module 'csstype'.` error.

### CODE REVIEW

**Comment by radekmie** [comment]
It looks like there's a problem because import the `mongodb` package inside the `meteor/mongo` hides the declared `Mongo` namespace. How could I proceed here?

**Comment by radekmie** [comment]
OK, is there a way to actually get some help here?

**Comment by gunn** [comment]
I'm not familiar enough to fix problem. Eliminating some `any`s seems like a worthy cause though. @filipenevola?

**Comment by nicu-chiciuc** [comment]
Did you try running 'scripts/generate-globals` for me it deletes all the files in the `globals` directory. It seems to be caused by commit `c8089e91d1be9af`, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40676. The script was using the files in `tsconfig.json` as a reference for files that have to be transformed.
I guess you modified the files in the `globals` directory manually, right?

I think the best solution would be to get rid of the `globals` directory entirely. Although, there may be people that still rely on global definitions. I'm not very experienced with this part of TS, but I guess at this point, global declarations should not be supported anymore (Although maybe someone that has more experience with this could chime in).

A temporary solution would be to remove the imports from `globals/mongo.d.ts` and leave the definitions for `rawCollection` and `rawDatabase` as `any`, for project that still rely on global imports.
