### PR TITLE
Remove package.json dependencies on @types packages

### PR DESCRIPTION
**Pull request by ghost**
We use `"baseUrl": "../"` for this instead.

### CODE REVIEW

**Comment by sandersn** [comment]
Travis fails with the claim that the definitions compile in 2.2 but not 2.0. Here's the error it sees with 2.0:

```
../q/index.d.ts(187,5): error TS1194: Export declarations are not permitted in a namespace.
```
