### PR TITLE
mocha: fix a regression bug

### LINKED ISSUE #22510: Mocha's type definitions pollute and break other node modules
For example, it changes the return type of `setTimeout` and causes some errors.

```
node_modules/spica/throttle.ts(7,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/spica/throttle.ts(28,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

This is caused by #22112.

@aozgaa Can you revert that change?

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #22510 again.

@RyanCavanaugh Can you please quickly merge and release this?

### CODE REVIEW

**Comment by 1999** [comment]
Not sure if I get the idea of this PR. `mocha` runner class inherits from node.js EventEmitter, so why do you want to do this? @falsandtru

**Comment by RyanCavanaugh** [comment]
@1999 no idea, I thought @falsandtru was doing a straight revert. We generally take PRs quickly if they are undoing a break.

**Comment by Flarna** [comment]
I expect the reason is that mocha runs also in browser therefore references to NodeJs are not really correct. Maybe add a reference to `@types/events` instead NodeJs?

**Comment by falsandtru** [comment]
If it don't pollute global declarations and don't make conflict with other libraries and popular names.

**Comment by Flarna** [comment]
NodeJS is a complete runtime which contains modules - not just one module. Similar as the browser runtime also NodeJS has globals like e.g. `setTimeout()`. But the globals in NodeJs don't match to that one in browser therefore adding NodeJS type definitions in a browser context is not nice - similar the need for browser stuff like DOM in a NodeJS project is not nice.

Regarding events: The browser variant of Mocha uses [browserify](https://github.com/browserify/browserify) to create mocha.js which bundles also events. A closer look has shown that browserify depends on [events](https://github.com/Gozala/events) which source is then bundled into mocha.js - not that one from NodeJs.
Module events seems to be a (not up to date) copy of NodeJs events; APIs added during last years like  `prependListener()` are missing in events.

To may understanding the main issue here is that Mocha uses NodeJS events if used in NodeJS context but events module in browser context. Don't know if this can be modelled somehow.
If the use case is just to register some handler via the `on()` method it should be don't care as both of them offer it.
