### ISSUE TITLE
[@types/lodash]: pickBy has incorrect signature when using it with Dictionary

### ISSUE THREAD

**Issue by vvlevykin** [DefinitelyTyped/DefinitelyTyped#24133]
- [x] I tried using the `@types/lodash` package and had problems. (version 4.14.104)
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

After upgrading to 4.14.104, the error appears when trying to filter a `Dictionary<number>` with `_.pickBy` and reassign to the same variable:
```
error TS2322: Type 'Partial<Dictionary<number>>' is not assignable to type 'Dictionary<number>'.
  Index signatures are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
```
The code is similar to this:
```typescript
let mapping: Dictionary<number> = {key1: 5, key2: -3}
mapping = _.pickBy(mapping, v => v > 0)
```
Ideally, the result of `_.pickBy` has to be also a `Dictionary<T>` in this case. 
After all, the new object is created which doesn't have some of the keys.
It is not the same as the object that has some of the values changed to `undefined`.

@andy-ms @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR

**Comment by aj-r** [comment]
For now there's a workaround: use `Dictionary<number | undefined>` everywhere.

```ts
let mapping: Dictionary<number | undefined> = {key1: 5, key2: -3}
mapping = _.pickBy(mapping, v => v > 0)
```

**Comment by aj-r** [comment]
@vvlevykin I think this is fixed since `@types/lodash@4.14.105`. Can you try with the latest version, and close this issue if it works?

**Comment by vvlevykin** [comment]
Appears to be working, thanks!

**Comment by 2016bmw** [comment]
@aj-r I'm still seeing this issue in `@types/lodash@4.14.109` with Dictionary<number> as well as dictionaries of types I've defined myself. I tried typescript 2.7.2 and 2.9.2. Is this expected?

**Comment by farzadmf** [comment]
Today, I also updated my TypeScript version and other package versions (including `@types`), and I'm seeing this error :(

**Comment by aj-r** [comment]
I'm looking at the history of `pickBy`, and it looks like it hasn't changed since February. That said, I'm still reproducing the issue. It looks like this was fixed for `pick`, but not for `pickBy`.

I'll see if there's any way to fix `pickBy`, but there may not be a good solution (without using conditional types, which we can't use because we still need to support TS 2.2).

**Comment by ypresto** [comment]
With this change pickBy returns Dictionary<T> for non-dictionary plain object (`interface Foobar {...}` or `type Foobar = {...}`).
Also, `pickBy<Type>()` does not select desired overload (`pickBy<T extends object>(object: T | null | undefined, predicate?: ValueKeyIteratee<T[keyof T]>): PartialObject<T>;` ).
