### ISSUE TITLE
 @types/mongoose has no exported member 'ChangeStreamOptions' and 'ChangeStream'

### ISSUE THREAD

**Issue by kolya182** [DefinitelyTyped/DefinitelyTyped#23275]
My code:
`import * as mongoose from "mongoose";` // 5.0.0

`const options: any = {
            autoIndex: true,
            poolSize: 500,
            reconnectTries: Number.MAX_VALUE,
           reconnectInterval: 1000
        };`

`mongoose.connect(dbURI, options)`

Error:
`node_modules/@types/mongoose/index.d.ts(2392,29): error TS2694: Namespace '"/Users/mykola/Dropbox/git/project/node_modules/@types/mongodb/index"' has no exported member 'ChangeStreamOptions'.`

`node_modules/@types/mongoose/index.d.ts(2392,77): error TS2694: Namespace '"/Users/mykola/Dropbox/git/project/node_modules/@types/mongodb/index"' has no exported member 'ChangeStream'.`

`src/models/Database.ts(24,9): error TS2531: Object is possibly 'null'.` // points to code above(mongoose.connect)

Works fine with `@types/mongoose 4.7.29`

**Comment by cdupetit** [comment]
@kolya182 :
I have the same issue. Can you tell me why did you close this issue ?

**Comment by kolya182** [comment]
I think i was outdated `mongodb` package. Currently i have `@types/mongodb": "^3.0.2`, `@types/mongoose": "^5.0.1`, `mongoose": "^5.0.3` and it works fine.

**Comment by cdupetit** [comment]
@kolya182 thanks for your answer.
I'm using `"@types/mongoose": "^5.0.1"` and `"mongoose": "^5.0.3"`.
But I still have the same error messages, as travis. Can you reopen this issue, please ?

**Comment by kolya182** [comment]
@cdupetit I think this PR should fix the issue https://github.com/jdesboeufs/connect-mongo/pull/275

**Comment by ntwaricliberi** [comment]
same issue, any solution ?

**Comment by tomavic** [comment]
Still issue exists with Mac Book M1
