### ISSUE TITLE
version 18.8.4 , dom onclick event type error，18.8.3 is normal 

### ISSUE THREAD

**Issue by FrontEndDog** [DefinitelyTyped/DefinitelyTyped#62667]
node version 14.19.3

**Comment by daniluk4000** [comment]
Same error with most of DOM types

**Comment by heavenshell** [comment]
I've got below type errors when updated to v18.8.4.

```
tsc -p tsconfig.json --noEmit
node_modules/@storybook/api/dist/ts3.9/modules/shortcuts.d.ts:55:18 - error TS2430: Interface 'Event' incorrectly extends interface 'KeyboardEvent'.
  Types of property 'target' are incompatible.
    Property 'prototype' is missing in type '{ tagName: string; addEventListener(): void; removeEventListener(): boolean; dispatchEvent(event: Event): boolean; getAttribute(attr: string): string | null; }' but required in type 'EventTarget'.

55 export interface Event extends KeyboardEvent {
                    ~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5162:5
    5162     prototype: EventTarget;
             ~~~~~~~~~
    'prototype' is declared here.


Found 1 error in node_modules/@storybook/api/dist/ts3.9/modules/shortcuts.d.ts:55
```

**Comment by FrontEndDog** [comment]
This may be a problem with vue，please see

https://github.com/vuejs/core/pull/6855

**Comment by daniluk4000** [comment]
@FrontEndDog I still use Vue 2.6.12. The only thing I updated is @types/node. 

I've created a very simple reproduction of my problem here: https://github.com/daniluk4000/types-node-error

**Comment by FrontEndDog** [comment]
> @FrontEndDog I still use Vue 2.6.12. The only thing I updated is @types/node.
> 
> I've created a very simple reproduction of my problem without 3rd-party libs here: https://github.com/daniluk4000/types-node-error

yes，I reappeared， This problem still exists with 18.8.5

**Comment by falsandtru** [comment]
#62729 will fix them.

**Comment by kesupile** [comment]
Hello! I've also encountered a similar issue with DOM types. In my case the `HTMLElement` type is showing some strange/incorrect behaviour.

**Version 18.8.3** ✅
<img width="521" alt="image" src="https://user-images.githubusercontent.com/13475147/196229936-0d1884bb-3d5f-45b8-a558-e7928a55c6f5.png">

**Version 18.8.4** ❌
<img width="552" alt="image" src="https://user-images.githubusercontent.com/13475147/196230277-8cafd269-c8eb-4b0e-815a-960d1a5bab3f.png">

`element` should be `() => HTML | null` inside the type guard, but it is still `MaybeFn`. This problem is still present in the latest release (`v18.11.0`)
