### ISSUE TITLE
[@types/mongodb] Property 'isConnected' does not exist on type 'Server'

### ISSUE THREAD

**Issue by fabiooshiro** [DefinitelyTyped/DefinitelyTyped#43391]
Hi @rifler
- [x] I tried using the `@types/mongodb` package and had problems.

```js
import { MongoClient, Db } from "mongodb";
let db: Db = /*async getDb... */
db.serverConfig.isConnected()
```

```
error TS2339: Property 'isConnected' does not exist on type 'Server | ReplSet | Mongos'.
  Property 'isConnected' does not exist on type 'Server'.
```

**Comment by rifler** [comment]
You think I broke it in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43279 ?

**Comment by peterblazejewicz** [comment]
@fabiooshiro which version of driver api you're using?

**Comment by fabiooshiro** [comment]
Hi, the version is
"@types/mongodb": "^3.5.3",

**Comment by aldo-sanchez** [comment]
I'm seeing the same with `client.isConnected`

```Property 'isConnected' does not exist on type 'Mongo'.```

**Comment by peterblazejewicz** [comment]
I'll try to be on the same page, I believe `MongoClient.isConnected({}?)` method works OK, with current types and driver 3.6,
```ts
const client = new MongoClient('mongodb://localhost:27017', {
  useUnifiedTopology: true,
});
(async () => {
    await client.connect()
    if (client.isConnected()) {
        await client.close();
    }
})();
```
The server fires events, including 'connected', has no direct API on the surface to check connection status IMO:
http://mongodb.github.io/node-mongodb-native/3.6/api/Server.html#event:connect
(I could be wrong on this, never had to write a code to check the server status that way, client is enough)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
