### ISSUE TITLE
Fix the declaration of JQueryStatic.fn

### ISSUE THREAD

**Issue by StevenLiekens** [DefinitelyTyped/DefinitelyTyped#12685]
- [x] I want to talk about `jquery/jquery.d.ts`.
  - The authors of that type definition are cc/ @borisyankov @choffmeister @Steve-Fenton @Diullei @tasoili @jasons-novaleaf @seanski @Guuz @ksummerlin @basarat @nwolverson @derekcicerone @AndrewGaspar @jameshfisher @seikichi @benjaminjackman  @JoshStrobl @johnnyreilly @DickvdBrink

- [x] I want to talk about `jquery.dataTables/jquery.dataTables.d.ts`.
  - The authors of that type definition are cc/ @Silver-Connection @omidkrad @pragmatrix @CNBoland 
---
The static property`JQueryStatic.fn` (AKA `jQuery.fn` or `$.fn`) is declared as `any` which makes it impossible for plugin authors to write proper type declarations.

An example of such a plugin is the DataTables plugin, which has a handful of static functions that you can access via `$.fn.dataTables`.

In jquery/jquery.d.ts
```ts
fn: any;  //TODO: Decide how we want to type this
```

In jquery.dataTables/jquery.dataTables.d.ts
```ts
//TODO: Wrong, as jquery.d.ts has no interface for fn
//interface JQueryStatic {
//    dataTable: DataTables.StaticFunctions;
//}
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L966
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery.dataTables/jquery.dataTables.d.ts#L17-L20

Example: https://datatables.net/reference/api/$.fn.dataTable.tables()
```ts
// get all DataTables on the page.
let tables: DataTables.DataTable[] = $.fn.dataTables.tables() as DataTables.DataTable[];
```

Here, the inferred return type of `tables()` is `any` because the type of `fn` is `any`, but the actual return type is an array of `DataTable`.

**Comment by johnnyreilly** [comment]
PRs are always welcome!

**Comment by StevenLiekens** [comment]
I don't know what the type of `JQueryStatic.fn` should be. I was thinking it could be an empty interface.

```ts
fn: JQueryPlugins;
```
```ts
interface JQueryPlugins {
}
```

Then, individual plugins can add their APIs by declaring them inside the `JQueryPlugins` namespace (because apparently [merging interfaces with namespaces is a thing](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) in TypeScript).

```ts
namespace JQueryPlugins {
    export interface dataTables {
        tables(): DataTables.DataTable[];
    }
}

Would that work?

**Comment by StevenLiekens** [comment]
Alternative way that is more closely aligned with how the original author(s) intended it.

In jquery/jquery.d.ts
```ts
fn: JQueryPlugins;
```
```ts
export interface JQueryPlugins {
}
```
---
In jquery.dataTables/jquery.dataTables.d.ts
```ts
export interface JQueryPlugins {
    dataTables: DataTables.StaticFunctions
}
```

**Comment by johnnyreilly** [comment]
I like the second approach. I can't think of any problems with it right now either... I don't know if this would have an impact on type definitions of existing plugins - probably?

**Comment by CNBoland** [comment]
I played around with @StevenLiekens second approach and it seems an elegant solution. Proposed changes are here: https://github.com/CNBoland/DefinitelyTyped/commit/e0c699038ccc94ff58b1526f80f09e4267c93399

In jquery/index.d.ts, I used JQueryPlugins as @StevenLiekens proposed, but had it extend the JQuery interface since $.fn represents the jQuery prototype.

**Comment by hauke-w** [comment]
@CNBoland thank you for your implementation. However, I think it would be better not to extend the `JQueryPlugins` interface with the `JQuery` interface. If `JQueryPlugins extends JQuery` you cannot both define a plugin function in Jquery interface and use static members of the plugin.
The following example does not compile:
```javascript
interface JQueryPlugins {
   // this does not compile because of the myPlugin function in JQuery (see below).
    myPlugin: MyPluginStatic
}

interface JQuery {
    myPlugin(): void;
}

interface MyPluginStatic {
    settings: { name: string }
    staticPluginFunc(...args: any[]): void
}
```
@StevenLiekens data-table example will not compile for the same reason if a dataTables function is defined in interface JQuery.
However, both examples compile without errors if JQueryPlugins is defined as follows in the JQuery d.ts file:
```javascript
interface JQueryPlugins {
    extend(source: any): void;
}
```
Then one could use the example plugin as follows:
```javascript
$.fn.myPlugin.settings = { name: "..." }
$("#x").myPlugin();
```
With my suggestion you cannot access all defined JQuery funtions from `$.fn` but I do not see a usecase in which this would be needed.

**Comment by StevenLiekens** [comment]
Hold on. If `$.fn` is the prototype of `$` then why are we considering having `$.fn` extend `$` instead of the other way around?

I believe this is more correct.

```ts
interface JQueryPlugins { }

interface JQuery extends JQueryPlugins { ... }

interface JQueryStatic {
    fn: JQueryPlugins;
}
```

**Comment by StevenLiekens** [comment]
`$.fn` has properties (methods) that are redefined on `$` with different signatures.

```ts
// usage: $('li').each(function(index) { var value = this; ... })
jQuery.fn.each = (callback) => jQuery

// usage: $.each($('li'), function(index, value) { ... })
jQuery.each = ( array, callback ) => void  |  ( object, callback ) => void
```

Correct me if I'm wrong. That's called shadowing in JavaScript and you can't represent that using inherited types in TypeScript.

I believe the right implementation has separate interfaces for `$` and `$.fn`. The interfaces do not extend each other. Instead they contain duplicate code for non-shadowed functions.

**Comment by leonard-thieu** [comment]
Since `jQuery.fn` aliases `jQuery.prototype`, I'm proposing that `fn` be defined as:
```typescript
interface JQueryStatic {
    // ...
    readonly fn: JQuery;
    // ...
}
```
This matches existing patterns in TypeScript's own ES definitions:
- [Object](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L136)
- [Function](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L291)
- [String](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L428)
- [Boolean](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L445)
- [Number](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L482)
- [Date](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L787)
- [RegExp](https://github.com/Microsoft/TypeScript/blob/v2.3.3/lib/lib.es5.d.ts#L855)

jQuery plugins can use the following pattern:

- Define an `interface` with static members and the plugin function

```typescript
interface MyPlugin {
    // Static member
    enabled: boolean;

    // Plugin function
    (): JQuery;
}
```

- and then declare a property of that type on `JQuery`

```typescript
interface JQuery {
    myPlugin: MyPlugin;
}
```
This allows it to be used like:
```typescript
$().myPlugin() === $();

$.fn.myPlugin.enabled === true;
```
For a more complete example, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16755

This change causes errors for the following:
### intl-tel-input
```
intl-tel-input-tests.ts(39,37): error TS2339: Property 'getCountryData' does not exist on type '{ (method: "destroy"): void; (method: "getExtension"): string; (method: "getNumber"): string; (me...'.
intl-tel-input-tests.ts(41,19): error TS2339: Property 'loadUtils' does not exist on type '{ (method: "destroy"): void; (method: "getExtension"): string; (method: "getNumber"): string; (me...'.
```
### jquery
```
jquery-tests.ts(2694,15): error TS2339: Property 'extend' does not exist on type 'JQuery'.
```
### jquery.ajaxfile
```
jquery.ajaxfile-tests.ts(24,67): error TS2339: Property 'ajaxWithFile' does not exist on type 'JQuery'.
```
### jquery.cycle
_This one doesn't appear to be related to the change_
```
jquery.cycle-tests.ts(262,24): error TS2339: Property 'pinch' does not exist on type '{ [key: string]: ($cont: JQuery, $slides: JQuery, options: CycleOptions) => void; }'.
Package compiles in TypeScript 2.2 but not in 2.0.
You can add a line '// TypeScript Version: 2.2' to the end of the header to specify a newer compiler version.
```
### jquery.tooltipster
```
jquery.tooltipster-tests.ts(41,33): error TS2345: Argument of type '{ position: string; }' is not assignable to parameter of type 'string'.
```
### pickadate
```
pickadate-tests.ts(29,25): error TS2339: Property 'defaults' does not exist on type '{ (keyword: "picker"): DatePicker; (objectName: "$node"): JQuery; (objectName: "$root"): JQuery; ...'.
pickadate-tests.ts(208,25): error TS2339: Property 'defaults' does not exist on type '{ (keyword: "picker"): TimePicker; (objectName: "$node"): JQuery; (objectName: "$root"): JQuery; ...'.
```
### qtip2
```
qtip2-tests.ts(1050,12): error TS2339: Property 'defaults' does not exist on type '{ (options?: QTipOptions): JQuery; (methodName: "api"): Api; (methodName: "option", propertyName:...'.
```
### simplebar
```
simplebar-tests.ts(3,32): error TS2339: Property 'noConflict' does not exist on type '(options?: SimplebarOptions) => JQuery'.
```
I didn't include packages where the error was:
```
Warning: ts.forEachLeadingCommentRange is not a function
Warning: ts.isWhiteSpaceLike is not a function
ts.forEachLeadingCommentRange is not a function
```
because I'm not sure if it's an actual error (although I think it might be). 
These packages would need to be fixed using the jQuery plugin pattern described above before going through with this change.

Full build log can be found at [here](https://gist.github.com/leonard-thieu/34b4f232527dc652bd10c2404fc781c8).

There shouldn't be a need to define additional types. I believe this correctly represents jQuery's implementation.

**Comment by johnnyreilly** [comment]
Feel free to submit a PR. We need fully passing build/tests before we'll merge though.

**Comment by leonard-thieu** [comment]
Alright, I'll start working on it.

**Comment by leonard-thieu** [comment]
Could I get an explanation for what this build error indicates?
```
Warning: ts.forEachLeadingCommentRange is not a function
Warning: ts.isWhiteSpaceLike is not a function
ts.forEachLeadingCommentRange is not a function
```

**Comment by hermanho** [comment]
It breaks the projects when compiling typescript with jQuery plugin that require static methods and property (like default settings plugin). Why just change patch version number only? It is not backwards-compatible.

**Comment by leonard-thieu** [comment]
`types-publisher` tracks the MAJOR.MINOR version of the target package leaving only the patch number to work with. I fixed any packages that broke because of the change but if they didn't have a test covering it, I would've missed it. If there's any packages that were missed, you can file an issue (or a PR!) to get it fixed.
