### PR TITLE
[lodash] Placeholder support

### LINKED ISSUE #24602: `placeholder` is missing from `lodash/fp`
- [x] I tried using the `@types/lodash` package and had problems.
- Authors: @bczengel @chrootsu @stepancar @aj-r @Ailrun @e-cloud @thorn0 @jtmthf @DomiR 

Attempting to use `import { placeholder } from 'lodash/fp'` causes an error.
```
Module "@types/lodash/fp" has no exported member 'placeholder'.

`placeholder` is often used in curried functions to change argument order.

### PR DESCRIPTION
**Pull request by aj-r**
- Placeholder support for curried functions
- Placeholder support for auto-curried `fp` functions (fixes #24602)
- Support importing `"lodash/fp/placehoder"` and the alias `"lodash/fp/__"`

Unfortunately, since this required adding a ridiculous number of new overloads, it caused the tests to run out of memory. To fix the tests, I needed to do the following:
- Removed parameterless generated overloads (e.g. `interface LodashPick { (): LodashPick; ... }`). I don't see any use case for these overloads (they don't really do anything), so I removed them to free up some space.
- Removed all jsdoc comments from the `fp` function definitions. This is unfortunate, but it made the biggest difference by far in the performance of the tests.
- Combined FP code into one file. Now all function definitions are inside `fp.d.ts`, instead of being distributed among hundreds of files. Unfortunately this change makes the diff very hard to read, but it's necessary in order to make the tests pass.

So there are some drawbacks, but I think the value of placeholder support outweighs them all.

Template:

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/lodash/lodash/wiki/FP-Guide#placeholders
- [x] Increase the version number in the header if appropriate. (N/A)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by andnp — APPROVED** [review]

**Comment by aj-r** [comment]
@andy-ms This PR has been approved for 8 days. Can it be merged? The build error is lowdb, not lodash.

**Comment by maximeag** [comment]
Hi guys,

Since this PR I can't include a single function from fp module :

```ts
import * as flow from "lodash/fp/flow";
```

When compiling I have now this issue :

```log
error TS2497: Module '"node_modules/@types/lodash/fp/flow"' resolves to a non-module entity and cannot be imported using this construct.
```

Error with `@types/lodash: 4.14.111`, works with `@types/lodash: 4.14.106`.

**Comment by andy-ms** [comment]
@maximeag You should probably be using `import flow = require("lodash/fp/flow")`. It's not an ES6 module, instead a function is directly exported.

**Comment by antgonzales** [comment]
I realize this is an old change but does this effectively mean that `lodash/fp` has no type checking? I'm not able to see any errors. Example:
```
lodash/fp/getOr('test', 'test', 'test') // No errors
lodash/get('test', 'test') // 2345: Argument of type 'string' is not assignable to parameter of type 'Readonly<Record<string, any>>'.
```
