### PR TITLE
[react-native] Change ColorValue type so that it can be assignable from objects

### LINKED ISSUE #46864: [@types/react-native] Cant assign ColorValue from object
`ColorValue` was introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963
```
declare const OpaqueColorValue: unique symbol;
type OpaqueColorValue = typeof OpaqueColorValue;

export type ColorValue = string | OpaqueColorValue;
```

However, this now breaks if they are assigned to an object:
```
function test(): ColorValue {
  return "foo";
}

const colors = {
  foo: test(),
};

const styles = StyleSheet.create({
  checked: {
    color: colors.foo,
  },
});
```

Results in:
```
error TS2322: Type 'string | symbol' is not assignable to type 'string | unique symbol | undefined'.
  Type 'symbol' is not assignable to type 'string | unique symbol | undefined'.
```

Authors:
@alexbrazier 

Reviewers:
@zoontek
@rickhanlonii
@dotconnor
@TheSavior
@pesoklp13
@alloy
@tom-un

Version:
typescript: 3.9.7
@types/react-native: 0.63.8

### PR DESCRIPTION
**Pull request by rurikoaraki**
Fixes #46864

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46864
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This PR fixes an issue where you cannot assign ColorValues from an object to another object. If you have an object that has many ColorValues as property values, the current typing makes it very difficult to work with them unless you add casts to deal with the type mismatch. See https://github.com/microsoft/fluentui-react-native/pull/694 as an example. The new typing is based off a suggestion taken from the issue linked above.

### CODE REVIEW

File: types/react-native/index.d.ts [hunk 1]
```diff
@@ -6037,9 +6037,7 @@ interface PlatformWebStatic extends PlatformStatic {
     OS: 'web';
 }
 
-declare const OpaqueColorValue: unique symbol;
-type OpaqueColorValue = typeof OpaqueColorValue;
-
+type OpaqueColorValue = symbol & { __TYPE__: 'Color' };
```
Comment (TheSavior) [inline types/react-native/index.d.ts:6040]: This needs to still have `unique`, right? Otherwise someone could pass in any symbol, which would be invalid, right?

Comment (rurikoaraki) [reply types/react-native/index.d.ts:6040]: The `{ __TYPE__: 'Color'}` part of the `ColorValue` type will make it so that you can't just pass any symbol. If you try something like

```
const Test = () => (
    <View
        style={{
            backgroundColor: Symbol('test'),
        }}
    />
);
```

that won't work. This is one of the suggested ways to approximate the opaque typing in Flow in TS (ex. [here](https://github.com/niieani/typescript-vs-flowtype#opaque-type-alias)).

However this would be allowed:

```
type TestType = symbol & {readonly __TYPE__: 'Color'};
const Test = () => (
    <View
        style={{
            backgroundColor: Symbol('test') as TestType,
        }}
    />
);
```

If this is an issue, then I would need to go back to the drawing board and find a different solution, and I'd be happy to hear suggestions for other things to try. The issue I'm having with using unique symbol is that you can't assign it from an object, and so if you have objects that hold color information as a bunch of properties that map to ColorValue (like theming objects), you end up needing to cast a lot of objects to force things to work.

For what it's worth, this works with the current definition, so I'm not sure if the above being allowed is much worse:

```
const Test = () => (
    <View
        style={{
            backgroundColor: Symbol('test') as ColorValue,
        }}
    />
);
````

Comment (ca057) [reply types/react-native/index.d.ts:6040]: Sounds legit to me as a user!

Comment (rurikoaraki) [reply types/react-native/index.d.ts:6040]: Any additional thoughts in response to my comments?

Comment (TheSavior) [reply types/react-native/index.d.ts:6040]: I don't know TypeScript well enough to be able to really review this. I agree that this seems to fix a thing that *should* be able to be used as a color. My biggest concern would be if this allows additional things as colors that shouldn't be. I'm not sure what those would be though. 

I'll approve this though, worst case we can fix forward if needed.

**Review by elicwhite — APPROVED** [review]

File: types/react-native/index.d.ts (hunk 1 above)
Comment (rurikoaraki) [reply types/react-native/index.d.ts:6040]: Thanks, I appreciate it! It's a fair concern, if a fix is necessary I can help out with fixing it.

**Comment by rurikoaraki** [comment]
Ready to merge
