### PR TITLE
Fix pdfjs-dist typings to use proper reflect lib dom

### PR DESCRIPTION
**Pull request by smoke**
It was giving the following error 
`ERROR in node_modules/@types/pdfjs-dist/index.d.ts(7,1): error TS1084: Invalid reference directive syntax.`

The regression was introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33558/commits/46096ba4f75f6c76d1ea20c02f93e9829508c77b#diff-21e9d6e91ee2c9204daebf0a94339b21R7

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by smoke** [comment]
@sandersn @1999 @jbaldwin can you please check this quick PR the fix is simple, but the error is quite confusing.

**Review by 1999 — COMMENTED** [review]
This is an issue with TS version from what I understand: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36585#issuecomment-509272146
