### ISSUE TITLE
latest node.d.ts incompatible with tsc 1.8.7

### ISSUE THREAD

**Issue by hewholived** [DefinitelyTyped/DefinitelyTyped#8514]
- [x] I tried using the latest `node/node.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript

Looks like the commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/81506d0602d4f15b153c6a8a7657a45e42c8346f breaks it.

**Comment by ericmdantas** [comment]
Same here. Here are the errors:

```
typings/main/ambient/node/node.d.ts(1761,52): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1762,76): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1763,52): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1763,96): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1773,54): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1774,74): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1775,54): error TS1005: '=' expected.
typings/main/ambient/node/node.d.ts(1775,94): error TS1005: '=' expected.
```

**Comment by vvakame** [comment]
I can't reproduce your issue.
Please tell me how is it reproduce?

```
$ tsc -v
Version 1.8.7
$ git rev-parse master
0d622d857f97d44ea7dcad2b3edec1f23c48fe9e
$ tsc node/node-tests.ts --allowUnreachableCode --target es6 --module commonjs --noImplicitAny
```

**Comment by vvakame** [comment]
FYI https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8519

**Comment by hewholived** [comment]
The issue is with typescript projects that depend on tsd for their type definitions. Looks like tsd is tuck with typescript 1.7 and does not understand the new enum types introduced in 1.8.

**Comment by vvakame** [comment]
Does your tsd.json contains `borisyankov/DefinitelyTyped`? You should replace to `DefinitelyTyped/DefinitelyTyped` it. repository is renamed.

**Comment by mateusdemboski** [comment]
Same problem mentioned by @ericmdantas

**Comment by mateusdemboski** [comment]
problem solved updating the VS plugin to latest version

**Comment by ericmdantas** [comment]
@mateusdemboski Is there any mention to the fix n the changelog?

**Comment by vapits** [comment]
I have the exactly same problem

**Comment by vapits** [comment]
@mateusdemboski VS plugin? Could you provide more infos?

**Comment by vapits** [comment]
@vvakame I did renamed the repo as it should be and reinstall from this repo everything, still the same issue though :/

**Comment by MpStyle** [comment]
I have the same issue
```
Using tsc v1.7.3
/project/src/public/ts/lib/node.d.ts(83,23): error TS1110: Type expected.
/project/src/public/ts/lib/node.d.ts(1835,52): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1836,76): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1837,52): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1837,96): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1847,54): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1848,74): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1849,54): error TS1005: '=' expected.
/project/src/public/ts/lib/node.d.ts(1849,94): error TS1005: '=' expected.
```

**Comment by mateusdemboski** [comment]
@vapits  Yes, I use VisualStudio 2015 for my project... (Sorry for the time to answer)

**Comment by hewholived** [comment]
I finally figured out what the problem was. I was using an older version of tsify package that referenced tsc 1.7.5. After upgrading tsify to 0.14.1 everything works just fine.

**Comment by andrewconnell** [comment]
Same issue, but to mitigate the others posting about Visual Studio in this thread, it's not related to Visual Studio or some addin... different root cause. Same issue when running with latest type def & latest TypeScript compiler (tsc 1.8.7).

**Comment by asimo** [comment]
Anybody have a fix for this?

+1 andrewconnell,   but

**tsc Version 1.8.10** I also tried changing repo vvakame solution.

server/typings/node/node.d.ts(83,23): error TS1110: Type expected.
server/typings/node/node.d.ts(1916,52): error TS1005: '=' expected.
server/typings/node/node.d.ts(1917,76): error TS1005: '=' expected.
server/typings/node/node.d.ts(1918,52): error TS1005: '=' expected.
server/typings/node/node.d.ts(1918,96): error TS1005: '=' expected.
server/typings/node/node.d.ts(1928,54): error TS1005: '=' expected.
server/typings/node/node.d.ts(1929,74): error TS1005: '=' expected.
server/typings/node/node.d.ts(1930,54): error TS1005: '=' expected.
server/typings/node/node.d.ts(1930,94): error TS1005: '=' expected.

**Comment by vvakame** [comment]
umm... I can't reproduce this issue.
and this repository support latest stable tsc only. it is 1.8.10 now.

**Comment by asimo** [comment]
Thanks for looking- although I still get error, it is compiling! That's
good enough for me at this point and I will look into errors.

**Comment by alexwakeman** [comment]
Anyone considered it's actually a problem with the node.d.ts file?

I'm getting errors in my IDE (WebStorm) even before using it as a reference in build. 

E.g. EventEmitter is not implementing all methods in NodeJS.EventEmitter - which in itself is quite strange.

**Comment by alexwakeman** [comment]
Actually thinking the node.d.ts file has incorrect syntax although can't be sure at this point.

**Comment by alexwakeman** [comment]
I'm assuming that everyone with this error is using gulp as a build-chain tool - and specifically gulp-typescript.

The fix for this is to use the latest version of typescript within gulp-typescript...

First thing is to update `package.json` inside `node_modules/gulp-typescript`. Specifically, under "dependencies":

`"typescript": "^1.8.10"`

Then run npm install within the `gulp-typescript` directory.

Try to compile your project again, and the errors should be gone.

**Comment by bandico0t** [comment]
@alexwakeman I'm using last version of gulp-typescript and tcs, but still have this errors.
I've tried to compile project with comand line like:
`M:\Projects\ProjectName\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\tsc\tsc.exe --project "M:\Projects\ProjectName\tsconfig.json" ` but error still appear

Tsc:
`M:\Projects\ProjectName\packages\Microsoft.TypeScript.MSBuild.1.8.11\tools\tsc\tsc.exe -v
1.8.10`

My tsconfig.json is:
```json
{
  "compilerOptions": {
    "outDir": "wwwroot/app",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "noEmitOnError": true
  },
  "exclude": [
    "gulpfile.ts",
    "node_modules",
    "typings"
  ]
}```

**Comment by mhegazy** [comment]
@ivogabe any ideas?

**Comment by andrewconnell** [comment]
@bandico0t why are you excluding `typings`? That's only used by the compiler & your editor... but excluding it from your build makes me wonder why you even bother getting type definitions... care to share?

**Comment by bandico0t** [comment]
@andrewconnell, actually I've tried to make my project works.
This version of tsconfig is a combination of tsconfigs from plenty topics about solving problem with angular2/typescript.
I can remove this exclude if it can help.

**Comment by bandico0t** [comment]
Finally, I've solved my problem.
I'm using MS Visual Studio for development and when I deleted this three lines:
```
"inlineSourceMap": true,
"inlineSources": true,
"noEmitOnError": true
```
it has worked
Thanks

**Comment by ivogabe** [comment]
@mhegazy It appears to be working with the latest version of gulp-typescript.

**Comment by ramik91** [comment]
@ivogabe +1 updating gulp-typescript lib solved the problem

**Comment by AJamesPhillips** [comment]
Can we close this issue now please?
