### PR TITLE
express-serve-static-core: Restore compatibility with ts2.1

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20820#issuecomment-339445516

Reverts `express-serve-static-core` and its dependent packages to compatibility with TypeScript 2.1 by removing type parameters from `Request`. A specifically-typed `Request` can still be obtained by extending the interface and overriding properties.

Also reverts `// TypeScript Version` comments of popular packages so that any future incompatities will be more noticeable.

### CODE REVIEW

**Review by mhegazy — APPROVED** [review]

**Review by MichalLytek — APPROVED** [review]

**Comment by andy-ms** [comment]
Test failure fixed by #21045

**Comment by rhyek** [comment]
@andy-ms i'm having an issue with express@4.16.2; express-serve-static-core@4.11.0. I get  `node_modules/@types/express/index.d.ts(84,15): error TS2315: Type 'Request' is not generic.`.

Related: #21022

**Comment by 19majkel94** [comment]
@rhyek Because generics were rollbacked:
> Reverts express-serve-static-core and its dependent packages to compatibility with TypeScript 2.1 by removing type parameters from Request.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20820#issuecomment-339445516

You need to make the generic by yourself:
```ts
import { Express } from "express";

declare module "express" {
  export interface Request<
    Body = any,
    Query = any,
    Params = any,
    Cookies = any,
  > extends Express.Request {
    body: Body;
    query: Query;
    params: Params;
    cookies: Cookies;
  }
}
```
