### ISSUE TITLE
Cannot find name 'object'.

### ISSUE THREAD

**Issue by nikhildhankani** [DefinitelyTyped/DefinitelyTyped#18724]
- [ x ] I tried using the `@types/highcharts:"^5.0.2"` package and had problems.

- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.1.15)
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] Authors: @hanssens, @damianog, @baltie, @AlbertOzimek

When I try to compile using webpack, I get the below error.

```
ERROR in [at-loader] ./node_modules/@types/highcharts/index.d.ts:6559:25
    TS2304: Cannot find name 'object'.
```

**Comment by hanssens** [comment]
@nikhildhankani This seems like an implementation, or configuration problem - specifically related to (your) webpack configuration.

Therefor, this is a question that is ideally suited for StackOverflow. I'd suggest posting it there, accompanied with a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). Meaning, include your config on StackOverflow and describe your setup thoroughly there, please.

**Comment by nikhildhankani** [comment]
Sure, will do that. Thanks and sorry to bother you here.

**Comment by audrummer15** [comment]
This is due to using a npm package of Typescript > 2.5. I ran into the same issue. A solution is to use Typescript < 2.5, or change the 'object' keyword with 'Object' in the typings file. Does anyone have suggestions on if changes should be made to this repository in regards to this change in the typescript keyword?

**Comment by Ponsivakumar** [comment]
I faced this issue when my typescript version is 2.1.5. It was all good when i upgraded it to 2.2.1.
