### ISSUE TITLE
[@types/express]Issue after upgraded to 4.17.10

### ISSUE THREAD

**Issue by Zeng83** [DefinitelyTyped/DefinitelyTyped#50543]
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/express@4.17.10` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: Authors: @addaleax, @Flarna, @ExE-Boss
We found the following error after we bumped up the version to @type/express@4.17.10
```
14:41:58 node_modules/@types/express/index.d.ts(103,15): error TS2707: Generic type 'ErrorRequestHandler' requires between 0 and 4 type arguments.
14:41:58 node_modules/@types/express/index.d.ts(118,15): error TS2707: Generic type 'Request<P, ResBody, ReqBody, ReqQuery>' requires between 0 and 4 type arguments.
14:41:58 node_modules/@types/express/index.d.ts(125,15): error TS2707: Generic type 'RequestHandler<P, ResBody, ReqBody, ReqQuery>' requires between 0 and 4 type arguments.
14:41:58 node_modules/@types/express/index.d.ts(128,40): error TS2344: Type 'Locals' does not satisfy the constraint 'number'.
14:41:58   Type 'Record<string, any>' is not assignable to type 'number'.
```

**Comment by Flarna** [comment]
the authors of express are: @borisyankov @CMUH @puneetar @dfrankland

**Comment by kiancross** [comment]
Also got this problem after upgrading to `4.17.10`. The issue was not present on `4.17.9`.

**Comment by vtrphan** [comment]
i got problems too

**Comment by davidLeonardi** [comment]
Fixed by downgrading. Please fix the latest version! :)

**Comment by rubiin** [comment]
4.17.9 does not seem to have this issue. I think the packages need proper testing before publish :(

**Comment by cherryblossom000** [comment]
I think this may be similar to #47339 in that the issue is due to an outdated `@types/express-serve-static-core`. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47339 for more info on why.

**Comment by kiancross** [comment]
I think this has been fixed in #50554. Use version `4.17.11`.

**Comment by theS1LV3R** [comment]
Just got the same issue on `4.17.11` of `express`, seems the [`package.json` file of `@types/express`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e89f7d98c073dfbdc26886d0975a8fb1539af60c/types/express/package.json) is asking for any compatible version of `@types/express-serve-static-core`, which makes it resolve to version `4.17.13`, which is broken. I think the suggested fix originally was to set it to `>=4.17.18`?

**Comment by kiancross** [comment]
> Just got the same issue on 4.17.11 of express

Should be `4.17.11` of `@types/express`, not `express`.

**Comment by theS1LV3R** [comment]
> > Just got the same issue on 4.17.11 of express
> 
> @theS1LV3R It should be `v4.17.11` of `@types/express`, not `express`.

Yeah my bad, wrote the wrong package. Meant `@types/express`

**Comment by kiancross** [comment]
@theS1LV3R That dependency issue was fixed in #50554 and released in `4.17.11`. Try reinstalling all dependencies.

**Comment by theS1LV3R** [comment]
> @theS1LV3R That dependency issue was fixed in #50554 and released in `4.17.11`. Try reinstalling all dependencies.

@kiancross that worked, thanks! Deleted `yarn.lock` and set `@types/express: "4.17.11"` in my `package.json` file, seems like everything works now.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
