### ISSUE TITLE
lodash: _.each on any type is broken

### ISSUE THREAD

**Issue by iccir** [DefinitelyTyped/DefinitelyTyped#6935]
After updating to the latest lodash.d.ts, I'm seeing several false positives related to `_.each`.  When the iteratee is an `any` type, the iterator parameter is now a `string` rather than an `any`.  

    var anyArray = [ ];
    
    _.each(anyArray, function(any1) {
        var any2 = any1.key;
    
        _.each(any2, function(any3) {
            // any3 should be an 'any', but has a 'string' type
            any3.foo; // Error: Property foo does not exist on type 'string' 
        })
    });
    
This may be a regression from b3833f8.

**Comment by iccir** [comment]
Upon further investigation: the behavior has changed, as `any3` in the above example is now a `string` type.  However, upon installing a previous version of lodash.d.ts, `any3` use to be a `{}` type.  It looks like we had some additional definitions to suppress these errors.

That said, I'm not sure what the correct behavior should be.  For comparison, vanilla TypeScript with `Array#forEach` compiles without error:

    var anyArray = [ ];
    
    anyArray.forEach(function(any1) {
        var any2 = any1.key;

        any2.forEach(function(any3) {
            any3.foo;  // This is fine, as any3 is the 'any' type
        })
    });

**Comment by chrootsu** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6962

**Comment by vvakame** [comment]
it merged.

**Comment by chrootsu** [comment]
@vvakame thanks mate! =)

**Comment by chrootsu** [comment]
@iccir please close the issue if the problem is gone

**Comment by iccir** [comment]
Looks good!  Thanks! :)
