### ISSUE TITLE
[@types/fhir] Circularly references

### ISSUE THREAD

**Issue by realtica** [DefinitelyTyped/DefinitelyTyped#71984]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71979

<div type='discussions-op-text'>

<sup>Originally posted by **realtica** February 18, 2025</sup>
Version:  "@types/fhir": "0.0.41"

`
ERROR in node_modules/@types/fhir/r2.d.ts(13301,13): error TS2456: Type alias 'FhirResource' circularly references itself.
node_modules/@types/fhir/r3.d.ts(20625,13): error TS2456: Type alias 'FhirResource' circularly references itself.
node_modules/@types/fhir/r4.d.ts(27964,13): error TS2456: Type alias 'FhirResource' circularly references itself.
node_modules/@types/fhir/r4b.d.ts(28601,13): error TS2456: Type alias 'FhirResource' circularly references itself.
node_modules/@types/fhir/r5.d.ts(36239,13): error TS2456: Type alias 'FhirResource' circularly references itself.
`</div>

**Comment by realtica** [comment]
This working well with version: "@types/fhir": "0.0.34" and below.

**Comment by Alirezamozafari1376** [comment]
I need help for my father's illness Address Volt Tonkeeper UQBHH6HhSfKXQUEDa6C05VrrQBL1gwaXVD_bkNHGgDgJ9TON

**Comment by mahmoodhamdi** [comment]
This is a genuine regression. The circular reference in `FhirResource` was introduced in v0.0.35. Looking at the type definition, the issue is that the union type alias references itself through nested resource types.

A fix would involve either:
1. Breaking the circularity by using an interface instead of a type alias for `FhirResource`
2. Restructuring the union to avoid the self-reference

Would be happy to look into a PR if this hasn't been addressed yet — can you confirm if you're still encountering this issue and which FHIR version (r2/r3/r4/r4b/r5) you're using?

**Comment by bkaney** [comment]
Closed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/75041
