### ISSUE TITLE
[@types/node] @types/node@22.8.5 and @types/node@20.17.4 break builds that do not target ECMAScript 2015 or higher

### ISSUE THREAD

**Issue by dreusel** [DefinitelyTyped/DefinitelyTyped#71050]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/71049

<div type='discussions-op-text'>

<sup>Originally posted by **dreusel** October 31, 2024</sup>
These versions, released 6 hours ago, break our builds with the following error:
```
node_modules/@types/node/events.d.ts:144:18 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

144         readonly #internalTypeOnlyBrand?: Events;
                     ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@types/node/events.d.ts:144
```
I suppose this should not happen with a patch release. The same project builds fine with @types/node@22.8.4 or @types/node@20.17.3

My tsconfig:
```
{
        "include": ["lib/*", "lib/**/*"],
        "compilerOptions": {
                "allowJs": true,
                "declaration": true,
                "emitDeclarationOnly": true,
                "outDir": "dist",
                "declarationMap": true,
                "skipLibCheck": true
        }
}
```

My build command:
`tsc --build && tsc dist/*.d.ts dist/**/*.d.ts`

(intended to build the type files, then check if the generated files are actually correct)</div>

**Comment by Wambosa** [comment]
Confirmed we ran into this issue this AM as well. Our package.json has `@types/node: ^18.16.4`.
We have version locked it to `@types/node: 18.16.4` and our builds are working again.

**Comment by joshuaconneely** [comment]
Appending this to your tsconfig.json `compilerOptions` will get rid of the error.

```
"target": "ES2015",             
"moduleResolution": "nodeNext", 
"module": "nodeNext" 
```

**Comment by eps1lon** [comment]
Fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71054
