### PR TITLE
Fix leaflet to compile with latest TypeScript v2.1.6.

### PR DESCRIPTION
**Pull request by anwalkers**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:

Not sure if this is correct or not. It does not pass the TypeScript compile because the type does not inherit from casting type.

`GeoJSONGeometryCollection` does not inherit from `GeoJSONFeature`

Error:

```
[18:28:15] Compiling TypeScript files using tsc version 2.1.6
[18:28:20] [tsc] > node_modules/@types/leaflet/index.d.ts(692,87): error TS2344: Type 'MultiPoint | GeometryCollection' does not satisfy the constraint 'GeometryObject'.
[18:28:20] [tsc] >   Type 'GeometryCollection' is not assignable to type 'GeometryObject'.
[18:28:20] [tsc] >     Property 'coordinates' is missing in type 'GeometryCollection'.
[18:28:20] [tsc] > node_modules/@types/leaflet/index.d.ts(746,83): error TS2344: Type 'MultiPoint | GeometryCollection' does not satisfy the constraint 'GeometryObject'.
[18:28:20] [tsc] >   Type 'GeometryCollection' is not assignable to type 'GeometryObject'.
[18:28:20] Failed to compile TypeScript: Error: tsc command has exited with code:2

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.
`

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by alejo90** [comment]
@atd-schubert can you please take a look at this?

**Comment by neolution** [comment]
@dt-bot This fixed my errors. Thank you!

**Comment by anwalkers** [comment]
@alejo90 @atd-schubert Any insights on this issue? Our CI builds are currently broken do to this issue.

**Comment by alejo90** [comment]
I really have no experience with geojson, so I don't know if the fix reflects what the library returns. Since @atd-schubert made the original change, I am hoping he can confirm whether this one is right or not. If we don't hear from him in the next twelve hours or so, I'll approve it.

**Comment by anwalkers** [comment]
@alejo90 Let's pull the trigger pull it in. If it breaks someone else because it isn't right they can fix it... ;)

**Comment by alejo90** [comment]
👍
