### ISSUE TITLE
[@types/copy-webpack-plugin] TS error with copy-webpack-plugin 6.0.1

### ISSUE THREAD

**Issue by hsimpson** [DefinitelyTyped/DefinitelyTyped#45008]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/copy-webpack-plugin` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @flying-sheep @avin-kavish

If you do not mention the authors the issue will be ignored.

New version of copy-webpack-plugin changed the constructor parameter to be an object with a patterns array property. When using the types then an TS error happens:
```
TSError: ⨯ Unable to compile TypeScript:
config/webpack.common.ts:92:7 - error TS2345: Argument of type '{ patterns: { from: string; to: string; }[]; }' is not assignable to parameter of type '(string | CopyPattern)[]'.
  Object literal may only specify known properties, and 'patterns' does not exist in type '(string | CopyPattern)[]'.

92       patterns: [
         ~~~~~~~~~~~
93         { from: 'src/app/index.html', to: '.' },
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
94         { from: 'glslangValidator', to: 'glslangValidator' },
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
95       ],
   ~~~~~~~
```

**Comment by peterblazejewicz** [comment]
@hsimpson 
please take a look #45012!

**Comment by hsimpson** [comment]
Confirmed, works with version 6.0.0 from npmjs 👍
