### ISSUE TITLE
[@types/react] 16.4.13 causing some HOCs to trigger error TS4023

### ISSUE THREAD

**Issue by MathieuDelafosse** [DefinitelyTyped/DefinitelyTyped#28558]
The following error appears when updated @types/react from 16.4.8 to 16.4.13 :  
`TS4023: Exported variable 'TopNavigation' has or is using name 'React.ComponentClass' from external module "/Users/xxxxx/Projects/xxxxx/node_modules/@types/react/index" but cannot be named.`
Around the following code : 
`156 const TopNavigation = translate('translations')(TopNavigationComponent);` which is i18n-next HOC.

A workaround is to import the module ComponentClass, but since it is unused in the current file, it causes unused-import lint error (which break builds).

Temporary reverted to 16.4.8 solved the issue. I don't really know what kind of further information you could need to fix that, feel free to ask.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
