### ISSUE TITLE
[@types/node]:  Namespace 'NodeJS' has no exported member 'Events'.

### ISSUE THREAD

**Issue by drav96** [DefinitelyTyped/DefinitelyTyped#39240]
- [ ] I tried using the `@types/node` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @borisyankov @theodorejb @davidparsson 

After updating @types/node to 12.11.1  i get following error

```
node_modules/nest-emitter/nest-emitter.module.d.ts:3:35 - error TS2694: Namespace 'NodeJS' has no exported member 'Events'.

declare type NestEmitter = NodeJS.Events;
```

**Comment by AviVahl** [comment]
It appears `nest-emitter` is testing itself with `@types/node@10`, which has that interface exported as an alias on the namespace. One possible way to fix this is to have `nest-emitter` use:
`type NestEmitter = typeof NodeJS.EventEmitter;`

This gives the same type with compat with both v10 and v12 of `@types/node`.

Another, maybe cleaner, way to achieve the same:
```
import {EventEmitter} from 'events';
interface NestEmitter extends EventEmitter {}
```
which is essentially how the "Events" interface is declared in `@types/node@10`.
