### ISSUE TITLE
Mocha's type definitions pollute and break other node modules 

### ISSUE THREAD

**Issue by falsandtru** [DefinitelyTyped/DefinitelyTyped#22510]
For example, it changes the return type of `setTimeout` and causes some errors.

```
node_modules/spica/throttle.ts(7,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/spica/throttle.ts(28,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

This is caused by #22112.

@aozgaa Can you revert that change?

**Comment by falsandtru** [comment]
This may be a bug of tsify.

**Comment by falsandtru** [comment]
@RyanCavanaugh Can you revert #24971? It is a regression bug.
