### PR TITLE
[react-redux] Fix #33690: improper import of `hoist-non-react-statics`

### LINKED ISSUE #33690: [@types/react-redux] 'hoist-non-react-statics' has no exported member 'NonReactStatics'
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.

@jamesreggio @JounQin

updating from `@types/react-redux 7.0.1` to `@types/react-redux 7.0.2` gives the following error:

```
'/node_modules/hoist-non-react-statics' has no exported member 'NonReactStatics'.

47 import { NonReactStatics } from 'hoist-non-react-statics';
```
seems like it was introduced here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/8b1beff944f6c7bf913b6fcee31fb5f7129064a7

### PR DESCRIPTION
**Pull request by jamesreggio**
**This PR fixes a regression in a popular package (`react-redux`). Please review and merge ASAP.**

---

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] ~Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>~ Unnecessary.
- [X] ~Increase the version number in the header if appropriate.~ Unnecessary.
- [X] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~ Unnecessary.

---

I regressed `react-redux` in 8b1beff94 by importing `hoist-non-react-statics` using the ES6 import syntax, when I should've used the TypeScript namespace/module import syntax.

This PR corrects the mistake, and should be an appropriate fix for #33690.

### CODE REVIEW

**Comment by jamesreggio** [comment]
@JounQin, can you review ASAP? This is blocking a lot of people on #33690.

**Review by surgeboris — APPROVED** [review]

**Comment by jamesreggio** [comment]
Please merge ASAP <3

**Comment by wolfy1339** [comment]
This still has a bug in it.
```
node_modules/@types/react-redux/index.d.ts:103:79 - error TS2694: Namespace '"node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
```

**Comment by jfbrazeau** [comment]
Same error for me with `7.0.4`.
```
$ tsc && babel --extensions ".ts,.tsx" -d ./lib ./src
../node_modules/@types/react-redux/index.d.ts:103:79 - error TS2694: Namespace '"<...path...>/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.

103 > = ComponentClass<JSX.LibraryManagedAttributes<C, P>> & hoistNonReactStatics.NonReactStatics<C> & {
                                                                                  ~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by weswigham** [comment]
@wolfy1339 @jfbrazeau try running `npm i @types/hoist-non-react-statics@latest` - it looks like you may have an out of date version which is missing the required type, and `npm` didn't update it with an update of `@types/react-redux` because the dependency relationship is versioned as `*`.

**Comment by wolfy1339** [comment]
If you require a certain version of that package, then why is it listed as `*`?

**Comment by weswigham** [comment]
Because, as I understand it, `react-redux` has nothing that would explicitly indicate an explicit dependence on an explicit version or version range right now.

**Comment by wolfy1339** [comment]
I fixed my problem by installing and adding an explicit dependency on `hoist-non-react-statics`.

**Comment by jamesreggio** [comment]
Please follow the issue thread over here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690#issuecomment-474043897

I've opened another PR with another attempted fix: #33979

**Comment by jfbrazeau** [comment]
> @wolfy1339 @jfbrazeau try running `npm i @types/hoist-non-react-statics@latest` - it looks like you may have an out of date version which is missing the required type, and `npm` didn't update it with an update of `@types/react-redux` because the dependency relationship is versioned as `*`.

@weswigham On the one hand, my `yarn.lock` file references https://registry.yarnpkg.com/@types/hoist-non-react-statics/-/hoist-non-react-statics-3.3.0.tgz#a59c0c995cc885bef1b8ec2241b114f9b35b517b which is the good version as far as I can see (am I wrong ?). And on the other hand I don't understand why I would have to explicitly declare this dependency in my module. It is true that I depend on react-redux, but why would I have to explicitly depend on react-redux dependencies ?

**Comment by weswigham** [comment]
> It is true that I depend on react-redux, but why would I have to explicitly depend on react-redux dependencies ?

You shouldn't have to, but what I'm saying is that the version previously installed by an older installation of `@types/react-redux` matches the dependency requirement (of `*`) but _actually_ might not be new enough to work - so if you've run an install in the past, _just_ updating `@types/react-redux` might not actually be enough. :(
