### PR TITLE
[connect] Add missing property originalUrl to req parameter

### PR DESCRIPTION
**Pull request by trygveaa**
This adds a new class IncomingMessage which extends from
http.IncomingMessage and adds the originalUrl property which was
previously missing. This new class is used for the req parameter in
HandleFunction.

The originalUrl property is added to req here:
https://github.com/senchalabs/connect/blob/3.4.0/index.js#L133

`originalUrl` is present in the version specified in these type definitions, so I didn't change the version.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/senchalabs/connect/blob/3.4.0/index.js#L133
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by EvanHahn — CHANGES_REQUESTED** [review]
Rejecting because I have a question:

Should we test that a request handler still works with `http.IncomingMessage`? For example, should we have a test like this?

```ts
app.use((req: http.IncomingMessage, res: http.ServerResponse) => {
  console.log(req, res);
  res.end();
});

**Comment by trygveaa** [comment]
@EvanHahn: Not sure if it's a question for me, or another maintainer. But sure, I can add that test if you want. I agree that it's a good idea.

**Comment by trygveaa** [comment]
@EvanHahn: I've added the test.

File: types/connect/index.d.ts [hunk 1]
```diff
@@ -18,11 +18,15 @@ declare function createServer(): createServer.Server;
 declare namespace createServer {
     export type ServerHandle = HandleFunction | http.Server;
 
+    export class IncomingMessage extends http.IncomingMessage {
+        originalUrl?: http.IncomingMessage["url"];
```
Comment (EvanHahn) [inline types/connect/index.d.ts]: I'm not a TypeScript expert. What does this line do?

**Review by EvanHahn — APPROVED** [review]

File: types/connect/index.d.ts (hunk 1 above)
Comment (trygveaa) [reply types/connect/index.d.ts]: `http.IncomingMessage["url"]` is a reference to the type of the `url` property in `http.IncomingMessage`, so it's setting the type of `originalUrl` to be the same as the type of `url`. It's called lookup types, [documented here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#keyof-and-lookup-types).

**Comment by orta** [comment]
Looks good and thanks for the test to verify existing code doesn't break 👍

File: types/connect/index.d.ts [hunk 2]
```diff
@@ -18,11 +18,15 @@ declare function createServer(): createServer.Server;
 declare namespace createServer {
     export type ServerHandle = HandleFunction | http.Server;
 
+    export class IncomingMessage extends http.IncomingMessage {
```
Comment (siraajahmed) [inline types/connect/index.d.ts]: This should be "implements" as http.IncomingMessage is an interface.

My code will no longer compile in typescript 3.7.2 because of this issue.

Full error is "node_modules/@types/connect/index.d.ts(21,42): error TS2689: Cannot extend an in
terface 'http.IncomingMessage'. Did you mean 'implements'?"

Please can we fix this ASAP.

Comment (trygveaa) [reply types/connect/index.d.ts]: According to [the types in this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L269), `http.IncomingMessage` is a class. Where are you getting your types from?

Comment (siraajahmed) [reply types/connect/index.d.ts]: Ah thanks for that. Turns out we were using an older version of node @types where the `http.IncomingMessage` was an interface. Thanks for your prompt response
