### ISSUE TITLE
 Module not found: Error: Can't resolve 'marked' in '/Users/vaibhavjain/Desktop/codebase/asp-frontend/node_modules/ngx-markdown/fesm2022'

### ISSUE THREAD

**Issue by vaibhavx07** [DefinitelyTyped/DefinitelyTyped#66082]
After updating from angular 14 to 15 I am getting this compilation error
 Module not found: Error: Can't resolve 'marked' in '/Users/vaibhavjain/Desktop/codebase/asp-frontend/node_modules/ngx-markdown/fesm2022'

**Comment by art-hck** [comment]
Did you fix it?
