### ISSUE TITLE
@types/mongoose-promise does not override mongoose's default promise lib

### ISSUE THREAD

**Issue by IOAyman** [DefinitelyTyped/DefinitelyTyped#10743]
- [x] I want to talk about `mongoose-promise/mongoose-promise.d.ts`.
  - The author of that type definition are cc/ @simonxca 

`@types/mongoose-promise` is not guaranteed to work with TypeScript 2.0.0 (cannot override `mongoose`'s default promises library. It has to be updated.
_Reported at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10193#issuecomment-241189905_

**Comment by simonxca** [comment]
Also reported in #9424

**Comment by simonxca** [comment]
Apparently Typescript 2 doesn't allow assigning properties on an imported module. So this:
```
import * as mongoose from 'mongoose';
mongoose.Promise = Promise;
```
leads to `error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.` To get your code to compile you will need to choose from one of the options below:
- `(<any>mongoose).Promise = Promise`
- `require('mongoose').Promise = Promise`
- `import mongoose = require('mongoose'); ... mongoose.Promise = Promise`

Note: Switching the Promise definitions does not work yet. I'm looking into that.

**Comment by pocesar** [comment]
a shot in the dark, would turn the custom MongoosePromise to a PromiseLike, any Promises/A+ can then work with it

**Comment by simonxca** [comment]
@IOAyman @pocesar I have an update here that uses global.Promise by default: https://github.com/simonxca/DefinitelyTyped/tree/patch-mongoose/mongoose

The definitions should work out of the box now unless you really want to use another promise library, then you'll have to do some manual steps.
You can take a look at the README and see if the promises make sense. There's a lot of changes though and I'll be away next week so I'm not sure if I want to deliver it before I come back.
