### PR TITLE
[lodash] change weakmap declaration to work with TS 2.2

### LINKED ISSUE #14324: Lodash All declarations of 'WeakMap' must have identical type parameters.
- [x] I tried using the `@types/lodash` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

I found this problem compiling a project using Typescript version 2.2.0-dev.20170128 and @types/lodash version 4.14.51. In my case the tsconfig use es6 target. The error message is:

`node_modules/@types/lodash/index.d.ts(19421,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
`
If I browse the file to the line indicated in the error message I can see the following comment:

`// Backward compatibility with --target es5`

Maybe this is the cause of the issue?
Best regards to all

### PR DESCRIPTION
**Pull request by budiadiono**
In TS 2.2 `WeakMap` interface for ES6 has been changed from `WeakMap<K, V>` to `WeakMap<K extends object, V>`. This changes makes `@types/lodash` not working with new ES6 introduced in TS2.2.

To keep the backward compatibility with ES5, I think it is safe to rename the `WeakMap` declaration.

I know TS 2.2 is still in RC version now, but many people using it, including me :). So if you think this is too early and also bad idea then feel free to close this PR without merging it.

If this get merged then it's should close #14324.

### CODE REVIEW

**Comment by kerbyfc** [comment]
Please, verify it %)

**Comment by eschwartz** [comment]
What do you think about `WeakMapLike` instead of `WeakMapES5`?

I'm just thinking about how custom `Promise` libraries used to talk about "promise-like" objects, that conformed to the Promise/A+ spec, but were not actual native `Promise` objects.

**Comment by budiadiono** [comment]
`WeakMapLike` is sounds good. @bczengel, @chrootsu, @stepancar what do you think?

**Comment by kerbyfc** [comment]
I can't use lodash without this fix...

**Comment by joewood** [comment]
Any ETA on getting this merged?

**Comment by budiadiono** [comment]
This pull request is dirty since contains another junk commits. I've made another one in pull request #14662. I also follow @eschwartz suggestion to use `WeakMapLike` instead of `WeakMapES5`.
