### ISSUE TITLE
[@types/next-auth] callbacks.session signature is incompatible with usage

### ISSUE THREAD

**Issue by Naddiseo** [DefinitelyTyped/DefinitelyTyped#52104]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @euxn23

This seems to be a regression introduced by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51493

Minimal reproduction:
```typescript
import NextAuth from "next-auth";

export default NextAuth({
  callbacks: {
    async session(session, token) {
      session.user.email = token.email; // this line causes the return to be Record<string,unknown>
      return session;
    },
  }
});

```

Typecheck output:
```
pages/api/v1/auth/[...nextauth].ts:55:11 - error TS2322: Type '(session: Session, token: JWT | User) => Promise<Session>' is not assignable to type '(session: Session, userOrToken: JWT | User) => Promise<WithAdditionalParams<Session>>'.
  Type 'Promise<Session>' is not assignable to type 'Promise<WithAdditionalParams<Session>>'.
    Type 'Session' is not assignable to type 'WithAdditionalParams<Session>'.
      Type 'Session' is not assignable to type 'Record<string, unknown>'.
        Index signature is missing in type 'Session'.

55     async session(session, token) {
             ~~~~~~~


```
