### ISSUE TITLE
Typings for knex not usable on @next

### ISSUE THREAD

**Issue by RWOverdijk** [DefinitelyTyped/DefinitelyTyped#10853]
Using `typescript@next`, I do a simple `npm i --save @types/knex`, then add `private query: Knex.QueryBuilder;` to my class. Webstorm then hits me up with something beautiful like this: `Knex ( "knex" )? (multiple choices...) ⌥⏎`.

This is working properly for other typings (such as chai).

I did tell webstorm to use `typescript@next`, I also tried it in vscode (which has also been configured to use `@next`).

In visual studio code it's even more fun. I even added the ref (but it didn't function without it either, same message).

![screenshot 2016-08-27 00 06 36](https://cloud.githubusercontent.com/assets/781745/18022765/f13d3592-6bf1-11e6-99ff-1d2832fbf403.png)

Is there any way I can use this? What am I doing wrong? Or is it just broken?

**Comment by ty10r** [comment]
Have there been any updates here?
I'm finding that when I import knex, my typescript compiler is only considering the first declared function as the type.

```ts
import * as Knex from 'knex';

interface SomeInterface extends Knex.QueryInterface {...}
```

Or any use of knex's interfaces results in something like:

`error TS2339: Property 'QueryInterface' does not exist on type '(config: Config) => Knex'.`

**Comment by goenning** [comment]
Not sure if something changed since then, but I just tried knex + ts@2 and it worked flawlessly.

**Comment by calebeaires** [comment]
👍  Same here!

**Comment by mhegazy** [comment]
seems working in `@types/knex@0.0.39`

**Comment by taybin** [comment]
This can be closed as knex provides its own definitions now.
