### ISSUE TITLE
@types/node fails to find typescript v4.4.2 declarations 

### ISSUE THREAD

**Issue by mondo192** [DefinitelyTyped/DefinitelyTyped#55448]
When creating a new yarn project with typescript v4.4.2 and adding @types/node to package.json. Typescript fails to find the types even though they appear to be installed. Im running vs code as my text editor and yarn berry. I wonder if this is an issue with @types/node or typescript itself. If works with typescript v4.3.5 but I get this import bug with typescript v4.4.2

```
Cannot find module 'http' or its corresponding type declarations.ts(2307)
```

Also intellisense does not work.

Node: v14.17.5
Yarn: 3.0.1
VSCode: 1.59.1 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa x64
npm: 7.21.1

```
{
  "name": "recipe-api",
  "packageManager": "yarn@3.0.1",
  "private": true,
  "devDependencies": {
    "@types/node": "^16.7.4",
    "typescript": "^4.4.2"
  },
  "dependencies": {
    "fastify": "^3.20.2"
  }
}
```

_Originally posted by @mondo192 in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55447_
