### ISSUE TITLE
@types/bluebird .props(Map) does not work in TS 2.4

### ISSUE THREAD

**Issue by fengb** [DefinitelyTyped/DefinitelyTyped#17925]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @lhecker @fengb (lol thats me)

I recently installed TS 2.4 and noticed this package's test stopped working:
```
bluebird-tests.ts(592,75): error TS2322: Type 'Map<number, Bluebird<string>>' is not assignable to type 'Map<number, string>'.
bluebird-tests.ts(592,75): error TS2322: Type 'Map<number, Bluebird<string>>' is not assignable to type 'Map<number, string>'.
  Type 'Bluebird<string>' is not assignable to type 'string'.
```

I can't tell if this is due to the implementation misusing a quirk or a regression of the latest compiler. According to how I'm interpreting the type definition:
* passing in `.props(Map<number, Bluebird<string>>)`
* should match `.props(Map<number, PromiseLike<string>>)`
* and return `Promise<Map<number, string>>`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
