### PR TITLE
[@types/node] Add AsyncIterableIterator.next() method.

### PR DESCRIPTION
**Pull request by Hirevo**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR fixes the following TypeScript issue I encountered with async iterators by using them in for-await-of loops:
```
error TS2519: An async iterator must have a 'next()' method.
```

This is the smallest sample code I could do that triggers the error:
```typescript
import { createReadStream } from "fs";

(async () => {
    const readable = createReadStream("./some_file.txt");
    
    for await (const chunk of readable) {
        // ...
    }
})();
```

The test suite didn't passed because of an issue with redux-form/v4.  
This is being adressed in PR #27212.

### CODE REVIEW

**Comment by Flarna** [comment]
test fail should be fixed by #27212

**Review by Flarna — APPROVED** [review]

**Review by a-tarasyuk — APPROVED** [review]

**Review by BrunoScheufler — APPROVED** [review]

**Comment by andy-ms** [comment]
The empty interface is just a forward-declaration -- the rest of the type should be defined later. You might want to check your `--lib` setting.
We might also consider adding `/// <reference lib` directives to `@types/node`. (CC @rbuckton)

**Comment by Hirevo** [comment]
Correct, adding `"esnext"` or `"esnext.asynciterable"` to TypeScript compiler's "lib" options removes this error.  
Previously, I just had `"es2015"`.  
In fact, async iterators are still a stage 3 proposal, so it makes perfect sense.  
This solution didn't cross my mind.  
I am sorry for the PR then, and I think it can be closed.

**Comment by Hirevo** [comment]
Correct, adding `"esnext"` or `"esnext.asynciterable"` to TypeScript compiler's "lib" options removes this error.  
Previously, I just had `"es2015"`.  
In fact, async iterators are still a stage 3 proposal, so it makes perfect sense.  
This solution didn't cross my mind.  
I am sorry for the PR then, and I think it can be closed.

**Comment by rbuckton** [comment]
Unfortunately, `<reference lib="">` was only just recently added to TypeScript. If we were to use it in NodeJS right now we'd have to update the minimum TypeScript version for over 1,500 packages that depend on NodeJS.
