### ISSUE TITLE
Regression in express-serve-static-core for request RouteParameters type

### ISSUE THREAD

**Issue by timmywil** [DefinitelyTyped/DefinitelyTyped#53584]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick, @DetachHead, @borisyankov, @19majkel94, @kacepe, @micksatana, @samijaber, @JoseLion, @dwrss, @andoshin11

I'm getting a type error in an express middleware package where the type for the Request object no longer works for the middleware's users.

The middleware types:

```ts
import type { Request, Response } from 'express'
// ...
  return function (req: Request, res: Response) {
// ...etc.
```

This particular middleware doesn't call the next function, but I also tried the following and got the same error:

```ts
import type { RequestHandler } from 'express'
// ...
export function createMiddleware(): RequestHandler {
  return function(req, res, next) {
// ...
```

The following code from a user will result in a type error:

```ts
const app = express()

app.use('/route', middleware())
```

The error:

```
Argument of type 'Request<RouteParameters<"/route">, any, any, ParsedQs, Record<string, any>>' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
  The types of 'app.get' are incompatible between these types.
    Type '((name: string) => any) & import("@types/express-serve-static-core/index").IRouterMatcher<import("@types/express-serve-static-core/index").Application, any>' is not assignable to type '((name: string) => any) & import("@types/express-serve-static-core/index").IRouterMatcher<import("@types/express-serve-static-core/index").Application, any>'.
      Type '((name: string) => any) & IRouterMatcher<Application, any>' is not assignable to type 'IRouterMatcher<Application, any>'.
        Types of parameters 'name' and 'path' are incompatible.
          Type 'PathParams' is not assignable to type 'string'.
            Type 'RegExp' is not assignable to type 'string'.ts(2345)
```

RouteParameters and ParamsDictionary seem to differ in that one takes a RegExp and the other does not. I would prefer to keep the types simple in the middleware and continue using main types exported by express rather than changing to RouteParameters.

RouteParamaters was changed recently in [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/95a309dcd7dc2632b4ebab87a75329f17af62dbc).

I don't fully understand the type definitions here or I'd offer to make a PR. I *think* it's a matter of aligning route parameters with path parameters, but I know they have different purposes. However, it seems like those purposes aren't always properly separated. Thanks.

**Comment by timmywil** [comment]
I just noticed that @types/node was updated in `@types/express-serve-static-core`. Strangely, this error goes away if I revert @types/node to 15.6.2. I'm not sure why yet.

**Comment by SimonSchick** [comment]
I wonder if this is related to the fact that I added https://github.com/DefinitelyTyped/DefinitelyTyped/commit/c886d9bf6be8a64bf7cde242779f8931b9ae329e#diff-50ed3ba474b514ee7443ee72b00abc59b143f94f70bb8a0a83c3293ec21f4540R159 in accordance with the node changelog.

**Comment by DetachHead** [comment]
i can't seem to reproduce this. could you please provide a full example as i feel there's something i'm missing from the code snippets provided.

if i were to guess, i'd say your `middleware` function is expecting a request with a `params` object of type `{[key: string]: string}` but `app.use('/route')` produces one of type `{}` since there are no query parameters. you should be able to just go `app.use('/route' as string, middleware())` to turn off this check

**Comment by mlegenhausen** [comment]
Same Problem

Type Versions:
* `@types/node@15.9.0` seems to be the breaking version. Reverting back to `@15.6.2` solves the problem as described.
* `@types/express@^4.17.12`
* `@types/body-parser@^1.19.0`

I have the problem when using the `bodyparser` as middleware.

```ts
import { json } from 'bodyparser'
import * as EX from './express'

const app = EX()
app.use(json())
```

**Comment by Sunny-fr** [comment]
I had the same issue using apollo-server-express since the latest release.


```
node_modules/apollo-server-express/node_modules/@types/express-serve-static-core/index.d.ts(589,18): error TS2430: Interface 'Response<ResBody, Locals, StatusCode>' incorrectly extends interface 'ServerResponse'.
  Types of property 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> | undefined' is not assignable to type 'IncomingMessage'.
      Type 'undefined' is not assignable to type 'IncomingMessage'.
node_modules/apollo-server-express/node_modules/@types/express/index.d.ts(58,55): error TS2344: Type 'Response<any, Record<string, any>>' does not satisfy the constraint 'ServerResponse'.
  Types of property 'req' are incompatible.
    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> | undefined' is not assignable to type 'IncomingMessage'.
      Type 'undefined' is not assignable to type 'IncomingMessage'.
```

I've added @types/node@15.6.2 to my dev dependencies, solved it.
Thanks @mlegenhausen  :)

> Same Problem
> 
> Type Versions:
> 
> * `@types/node@15.9.0` seems to be the breaking version. Reverting back to `@15.6.2` solves the problem as described.
> * `@types/express@^4.17.12`
> * `@types/body-parser@^1.19.0`
> 
> I have the problem when using the `bodyparser` as middleware.
> 
> ```ts
> import { json } from 'bodyparser'
> import * as express from 'express'
> 
> const app = express()
> app.use(json()) // Type Error
> ```

**Comment by Mulando** [comment]
Same issue here, after updating from @types/node@15.9.0 to 15.12.0

error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type 'NextHandleFunction' is not assignable to parameter of type 'PathParams'.
          Type 'NextHandleFunction' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 27 more.

    56         this._app.use(express.json()); // parses body req.body to object
                             ~~~~~~~~~~~~~~

      node_modules/@types/express-serve-static-core/index.d.ts:151:5

**Comment by SimonSchick** [comment]
Can one of you please provide a self contained repro?

**Comment by mrjackwills** [comment]
I have had this exact issue, ```app.use(json())```, or ```app.use(cors())```, creating the overload error

Removing node_modules and package-lock.json, and then reinstalling via npm install, and now all the overload issues have disappeared

**Comment by timmywil** [comment]
I put together a codesandbox for this https://codesandbox.io/s/eager-glade-rlp17?file=/src/index.ts

**Comment by timmywil** [comment]
Wait, I messed up something. I'll see if I can fix it and just edit the comment.

**Comment by timmywil** [comment]
After further investigation, I think this issue is a matter of making sure all of your sub-dependencies are updated. I cannot reproduce if everything is up-to-date, but I did have to brute force the updates with `rm -rf node_modules/ package-lock.json && npm install`. I had done that for my example app within my library, but not for the library itself. Once I did it for both, the type error went away.

I don't think there's anything to be done in the types, but hopefully this issue will be helpful for those that hit the error and don't know they need to blow away their lock files.

**Comment by SimonSchick** [comment]
I downloaded the repro and am not getting any errors after changing it to-

Oh well you closed it 😛

**Comment by Sunny-fr** [comment]
> After further investigation, I think this issue is a matter of making sure all of your sub-dependencies are updated. I cannot reproduce if everything is up-to-date, but I did have to brute force the updates with `rm -rf node_modules/ package-lock.json && npm install`. I had done that for my example app within my library, but not for the library itself. Once I did it for both, the type error went away.
> 
> I don't think there's anything to be done in the types, but hopefully this issue will be helpful for those that hit the error and don't know they need to blow away their lock files.

Hey there !
Just to mention I was using npx and @types/node wasn't listed in my depencies.
At first of course I tried using the good old fashioned removing node_modules and package-lock.json but It didn't workout (my initial error came from Jenkins witch rebuild every time from scratch).
So in order to make it work I had to add to my package.json this dependency : `@types/node@15.6.2`.

Anyway thank you, I just wanted to point out this maybe it can help someone (because a I've had a hard time to figure it out😂)

**Comment by yurtaev** [comment]
Workaround to fix apollo-server-express `"@types/express-serve-static-core": 4.17.19`:

```json5
// package.json
{
  "resolutions": {
    // You can remove `resolutions` after upgrade the lock file.
    "@types/express-serve-static-core": "*"
  }
}
```

**Comment by mlegenhausen** [comment]
Thanks for the hint. Removing `@types/express-serve-static-core` from the `yarn.lock` and running `yarn` again updated the dependency to the latest version which fixed the problem.

**Comment by glasser** [comment]
Apollo Server maintainer here. We have continuous problems where there are changes to `@types/express` that require you to update `@types/express-serve-static-core` but the dependencies don't properly do it for you, and people can't build their projects and they report the bug to us.

This PR looks like a good idea but it seems like this versioned dependency should be updated much more often? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50554
