### PR TITLE
[WIP] start support for tsc 1.5.0-beta

### PR DESCRIPTION
**Pull request by vvakame**
only support --target es6? or support es5 and es6 both?

### CODE REVIEW

**Comment by vvakame** [comment]
Well... how to fix?

**Comment by basarat** [comment]
If an external module (in this case `"acl"`) is split across multiple files you can only use stuff that has been exported.

**Comment by basarat** [comment]
Sorry. I've made it worse :) Investigating

**Comment by basarat** [comment]
I've provided the TS team with a sample : https://github.com/Microsoft/TypeScript/issues/2784

**Comment by basarat** [comment]
The reason why I thought I had a fix was that the files compile fine in isolation under different cases

**Comment by basarat** [comment]
So the fix recommended by the TS team (https://github.com/Microsoft/TypeScript/issues/2784#issuecomment-93778204) is to use a ghost module. I'm thinking of calling it `AclTypes` :+1:

**Comment by basarat** [comment]
So can't declare inside `"foo"` if it has an `export =` as only a single thing can have an `export` if we use `export =`. And if I move to `AclTypes` then I can't use `import http = require("http")` 

So now I need to move stuff from `"http"` out into the ghost `NodeJS` module. Sorry.

**Comment by basarat** [comment]
@vvakame are you okay with me completely opening up `node.d.ts`. Ofcourse it will be a lot of work and I might stumble on more refactoring needed in the process.

**Comment by vvakame** [comment]
@basarat wow, thank you basarat! it is big incident...

**Comment by vvakame** [comment]
```
----------------- For file:react/legacy/react-0.12-tests.ts
react/legacy/react-0.12.d.ts(927,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

Hmm?

**Comment by basarat** [comment]
> Hmm?

saw the same thing : https://github.com/Microsoft/TypeScript/issues/2784#issuecomment-93652430

In this reduced example : https://github.com/Microsoft/TypeScript/issues/2784#issue-68812863

Basically there is an *implicit* export of `Foo` if its used in `b.d.ts` below: 

`a.d.ts` (which compiles fine in isolation) without any error:

```ts
declare module "foo" {
    interface Foo {
        a: number;
    }
    var _:Foo;
    export = _;
}
```

And `b.d.ts` that plans to add stuff to module `foo`'s `Foo` interface: 
```ts
/// <reference path="./a"/>

declare module "foo" {
    interface Foo {
        b: number;
    }
}
```

**Comment by vvakame** [comment]
@basarat It seems to do not reopen external module in `react/legacy/react-0.12-tests.ts` and `react/legacy/react-0.12.d.ts`. isn't it?

**Comment by basarat** [comment]
> isn't it?

This is effectively what you did to fix `acl` as well

**Comment by vvakame** [comment]
@basarat umm.. sorry, I am not understand yet... can you make a commit?

**Comment by basarat** [comment]
> can you make a commit?

Here is a sample: 

demo

> It seems to do not reopen external module 

Yes. Exactly.

**Comment by basarat** [comment]
Note I do not see this error in our case locally : 

image

But I am on typescript master so perhaps worth pointing typescript to : https://github.com/Arnavion/typescript-github/releases/tag/2015-04-26-218e1012a2e671ca70be3c1b9edf0db092e4c5c2 Details : https://github.com/Arnavion/typescript-github#install

**Comment by vvakame** [comment]
```
$ git rev-parse master # in TypeScript repo
f988a11cfcb5503d575260563ffb7ea66549d6ad
$ node ~/work/TypeScript/bin/tsc.js --noImplicitAny --module commonjs --target es5 react/legacy/react-0.12-tests.ts
react/legacy/react-0.12.d.ts(927,5): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

current master/HEAD's LKG can not compile react/legacy/react-0.12-tests.ts.
and I tried `218e1012a2e671ca70be3c1b9edf0db092e4c5c2`'s LKG. but i cant get exit code 0 :crying_cat_face:

**Comment by vvakame** [comment]
wow...!!

**Comment by basarat** [comment]
> wow...!!

eek. This is related to changes in lib.d.ts.

About : `node.d.ts` : this is sortable : https://github.com/Microsoft/TypeScript/issues/2953#issuecomment-98040346 The same errors will appear in *all* node packages

About `webaudio` and other *cutting edge stuff* I feel like recommending that it be compiled with `--nolib` reason is the current limbo that `lib.d.ts` has gone into. Alternatively it can be compiled with `target es6` and then anything that is duplicated should be removed from these definitions

**Comment by vvakame** [comment]
NOTE 
https://github.com/borisyankov/DefinitelyTyped/pull/4193
https://github.com/borisyankov/DefinitelyTyped/pull/4245
https://github.com/Microsoft/TypeScript/issues/2929

**Comment by vvakame** [comment]
do you means lib.d.ts and lib.es6.d.ts into https://github.com/borisyankov/DefinitelyTyped/tree/master/typescript and reference it from these definition files?

**Comment by basarat** [comment]
> do you means lib.d.ts and lib.es6.d.ts into https://github.com/borisyankov/DefinitelyTyped/tree/master/typescript and reference it from these definition files?

No. Just compile with `target --es6`. And if there are any `duplicate definition` errors, delete the one in these definition files (i.e. prefer es6.lib.d.ts)

**Comment by jt000** [comment]
@basarat - Just curious: what did you use to make those gifs?

**Comment by basarat** [comment]
@jt000 https://screentogif.codeplex.com/

**Comment by vvakame** [comment]
NOTE https://github.com/Microsoft/TypeScript/issues/3005

**Comment by vvakame** [comment]
NOTE https://github.com/Microsoft/TypeScript/issues/2953

**Comment by vvakame** [comment]
ready to merge! 7/20 is release day of VisualStudio 2015.

**Comment by vvakame** [comment]
I think we need test bed of es6 target.
my proposal. test with `--target es6` option if definition has `*-tests.es6.ts` postfix.

@basarat @horiuchi what do you think?

**Comment by basarat** [comment]
>  test with --target es6 option if definition has *-tests.es6.ts postfix

:+1: from me

BTW thanks for all the hard work on this update :100:

**Comment by vvakame** [comment]
:sparkles: :smiley_cat: :sparkles:

**Comment by vvakame** [comment]
TypeScript 1.5.3 released!

**Comment by vvakame** [comment]
oops. I I forgot update package.json...
