### ISSUE TITLE
Getting AbortSignal error on compilation for version 16.6.2

### ISSUE THREAD

**Issue by shahabali1993** [DefinitelyTyped/DefinitelyTyped#66617]
PS: I can't upgrade the @types/node version to latest if someone is going to suggest that as I am using scramjet library and it currently works with the version 16.6.2 of @types/node.

Current **node version**: 18.17.1 and **@types/node version**: 16.6.2

$ yarn compile
yarn run v1.22.19
$ tsc
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  ../../../Users/ShahabAli/AppData/Local/Yarn/Data/global/node_modules/typescript/lib/lib.dom.d.ts:2090:13
    2090 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.

Found 1 error in node_modules/@types/node/globals.d.ts:72

**Comment by shahabali1993** [comment]
I was able to fix this issue by updating the AbortSignal interface in globals.d.ts in node_modules for now

**From**
`declare var AbortSignal: {
    prototype: AbortSignal;
    new(): AbortSignal;
};`

**To**
`declare var AbortSignal: { 
    new (): AbortSignal; 
    prototype: AbortSignal; 
    abort(reason?: any): AbortSignal; 
    timeout(milliseconds: number): AbortSignal; 
};`

**Comment by shahabali1993** [comment]
@pilagod

**Comment by shahabali1993** [comment]
@peterblazejewicz @Methuselah96 @nikcorg @pilagod can you please look into it?

Or if this works for you I can be given access as a moderator so I can create a pull-request which you can verify and then merge into master.

**Comment by thiagodevbrz** [comment]
I was getting this error when trying to build the project on a AWS Lambda using node v16.16.0 and i fixed it updating all dependencies using "yarn upgrade --latest", @types/nodes now is using 20.6.2.
