### PR TITLE
Put current version of node in the root

### PR DESCRIPTION
**Pull request by sandersn**
Previously, the code that supports the oldest version of Typescript was in the root: 3.1 and below. Newer versions were is ts*/ subdirectories.

This PR puts the newest version in the root, and older versions -- usually 3.7 and below -- in ts*/ subdirectories. This is possible because all supported versions of the Typescript now understand the typesVersions property in package.json.

This PR needs a new version of DefinitelyTyped-tools and dtslint, which I will ship soon. It also needs to be brought up to date with master.

### CODE REVIEW

**Comment by yiziz** [comment]
@sandersn i believe this change will cause a `error TS1084: Invalid 'reference' directive syntax.` on line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v8/index.d.ts#L35 if you have a combination of `"@types/node": "^8.0.9"` and `"typescript": "^2.4"`

**Comment by clennam** [comment]
> @sandersn i believe this change will cause a `error TS1084: Invalid 'reference' directive syntax.` on line: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v8/index.d.ts#L35 if you have a combination of `"@types/node": "^8.0.9"` and `"typescript": "^2.4"`

Experiencing the same ```error TS1084: Invalid 'reference' directive syntax.``` error using `"@types/node": "^8.10.48"` and `"typescript": "~2.9.2"`. Attempted to rebuild using specific version `"8.10.48"` and had no issues.

**Comment by cscleison** [comment]
hey @sandersn I'm having a weird side effect. Because a lot of libs do a `/// <reference types="node" />` and node itself do a `/// <reference lib="es2018" />`... my codebase stopped complaining about ES features higher than my `target` configuration. More details here https://github.com/microsoft/TypeScript/issues/40388

Who is in the wrong here? I suppose the libs should not be referencing node directly, but _there's a lot of them_...

**Comment by richmwatts** [comment]
It would appear that this change has somehow broken a lot of peoples builds, mine included.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47250

I do not know how and it would be good to get an explanation.

**Comment by G-Rath** [comment]
@richmwatts as I said on my comment [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47250#issuecomment-686938721), you need to update to TypeScript 3.2 or higher to use the latest version of `@types/node`.

If you cannot upgrade, you'll have to pin your node dependency to the last stable version.

**Comment by richmwatts** [comment]
@G-Rath OK but does this explain why using version 6.x.x of @types also stopped my build from working?

**Comment by G-Rath** [comment]
@richmwatts if you updated `@types/node` then yes it does - I'm not sure why @typescript-bot didn't put a message saying it published, but [it did publish a new version 6 days ago that moved the TypeScript version to 3.2](https://app.renovatebot.com/package-diff?name=@types/node&from=6.14.10&to=6.14.11).

**Comment by sandersn** [comment]
@yziz @clennam @richmwatts
Definitely Typed only tests on 3.1 and above now, so 3.1 features may be added at any time. Legacy projects should pin all their dependencies and only update on purpose.
