### PR TITLE
[jquery] Fix regression with assignability of jQuery Promises to Promise.

### LINKED ISSUE #28768: Regression: JQueryPromise is not assignable to Promise
- [x] I tried using the `@types/jquery` package and had problems.
- [ ] ~~I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript~~
I am using TypeScript 2.9.2 and cannot upgrade because Angular does not support TS 3 yet.
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

@types/jquery 3.3.3 has a regression. 3.3.2 did not have this problem.

With 3.3.3 and later, this code:

```typescript
	setValueToDefault (): Promise<void> {
		if (this._defaultValue === undefined) {
			return this.WebService.getDefaultValue(this.entityType).done(value => {
				if (this._defaultValue === undefined) {
					this._defaultValue = value;
				}
				if (this.value === undefined) {
					this.changeValue($.extend({}, this._defaultValue));
				}
			});
		} else {
			this.changeValue($.extend({}, this._defaultValue));
			return Promise.resolve();
		}
	}
```

Results in this error:

```
ERROR in src/main/frontend/components/entityReferenceAutocomplete.component.ts(73,4): error TS2322: Type 'JQueryPromise<EntityReference>' is not assignable to type 'Promise<void>'.
  Property '[Symbol.toStringTag]' is missing in type 'JQueryPromise<EntityReference>'.
```

In the above code, this.WebService.getDefaultValue() returns a JQueryPromise<EntityReference>.

Since the regression appears in 3.3.3, the culprit is most likely #26420.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

---

jQuery Promises should be assignable to the global `Promise` interface. A regression of this behavior was introduced by #26420.

Fixes #28768

### CODE REVIEW

**Comment by leonard-thieu** [comment]
Failures are unrelated (all already fail on `master`).

**Comment by jgasiorowski** [comment]
@leonard-thieu Is that expected behaviour that on v3.3.8 I get `Cannot find name 'Symbol'` error? I am using es5. Is that required to move on es6 with this version?

**Comment by leonard-thieu** [comment]
> @leonard-thieu Is that expected behaviour that on v3.3.8 I get `Cannot find name 'Symbol'` error? I am using es5. Is that required to move on es6 with this version?

No. This will be fixed by #28975. Thanks for reporting this!
