### ISSUE TITLE
[react] Impossible to update different state properties depending on some condition

### ISSUE THREAD

**Issue by stas-vilchik** [DefinitelyTyped/DefinitelyTyped#25603]
`@types/react@16.3.13`
`typescript@2.8.3`

It seems impossible to update different `state` properties depending on some condition, i.e. this code snippet:

```typescript
handleNameChange = (name: string) => {
  this.setState(
    state =>
      state.keyModifiedByUser
        ? { name }
        : { name, key: latinize(name).replace(/[^A-Za-z0-9]/g, '_') }
  );
};
```

produces an error:

```
my/react/component.tsx(136,7): error TS2345: Argument of type '(state: Readonly<State>) => { name: string; key?: undefined; } | { name: string; key: string; }' is not assignable to parameter of type 'State | ((prevState: Readonly<State>, props: Props) => State | Pick<State, "name" | "key"> | null...'.
  Type '(state: Readonly<State>) => { name: string; key?: undefined; } | { name: string; key: string; }' is not assignable to type 'Pick<State, "name" | "key">'.
    Property 'key' is missing in type '(state: Readonly<State>) => { name: string; key?: undefined; } | { name: string; key: string; }'.
```

My state is defined as

```typescript
interface State {
  key: string;
  keyModifiedByUser: boolean;
  name: string;
}
```

Please note that the code above worked correctly with `@types/react@16.0.29` which I was using before.

Authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @theruther4d @guilhermehubner @ferdaber @jrakotoharisoa

**Comment by ferdaber** [comment]
This is a known issue ever since the return type of `setState` was changed from `Partial` to `Pick`, see here for the discussion of the rationale behind the change:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365

The same report of your issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365#issuecomment-351868649

The workaround for your issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365#issuecomment-351884578

**Comment by ferdaber** [comment]
Note that the issue is because of how the compiler treats multiple returns as unions and how it affects the `Pick` inference algorithm.

**Comment by stas-vilchik** [comment]
Thanks, @ferdaber
