### ISSUE TITLE
[@types/mousetrap] Property 'bindGlobal' does not exist on type 'MousetrapStatic' after update to 1.6.7

### ISSUE THREAD

**Issue by doberkofler** [DefinitelyTyped/DefinitelyTyped#52437]
After upgrading `@types/mousetrap` from 1.6.6 to 1.6.7 the types for the global binding are no longer available.

- [x] I tried using the `@types/mousetrap` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @peterblazejewicz

**Comment by peterblazejewicz** [comment]
there was a change to remove direct binding to 3rd party addons. They are still there with definition,
but not imported by default, so for example for CommonJS:
```ts
import Mousetrap = require('mousetrap');
// known extensions shipped with DT package
import 'mousetrap/extensions/pause';
import 'mousetrap/extensions/global';
```
for for inline (global) usage (this one can be also done by adding types in tsconfig:
```ts
/// <reference types="mousetrap" />
/// <reference types="mousetrap/extensions/pause" />
/// <reference types="mousetrap/extensions/global" />
...
```
HTH!

**Comment by doberkofler** [comment]
I'm not sure I understand why the `mousetrap-global-bind` type definitions have been removed?

Until now I've just imported the modules as follows:

```typescript
import Mousetrap from 'mousetrap';
import 'mousetrap/plugins/global-bind/mousetrap-global-bind';
```

and now I have to import like this:

```typescript
/// <reference types="mousetrap/extensions/global" />
import Mousetrap from 'mousetrap';
import 'mousetrap/plugins/global-bind/mousetrap-global-bind';
```
