### ISSUE TITLE
[@types/react-native] Cant assign ColorValue from object

### ISSUE THREAD

**Issue by danilobuerger** [DefinitelyTyped/DefinitelyTyped#46864]
`ColorValue` was introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963
```
declare const OpaqueColorValue: unique symbol;
type OpaqueColorValue = typeof OpaqueColorValue;

export type ColorValue = string | OpaqueColorValue;
```

However, this now breaks if they are assigned to an object:
```
function test(): ColorValue {
  return "foo";
}

const colors = {
  foo: test(),
};

const styles = StyleSheet.create({
  checked: {
    color: colors.foo,
  },
});
```

Results in:
```
error TS2322: Type 'string | symbol' is not assignable to type 'string | unique symbol | undefined'.
  Type 'symbol' is not assignable to type 'string | unique symbol | undefined'.
```

Authors:
@alexbrazier 

Reviewers:
@zoontek
@rickhanlonii
@dotconnor
@TheSavior
@pesoklp13
@alloy
@tom-un

Version:
typescript: 3.9.7
@types/react-native: 0.63.8

**Comment by alloy** [comment]
I wonder if your issue is one that requires more explicit typing, such as [this example](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963/commits/cdaa613261d0cd20ea3757d2cc250e9bf4faca46#diff-2aa49bfa477648677014849cb12af571R332)? If not, could you create a PR with a failing test that shows the issue?

**Comment by danilobuerger** [comment]
@alloy I think the problem is that unique symbols are not assignable without loosing the unique part:
```
const a: unique symbol = Symbol("a")
const b = { a }
```
results in
```
declare const a: unique symbol;
declare const b: {
    a: symbol;
};
```
In case of the example as soon as `test()` is assigned, the resulting `colors.foo` is not of type `string | unique symbol` but `string | symbol`.

**Comment by alloy** [comment]
How wide-spread is this? As in, how bad would it be to do either one of these?

```ts
const colors: { foo: ColorValue } = {
  foo: test(),
};
```

or

```ts
const colors = {
  foo: test() as ColorValue,
};
```

**Comment by danilobuerger** [comment]
Right now I am using the latter as a workaround. However, this gets quite annoying with a lot of colors. (The first approach scales even worse as you would have to list every field name again).

**Comment by alloy** [comment]
> The first approach scales even worse as you would have to list every field name again

What about?

```ts
const colors: Record<string, ColorValue> = {
  foo: test(),
};
```

**Comment by danilobuerger** [comment]
Somebody will write `colors.bar` instead ;) You loose the type information about the field names.

**Comment by alloy** [comment]
I’m unsure what you mean, can you give a more complete example?

**Comment by danilobuerger** [comment]
Well if you type it as a `Record`, you loose the information what concrete fields are inside `colors`.

Anyway, I am not looking for a workaround (already got one as explained). We should rather think about how to solve the underlying issue. In reality `PlatformColor` doesn't return a `unique symbol` but an object.

**Comment by alloy** [comment]
> Well if you type it as a `Record`, you loose the information what concrete fields are inside `colors`.

Ah, yes, I see what you mean.

> Anyway, I am not looking for a workaround (already got one as explained). We should rather think about how to solve the underlying issue.

To be clear, I wasn’t trying to suggest a workaround to you; I’m trying to understand how big of an issue this is and what an actual acceptable solution would be _for others_.

> In reality `PlatformColor` doesn't return a `unique symbol` but an object.

Yes, but that object contains implementation details that we don’t want to expose, hence the usage of `unique symbol` which is the only replacement for Flow’s `opaque` type, that I know of.

**Comment by danilobuerger** [comment]
> To be clear, I wasn’t trying to suggest a workaround to you; I’m trying to understand how big of an issue this is and what an actual acceptable solution would be for others.

Ah sorry, I misunderstood your intent. Yes, that seems the way to go!

> Yes, but that object contains implementation details that we don’t want to expose, hence the usage of unique symbol which is the only replacement for Flow’s opaque type, that I know of.

I thought typescript doesn't really have opaque types, just workarounds? Something along the following lines could work:
```
type OpaqueColorValue = {__TYPE__: "OpaqueColorValue"};
type ColorValue = string | OpaqueColorValue;
```

**Comment by alloy** [comment]
> I thought typescript doesn't really have opaque types, just workarounds?

Correct 😞 

> Something along the following lines could work:
> 
> ```
> type OpaqueColorValue = {__TYPE__: "OpaqueColorValue"};
> type ColorValue = string | OpaqueColorValue;
> ```

Yeah something like that was originally proposed on #45963 too, there doesn’t seem to have been a real decision for one over the other. Technically I prefer the opaqueness of the unique symbol vs a bogus object, but I also don’t feel very strong about it.

How bad is the problem for you specifically and/or would you be ok and see if many more people report problems with the ergonomics of the current solution?

**Comment by danilobuerger** [comment]
I keep all my colors in one file. So its just 30 times `as ColorValue` for me right now and they don't really change often. So not really a problem, more of an eyesore. But there could obviously be more edge cases.

**Comment by alloy** [comment]
Aye, I hear you. Ok, let’s leave it as-is for now then, but leave this issue open so others can find it and chime in.

Thanks for the feedback, though! 🙏

**Comment by yvbeek** [comment]
This change is causing quite a few issues in our project.

We, like many others, use the `react-native-vector-icons` library. The color of the icon is defined as `color?: string;`. Because of this change I can no longer assign a StyleSheet class' color to this property.

What would be the best way to solve this?
I don't really want to sprinkle `as string` all over my code.

**Comment by alloy** [comment]
@yvbeek That seems to be a different issue. Colors simply are no longer just strings in v0.63, so it sounds like the lib needs an update instead.

**Comment by yvbeek** [comment]
@alloy Ok, those libraries will probably get updated in the coming weeks. I think for now I will pin it to the old `@types/react-native` version. I've tried to override the definitions of the other libraries, but that doesn't seem to work.

**Comment by rurikoaraki** [comment]
I'm having issues with this typing as well. I'm trying to update a package to use ColorValue so that consumers of the package can use PlatformColors for some color props, however the fact that ColorValue isn't directly assignable from an object is making the shift painful. More importantly our package uses a lot of new objects which contain props that take from objects with color props, and we allow the package's consumers to create their own objects with color props to use with our components, so I'm worried consumers of the package will encounter a build break if we shift to support ColorValue. The PR with the change is microsoft/fluentui-react-native#694 to give an idea of what needed to be done to get the update to compile. Any chance we can get the typing to be more friendly to assignments from objects?

**Comment by keerthika-priya** [comment]
What exactly does this line mean?
`type OpaqueColorValue = symbol & { __TYPE__: 'Color' };`
What is  the meaning of `{ __TYPE__: 'Color' }`? What does 'Color' signify here?
