### ISSUE TITLE
[react-router] useParam's return type fails in TypeScript 4.0.2

### ISSUE THREAD

**Issue by mxsxs2** [DefinitelyTyped/DefinitelyTyped#46946]
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @eps1lon 

Source:
```
import React from 'react'
import { useParams } from 'react-router-dom'

const Component = () => {
    const { id } = useParams()
    return (
        <span>Id: {id}</span>
    )

}
export default Component
```

After updating TS to 4.0.2 from 3.9.7 I get the following error:
```
test.tsx:5:13 - error TS2339: Property 'id' does not exist on type '{}'.

5     const { id } = useParams()
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c2859fdc14663c4f285ecc11447cb668cfcf3ee4/types/react-router/index.d.ts#L164
