### ISSUE TITLE
[@types/lodash] Got failed on version 4.17.6

### ISSUE THREAD

**Issue by 97lynk** [DefinitelyTyped/DefinitelyTyped#69932]
Hi everyone,

I just have got a failed when build angular app use `@types/lodash` 

```
Error: node_modules/@types/lodash/common/object.d.ts:1026:46 - error TS1005: '?' expected.
[INFO] 
[INFO] 1026         : K extends `${infer N extends number}` ? T[N]
[INFO]                                                   ~
[INFO] 
[INFO] 
[INFO] Error: node_modules/@types/lodash/common/object.d.ts:1026:51 - error TS2536: Type 'N' cannot be used to index type 'T'.
[INFO] 
[INFO] 1026         : K extends `${infer N extends number}` ? T[N]
[INFO]                                                        ~~~~
[INFO] 
[INFO] 
[INFO] Error: node_modules/@types/lodash/common/object.d.ts:1031:46 - error TS1005: '?' expected.
[INFO] 
[INFO] 1031         : K extends `${infer N extends number}` ? T[N]
[INFO]                                                   ~
[INFO] 
[INFO] 
[INFO] Error: node_modules/@types/lodash/common/object.d.ts:1031:51 - error TS2536: Type 'N' cannot be used to index type 'T'.
[INFO] 
[INFO] 1031         : K extends `${infer N extends number}` ? T[N]
[INFO]                                                        ~~~~
[INFO] 
[INFO] 
[INFO] Error: node_modules/@types/lodash/common/object.d.ts:1041:46 - error TS1005: '?' expected.
[INFO] 
[INFO] 1041         : K extends `${infer N extends number}`
```

My uses:
- lodash 4.17.15
- @types/lodash 4.17.6
- node: 16

I think that relevant the merge request #69696 yesterday.

Thanks all.

**Comment by bunyadahmadli** [comment]
I got same error.

**Comment by ayad-nadeeb** [comment]
<img width="604" alt="image" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/49183072/77b540eb-9531-42fc-ba31-d361d4b8b773">

Having the same issue.

**Comment by Navaneetha151** [comment]
![lodash issue](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/162975120/1b483829-d5be-4be2-9538-58524bc0d451)
Having the same issue but version is 4.17.13

**Comment by kamleshpaliwalreg** [comment]
./node_modules/@types/lodash/common/object.d.ts:1026:46
Type error: '?' expected.

[0m [90m 1024 | [39m    type [33mGetFieldTypeOfArrayLikeByKey[39m[33m<[39m[33mT[39m [36mextends[39m unknown[][33m,[39m [33mK[39m[33m>[39m [33m=[39m[0m

**Comment by XavierDess** [comment]
I got the same error too since the publish of the new 4.17.6 version yesterday

**Comment by cmonzon44** [comment]
i got de same error since the new published yesterday.
![Screenshot 2024-06-27 210606](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/11430219/3220a1d9-7ef0-4733-97a4-96039cf3f6b8)

**Comment by ivan-junior** [comment]
Getting back to previous version solved for me

``
npm uninstall @types/lodash
npm install @types/lodash@4.17.5
``

**Comment by birdofpreyru** [comment]
Hey guys, I am the author of that change. What TypeScript version are you using?

**Comment by kamleshpaliwalreg** [comment]
4.6.4

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ivan-junior** [comment]
4.5.4

Yeah. That is it!

**Comment by Navaneetha151** [comment]
> > Getting back to previous version solved for me
> > `npm uninstall @types/lodash` `npm install @types/lodash@4.17.5`
> 
> ✅ Agree. This is the best decision for now.

Thanks [97lynk](https://github.com/97lynk) . works for me.

Using  typescript version 4.6.4

**Comment by hycentra-james** [comment]
I'm also the same error on mine:

"@types/lodash": "^4.14.198",
"lodash": "^4.17.21",
"typescript": "~4.3.5",

node 16

**Comment by birdofpreyru** [comment]
Perhaps, just bump your Typescript to at least v4.8? Will solve you this issue, and hardly break anything in your code, I guess, when upgrading from 4.6.

**Comment by 97lynk** [comment]
> Perhaps, just bump your Typescript to at least v4.8? Will solve you this issue, and hardly break anything in your code, I guess, when upgrading from 4.6.

Right. I am using typescript 4.6.3.

**Comment by MaheshBusa93** [comment]
Can someone help me out what version needs to used to fix the issue ??
@cmonzon44  @birdofpreyru @97lynk  @bunyadahmadli @ayad-nadeeb

**Comment by Ritcabuchi** [comment]
typescript: 4.2.4

**Comment by MaheshBusa93** [comment]
@Ritcabuchi  
But as per above discussion it should be 
**Perhaps, just bump your Typescript to at least v4.8? Will solve you this issue, and hardly break anything in your code, I guess, when upgrading from 4.6.**

**Comment by coyaSONG** [comment]
2 ways to resolve this issue
1. use the use a @types/loadash version lower than 4.17.6
2. use higher typescript v4.8.

Am I understanding this correctly?

**Comment by birdofpreyru** [comment]
Yes. I even would not call it as _an issue_, and close this ticket already &mdash; who relies on an obsolete version of a dependency (TypeScript) cannot expect that it will continue to work seamlessly with latest version of other related dependencies (`@types/lodash`).

**Comment by sunnywilson93** [comment]
Upgrade typescript to v5+.
Apart from this, if you're using any bundlers (e.g., Rollup, Webpack), don't forget to upgrade their TypeScript-related packages as well.
I had to upgrade rollup-plugin-ts.

**Comment by retamozo** [comment]
After I bumped into TS v4.5.9 it got solved.

**Comment by silverzoey** [comment]
4.5.4

> Hey guys, I am the author of that change. What TypeScript version are you using? The change has been tested with TypeScript 4.8–5.5; I guess, it is broken for TypeSript 4.7 and lower, but support for that was just dropped, as per DefintelyTyped's [Support Window policy](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master?tab=readme-ov-file#support-window).

**Comment by kanikarthi7** [comment]
@birdofpreyru 

My angular version is 13 
typescript 4.4.2
@types/Lodash 4.14.182

am getting issue mentioned below -> 

Error: Error: node_modules/@types/lodash/common/object.d.ts:1026:46 - error TS1005: '?' expected.

1026         : K extends `${infer N extends number}` ? T[N]
                                                  ~


Error: Error: node_modules/@types/lodash/common/object.d.ts:1031:46 - error TS1005: '?' expected.

1031         : K extends `${infer N extends number}` ? T[N]
                                                  ~


Error: Error: node_modules/@types/lodash/common/object.d.ts:1041:46 - error TS1005: '?' expected.

1041         : K extends `${infer N extends number}`


plz give me solution,,

thanks

**Comment by retamozo** [comment]
> @birdofpreyru
> 
> My angular version is 13 typescript 4.4.2 @types/Lodash 4.14.182
> 
> am getting issue mentioned below ->
> 
> Error: Error: node_modules/@types/lodash/common/object.d.ts:1026:46 - error TS1005: '?' expected.
> 
> 1026 : K extends `${infer N extends number}` ? T[N] ~
> 
> Error: Error: node_modules/@types/lodash/common/object.d.ts:1031:46 - error TS1005: '?' expected.
> 
> 1031 : K extends `${infer N extends number}` ? T[N] ~
> 
> Error: Error: node_modules/@types/lodash/common/object.d.ts:1041:46 - error TS1005: '?' expected.
> 
> 1041 : K extends `${infer N extends number}`
> 
> plz give me solution,,
> 
> thanks

dude, read the thread.

**Comment by kanikarthi7** [comment]
@retamozo  yes dude,, am did whatever above mentioned version's but that time my angular version not supported ,, so that's reason i mentioned here with my angular version..
am tried below version's
typescript - 4.8.4
@types/lodash -4.17.5

**Comment by birdofpreyru** [comment]
What do you want from me @kanikarthi7 ? The current Angular version is v18, you are using an obsolete v13 &mdash; you should have all your dependencies frozen at their ancient versions, compatible with Angular v13, I guess.

**Comment by kanikarthi7** [comment]
@birdofpreyru ,,
yes am using with older versions only and it was working fine till 28th June 2024. But when am trying now without doing any modification of my packages. ng build is getting failed.
 
my older version of
lodash- 4.14.182
typescript- 4.4.2
angular- 13.0.3

**Comment by birdofpreyru** [comment]
@kanikarthi7 Do you expect me to give you a free lecture on how dependencies are managed by NPM, and what is the purpose of `package-lock.json`, which it seems you don't use?

**Comment by DhakshinaMoorthi-Techee** [comment]
I am getting the same error. Currently, I am using Angular version **11.2.1** and TypeScript version **4.1.5**. If I upgrade the TypeScript version to **4.8.4**, it gives an error saying I must use a TypeScript version between **4.0** and **4.2**. Please help me resolve this issue.

Current versions:
- Angular: **11.2.1**
- TypeScript: **^4.1.5**
- Lodash: **^4.17.4**

**Comment by epoiate** [comment]
You are right, it is an older version and we should update. I am in the process of migrating from angular 12 to angular 13 myself and the commit that was working last time I tested now doesn't.

The following was working in Angular 12:
    "typescript": "~4.3.5",
    "lodash-es": "^4.17.21",
    "@types/lodash-es": "^4.17.21",

now with Angular 13 I get the same problem as everyone else
    "typescript": "~4.6.4",
    "lodash-es": "4.17.5",
    "@types/lodash-es": "4.17.5",

For some reason, even downgrading to the recommended version isn't working.

I don't need anyone to fix an older version with an unsupported TS. 
I just need some help to define which version works so that I can migrate to Angular 14 and up later.

> Hey guys, I am the author of that change. What TypeScript version are you using? The change has been tested with TypeScript 4.8–5.5; I guess, it is broken for TypeSript 4.7 and lower, but support for that was just dropped, as per DefintelyTyped's [Support Window policy](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master?tab=readme-ov-file#support-window).

Maybe, as breaking change, this could have been a step up to 4.18.0

**Comment by birdofpreyru** [comment]
Try using `npm ls PACKAGE_NAME` to check what versions of involved packages you ended up with in your `node_modules`. Perhaps some aren’t those you think they are.

**Comment by plee-fn** [comment]
@birdofpreyru 
Hi, I'm also running into some errors regarding `number.`
Here is an example use case:
```
import { get } from 'lodash';

export type FieldSourceObject = {
  value: string | number;
  disabled?: boolean;
};

type FieldSourceType = string | FieldSourceObject;

const values: FieldSourceType[] = [{ value: 'test' }, { value: 'test2' }];
const realValue: FieldSourceType[] = values.map((val) => get(val, 'value', val));

console.log(realValue);
```

The error I'm seeing on `realValue` is:
```
src/test.ts:11:7 - error TS2322: Type '(number | FieldSourceType)[]' is not assignable to type 'FieldSourceType[]'.
  Type 'number | FieldSourceType' is not assignable to type 'FieldSourceType'.
    Type 'number' is not assignable to type 'FieldSourceType'.

11 const realValue: FieldSourceType[] = values.map((val) => get(val, 'value', val));
```

I'm running on:
```
"@types/lodash": "4.17.6",
"lodash": "4.17.21",
"typescript": "5.5.3",
```

**Comment by birdofpreyru** [comment]
@plee-fn do you understand TypeScript? This is the correct behavior! The type of value at `value` path of `FieldSourceType` is `string | number | undefined` (`undefined` because `FieldSourceType` can be a `string`). Now, you do `get(val, 'value', val)`, so instead of `undefined` it falls back to `typeof val`, which is `FieldSourceType`. This way `values.map((val) => get(val, 'value', val))` returns the result of type `(string | number | FieldSourceType)[]`, but because your `FieldSourceType` already includes `string` possibility, it is simplified to just `(number | FieldSourceType)[]`, which you try to assign to a variable of `FieldSourceType[]`, hence the error.

This is exactly a sort of situations that my change fixed. Prior to my patch, `@types/lodash` failed to evaluate correct types in such complex scenarios and fell back to `any`, thus whitelisting your typing error!

You may thank me for detailed explanations via my [GitHub.Sponsors](https://github.com/sponsors/birdofpreyru) page :sweat_smile:

**Comment by plee-fn** [comment]
@birdofpreyru Thanks for the insight! I was able to solve my problem.

**Comment by pifou25** [comment]
Hello,
I also downgraded  @types/lodash:4.17.4 to fix this issue... :/ as this change breaks compatibility with actual typescript, it should go to a new version 4.18.x or even better a new major version 5.0.0 ?

**Comment by AndroPlus** [comment]
Hi all,
Why suddenly this issues popsup. 
We didn't changed any recently on package.json. 

From july1, this issue seems popping up

**Comment by Elias-Vdw** [comment]
@AndroPlus 
I'd wager you have a ~ or a ^ in front of your version for lodash in your package.json
that means it will automatically install minor or patch updates. Removing this symbol and running npm i again should solve your issue. Or upgrading typescript version

**Comment by 97lynk** [comment]
> @AndroPlus I'd wager you have a ~ or a ^ in front of your version for lodash in your package.json that means it will automatically install minor or patch updates. Removing this symbol and running npm i again should solve your issue. Or upgrading typescript version

Agree with you, Almost bro is using `^` in their `package.json`.

**Comment by cheey-maimu** [comment]
> Getting back to previous version solved for me
> 
> `npm uninstall @types/lodash` `npm install @types/lodash@4.17.5`

This problem is solved,Nice!!!

**Comment by jakebailey** [comment]
Per https://github.com/DefinitelyTyped/DefinitelyTyped#support-window, TS 4.8 is no longer a supported version of TypeScript. If you're hitting this issue, you really need to continue to pin your deps (you're already doing so with an ancient version of TypeScript), or update your version of TypeScript.

This break is an "obvious" one, but because nobody tests with such old versions of TypeScript, you may already be broken or become broken in even more subtle ways than this.

**Comment by ryfazrin** [comment]
> Getting back to previous version solved for me
> 
> `npm uninstall @types/lodash` `npm install @types/lodash@4.17.5`

Thank you. It work on my project (nextjs v12) 👍 
For additional, I remove `~` or a `^` in front of version for lodash & types/lodash in my package.json.

**Comment by birdofpreyru** [comment]
Read the fucking thread, dude! 🤦‍♂️

**Comment by huang-1234** [comment]
I got same error.

**Comment by jjkavalam** [comment]
You are hitting this error likely because your TypeScript version is old. Use the more recent versions and you should be fine.

**Comment by ahmedshalaby24** [comment]
still get same error , any solution ? 
RN: 0.64,
lodash: 4.17.15,
@types/lodash: 4.17.5

**Comment by komendantaa** [comment]
`4.17.5` doesn't work for me. 

Here is my worked solution. 

env BEFORE  (with errors)
-  lodash: 4.17.21
- @types/lodash: ^4.14.176
- typescript: ~4.2.3


install types for exact typescript v `4.2`
```
npm i -D @types/lodash@ts4.2
```


env AFTER (no errors)
-  lodash: 4.17.21
- @types/lodash: ^4.14.191
- typescript: ~4.2.3
