### PR TITLE
`sinon-chai`: fix version of dependency `@types/chai`

### LINKED ISSUE #40956: [@types/sinon-chai] Incompatibility with @types/chai 3.x
- [x] I tried using the `@types/sinon-chai` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

v2.7.36 of `@types/sinon-chai` is not compatible with v3.x of `@types/chai`. If we go back one patch version to v2.7.35 everything is fine. The problem seems to be that v2.7.36 has the following line:

```
declare const sinonChai: Chai.ChaiPlugin;
```

The `ChaiPlugin` type has been introduced  recently in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37451 and is not available in `@types/chai` 3.x releases.

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40956

`@types/sinon-chai` now requires versions of `@types/chai` 4.2.0 and above, because it references `ChaiPlugin`, and `ChaiPlugin` was added in `@types/chai` 4.2.0: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37451#issuecomment-519584606

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Review by jednano — APPROVED** [review]

**Comment by sandersn** [comment]
I don't understand -- doesn't `@types/sinon-chai` get the latest version of `@types/chai` by default? That looks like 4.2.11 to me.

**Comment by OliverJAsh** [comment]
> doesn't `@types/sinon-chai` get the latest version of `@types/chai` by default?

It does, because of the wildcard `*` dependency specified in the currently generated `package.json`. However, I think that's only the case if you don't already have `@types/chai` installed. If you already have it installed, it will just re-use that version, and that may be lower/older than `4.2.0`.

To illustrate the problem, I created a reduced test case: https://github.com/OliverJAsh/cypress-sinon-chai-error.

This project has `@types/chai` `4.0.2` installed. When I install `cypress` (which depends on _specific versions_ of `@types/chai` and `@types/sinon-chai`) and then run `tsc`, I get this type error:

```sh-session
$ tsc
node_modules/@types/sinon-chai/index.d.ts:107:31 - error TS2694: Namespace 'Chai' has no exported member 'ChaiPlugin'.

107 declare const sinonChai: Chai.ChaiPlugin;
                                  ~~~~~~~~~~


Found 1 error.
```

It seems to be because `@types/sinon-chai` is loading `@types/chai` from the root `node_modules`, which is the version of `@types/chai` we had installed originally. However, this version does not satisfy the requirements of `@types/sinon-chai`—these types only work with `@types/chai` `^4.2.0`, because `ChaiPlugin` was added in `4.2.0`.

**Comment by OliverJAsh** [comment]
@sandersn Any thoughts on my last comment?
