### PR TITLE
[node-forge] Added pkcs12 typings

### PR DESCRIPTION
**Pull request by flynetworks**
Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/digitalbazaar/forge#pkcs12
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by westy92** [comment]
Is there any difference from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14730?

**Comment by flynetworks** [comment]
No but #14730 isn't merged since two weeks and i got no answer on my comments

**Comment by westy92** [comment]
Unfortunately merging can be a bit spotty.  Best to just be patient and wait for the powers that be to get to it.  I reflected my approval above.

**Comment by yuit** [comment]
@flynetworks Thank you for reopening the PR again and sorry for delay in merging here.

**Comment by flynetworks** [comment]
@yuit thanks for merging 👍 I'll delete my fork now. Can you estimate when the update is available via npm?

**Comment by lukiano** [comment]
I'm getting
`node_modules/@types/node-forge/index.d.ts(265,17): error TS2411: Property 'localKeyId' of type 'Bag[] | undefined' is not assignable to string index type 'Bag[]'.`
`node_modules/@types/node-forge/index.d.ts(266,17): error TS2411: Property 'friendlyName' of type 'Bag[] | undefined' is not assignable to string index type 'Bag[]'.`
seems to be something introduced in commit ac8fb9a.

**Comment by flynetworks** [comment]
Ok i'll have a look. Can you post some sample code, please?

**Comment by lukiano** [comment]
the compiler complains on `index.d.ts` . Just mind this is with `strictNullChecks` enabled

**Comment by flynetworks** [comment]
I've created a new [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15082) to fix this issue. Thanks for reporting and sorry for the inconvenience.

**Comment by lukiano** [comment]
Thank you very much for that
