### ISSUE TITLE
TS2304 Cannot find name 'SVGElementTagname'

### ISSUE THREAD

**Issue by nat42** [DefinitelyTyped/DefinitelyTyped#43977]
`@types/jquery` v3.3.5 released to NPM from a day ago broke our build with Typescript 2.8.4 and testing showed it also failed to build for Typescript 3.3.35 Seems to be due to the merge of PR 43857

Typescript compile errors compiling the @types/jquery with error TS2304 Cannot find name 'SVGElementTagname' this does not seem to be a type name that Typescript knows about (and we aren't using anything that should need to know about jquery finding SVG elements in our code)

Can we revert / ammend this PR so that it doesn't break for general use cases?

Also, this has left me concerned as to what testing if any occurs before releases are deemed stable? Projects I work on might be manually updated for type packages if changes are going from development to stable release without testing

**Comment by jeeva-nikam** [comment]
Facing the same error, error statement is given below.
ERROR in node_modules/@types/jquery/JQuery.d.ts(4137,26): error TS2304: Cannot find name 'SVGElementTagNameMap'.

**Comment by dhilipswaminathan** [comment]
Facing the same error, error statement is given below.
ERROR in node_modules/@types/jquery/JQuery.d.ts(4137,26): error TS2304: Cannot find name 'SVGElementTagNameMap'.

This is delaying our production deployment.

**Comment by martin-badin** [comment]
You have to upgrade the typescript version. The type was added to the version 2.7 https://github.com/microsoft/TypeScript/issues/14783

**Comment by Nadav-Revuze** [comment]
any solution ?

**Comment by martin-badin** [comment]
> any solution ?

You have to upgrade typescript.

**Comment by arunranaoodles1** [comment]
is there any other solution, because upgrading our app is causing a lot of issues; also we are facing this error only when building with jenkins or cloning the repo and then running npm install; however it gets resolved when we uninstall @types/jquery and @types/bootstrap and then manually install them using npm install @types/jquery and npm i @types/bootstrap; this is not a good strategy as we  the team cannot build the project manually everytime; so any solution would be very much helpfull guys

**Comment by martin-badin** [comment]
Did you try to upgrade TS to version < 3.0? (2.7,2.8,2.9)

**Comment by arunranaoodles1** [comment]
> Did you try to upgrade TS to version < 3.0? (2.7,2.8,2.9)

i did once but the compiling was giving warnings; plus its not allowed to us to upgrade ts bcoz then we get a lot of other issues as the project is highly complex and big; and guys can you help me with the manual npm i @types.... issue; im still confused about that; and the jenkins part too

**Comment by martin-badin** [comment]
I understand your requirements but I think that this is a normal process of development and we shouldn't stop on a specific version.

Maybe you can add to the package.json the correct version of this package.

**Comment by pabloleone** [comment]
I solved the issue downgrading to a specific version prior to the broken release.

```
"@types/jquery": "3.3.31",
"jquery": "3.3.1",
```

Removed `node_modules` and `package-lock.json` then install everything again (`npm i`) and everything worked again!

**Comment by pcd27** [comment]
I was facing the same issue.
The error says like:
ERROR in node_modules/@types/jquery/JQuery.d.ts(4137,26): error TS2304: Cannot find name 'SVGElementTagNameMap'

Solved it by going to the file 'JQuery.d.ts' mentioned in the path projectFolder/node_modules/@types/jquery 
and commenting this line:
// find<K extends keyof SVGElementTagNameMap>(selector_element: K | JQuery<K>): JQuery<SVGElementTagNameMap[K]>;

Its working fine now.

**Comment by martin-badin** [comment]
> I was facing the same issue.
> The error says like:
> ERROR in node_modules/@types/jquery/JQuery.d.ts(4137,26): error TS2304: Cannot find name 'SVGElementTagNameMap'
> 
> Solved it by going to the file 'JQuery.d.ts' mentioned in the path projectFolder/node_modules/@types/jquery
> and commenting this line:
> // find(selector_element: K | JQuery): JQuery<SVGElementTagNameMap[K]>;
> 
> Its working fine now.

You can solve it by upgrading the TS version or downgrade `@types/jquery`.

**Comment by oyepez003** [comment]
I just upgrade the typescript version from **typescript": "2.4.2"** to **typescript": "2.7.2"**

`rm -rf node_modules package-lock.json && npm install`

**Comment by josteink** [comment]
Sounds to me like this issue can be considered resolved by now?

**Comment by krissolz** [comment]
I faced the same issue 

**node_modules/@types/jquery/JQuery.d.ts(4137,89): error TS2304: Cannot find name 'SVGElementTagNameMap'.**

and 

**npm install typescript@2.7.2 --save-dev** 

as it was mentioned above, fixed the problem without doing anything else.

Regards

**Comment by moorthi07** [comment]
> I faced the same issue
> 
> **node_modules/@types/jquery/JQuery.d.ts(4137,89): error TS2304: Cannot find name 'SVGElementTagNameMap'.**
> 
> and
> 
> **npm install typescript@2.7.2 --save-dev**
> 
> as it was mentioned above, fixed the problem without doing anything else.
> 
> Regards

worked for me. thx

**Comment by React-helmet** [comment]
@martin-badin https://jqcode.space/questions/jquery-is-not-available-for-use
