### ISSUE TITLE
Cannot find name 'Dynamsoft' after upgrading to @types/dwt v15

### ISSUE THREAD

**Issue by rooby** [DefinitelyTyped/DefinitelyTyped#36641]
- [x] I tried using the `@types/dwt` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
Authors: @lincoln2018 , @yushulx , @Tom-Dynamsoft 

I was previously using v14.x of the DWT package and type and it was working,
After updating to 15.x I am getting these errors:

> error TS2552: Cannot find name 'Dynamsoft'. Did you mean 'dynamsoft'?

It seems like this might relate to the removal of the Dynamsoft namespace from @types/dwt in v15.

I am currently using angular 7.x and typescript 3.1.x and am loading the dwt javascript by including it in my angular.json scripts array.

Is that namespace something that could be added back in or should I change my implementation based on it no longer being there?

**Comment by rooby** [comment]
Previously I had been using a custom install of the Dynamsoft code instead of the npm package, due to having to override the install.js script ( to do this: https://developer.dynamsoft.com/dwt/kb/2902 ).

I guess that kind of usage is no longer supported and I should switch to using the npm package.
I'll just have to work out how to replicate the functionality in that link.

**Comment by Tom-Dynamsoft** [comment]
@rooby Regarding the install.js, this file is dynamically loaded by JavaScript in dynamsoft.webtwain.initiate.js. The path for it is defined like the following in dynamsoft.webtwain.config.js

`Dynamsoft.WebTwainEnv.ResourcesPath = 'Resources';`

The code above uses a relative path, in your case, you can use an absolute path and point to a directory on your own server where there is a copy of the install.js . This way, you are free to change the file.

BTW, we did have an issue with v15.0 when using Angular 7 and it has been fixed. Please check out the latest sample

`http://download.dynamsoft.com/Samples/DWT/Scan-Documents-with-AngularJS-TS.zip`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
