### ISSUE TITLE
@types/graphql@0.13.0: Type alias 'IntrospectionTypeRef' circularly references itself.

### ISSUE THREAD

**Issue by Ben305** [DefinitelyTyped/DefinitelyTyped#24744]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/graphql` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @TonyPythoneer @calebmer @intellix @firede @kepennar @freiksenet @IvanGoncharov @DxCx @rportugal @tgriesser @dyst5422 @adnsio @divyenduz 

After upgrading from 0.12.7 to 0.13.0, I see the following error when running _tsc_:

> node_modules/@types/graphql/utilities/introspectionQuery.d.ts(95,13):
> error TS2456: Type alias 'IntrospectionTypeRef' circularly references itself.

**Comment by IvanGoncharov** [comment]
@firede Can you please take a look?

**Comment by Ben305** [comment]
The problem was caused by an outdated globally installed version of typescript (2.5.3). Upgrading to 2.8.1 fixed the issue.

**Comment by fsc7** [comment]
I am using version typescript 3.0.1 and @types/graphql 0.13.4 and I am getting the same error
