### ISSUE TITLE
@types/underscore error TS2322 for `_.chain` after upgrade to v1.9

### ISSUE THREAD

**Issue by smileLilith** [DefinitelyTyped/DefinitelyTyped#36308]
After upgrade of `@types/underscore` from v1.8.20 to v1.9.0 all usages of `_.chain` in my angular project were broken. For example
```
const arr1: string[] = ['z', 'x', 'y'], query = 'z';
let arr2: string[] = ['a', 'b', 'c'];
...
arr2 = _.chain(arr1)
      .union(arr2)
      .without(query)
      .value()
```
has returned
```
error TS2322: Type 'string' is not assignable to type 'string[]'
```

It seems it was caused by changes done in [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/9cf5c98aa8c9edc65e70dd078e0f94d72d4aa6d1#diff-bc995fed3367d28165753a2581d1af54).

@regevbr, @DanielRosenwasser was this expected? If yes, what is upgrade path?

**Comment by regevbr** [comment]
I'm sorry for that. I will get right on it.
Thanks for reporting!

**Comment by smileLilith** [comment]
No worries, thank you

**Comment by regevbr** [comment]
The changes made at #36230 caused it
@jgonggrijp the changes we just made caused a breaking chnage and I verified it in the test of the library.
As I mentioned in the PR - I will need to revise all the methods under the _.Chain interface so they will not break existing code.
Any suggestions for now?

**Comment by jgonggrijp** [comment]
@regevbr I have nothing to add to what you already said. Add tests that replicate the problem, then revise the code until all tests pass again.

And then wait until the next issue comes up... it's a fact of life.

**Comment by regevbr** [comment]
@jgonggrijp I already did it and the fix takes a second but I found myself revising the entire library as almost 90% of the _Chain interface is completely wrong (even from before the change). I also noticed that there are some missing methods declarations and dome deprecated ones.
I want to finish the complete revision of the library but it is going to take a few days for us to ping pong on the review as it will be a big one

**Comment by jgonggrijp** [comment]
@regevbr Would it be doable for you to submit a PR that only fixes the current issue first? I don't mind reviewing twice, and while I agree it's important for the Chain interface to be correct, I'd say that newly introduced bugs are a bit more urgent to fix than long-existing ones.

**Comment by regevbr** [comment]
@jgonggrijp sure coming right up
