### PR TITLE
d3-selection: Use $ExpectError

### PR DESCRIPTION
**Pull request by denisname**
Use $ExpectError in tests.
Some tests don't fail anymore, as TypeScript type inference has improved.

### CODE REVIEW

**Comment by denisname** [comment]
@andy-ms The CI failures looks incorrect. Changes I made are not related, only `d3-selection-test.ts` has been changed. I don't see how I can resolve this...

```
Testing...
tests
c3 OK
d3-selection OK
d3/v4 OK
d3-axis OK
d3 OK
d3-brush OK
d3-chord OK
d3-contour OK
d3-drag OK
d3-geo OK
d3-graphviz OK
d3-sankey OK
d3-selection-multi OK
d3-shape OK
d3-transition OK
d3-zoom OK
d3kit OK
react-faux-dom OK
react-native-svg-charts failing:
   Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/d3-shape/index.d.ts:325:16
   ERROR: 325:16   expect  TypeScript@next compile error: 
   Cannot find name 'CanvasRenderingContext2D'.
   [etc.]
```

**Comment by andy-ms** [comment]
`react-native-svg-charts` is a `react-native` package, so presumably it shouldn't be relying on `--lib dom`. But it imports from `d3-shape` which does require `--lib dom` due to using `CanvasRenderingContext2D` in many places. I do see a comment `(Note that this is a subset of the CanvasRenderingContext2D interface!)` -- maybe it should be using its own type then instead of using the type from `--lib dom`?

**Comment by denisname** [comment]
@andy-ms The `d3-shape` depends on `CanvasRenderingContext2D`, as it allows "to render to a Canvas 2D context". So `d3-shape` is correct. If `react-native-svg-charts` does not want to depends on `dom` it should not import any d3 libraries.

This PR is correct and should be accepted.

The error here was introduced by PR #29799. This made it now impossible to change d3 because a PR with a CI fail and d3 dependency has been accepted.

**Comment by andy-ms** [comment]
It looks like `react-native-svg-charts` has depended on `d3` since the beginning, as does the real package (https://github.com/JesperLekland/react-native-svg-charts/blob/dev/package.json) . It looks like `d3-shape` may have uses outside of the CanvasRenderingContext2D. In situations like this it may be better to 'predeclare' the type without giving it a body, as in `declare global { interface CanvasRenderingContext2D {} }`, so that the "dom" lib isn't necessary.

**Comment by denisname** [comment]
Thanks @andy-ms 😃.
