### PR TITLE
Update dom4.d.ts to work with TS 2.0.2+

### PR DESCRIPTION
**Pull request by hturki**
Or else you get "error TS2687: All declarations of 'children' must have identical modifiers"

Line 18732 of https://raw.githubusercontent.com/Microsoft/TypeScript/v2.0.2/lib/lib.d.ts (the non-raw view gets truncated before that line)

### CODE REVIEW

**Comment by andy-ms** [comment]
You've targeted this PR at the `master` branch. For 2.0-compatible definitions you should use definitions from the `types-2.0` branch (via `npm install @types/dom4`). It already seems to be fixed there, so closing.
