### PR TITLE
[three] allow GLBufferAttribute as an attribute type

### PR DESCRIPTION
**Pull request by mikkom**
This change allows the use of `GLBufferAttribute` as an attribute using the `setAttribute` method in `BufferGeometry`. The type for `GLBufferAttribute` had already been defined and exported but it was not used anywhere else in the typings. The feature was introduced in https://github.com/mrdoob/three.js/pull/13196.

Note that the change can break consumers of the typings as `GLBufferAttribute` does not implement the same interface as `BufferAttribute`. The way to fix these issues is to use the boolean flags (`isBufferAttribute`, `isInterleavedBufferAttribute`, or `isGLBufferAttribute`) to discriminate between the different options (or alternatively by resorting to type assertions). Despite the potential breakage, I believe these typings are more correct.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mrdoob/three.js/pull/13196
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. BoxBufferGeometry
1. CapsuleBufferGeometry
1. CircleBufferGeometry
1. ConeBufferGeometry
1. CylinderBufferGeometry

<details>
<summary>as well as these 19 other properties...</summary>
<p>DataUtils, DodecahedronBufferGeometry, ExtrudeBufferGeometry, IcosahedronBufferGeometry, ImmediateRenderObject, LatheBufferGeometry, LinearSRGBColorSpace, NoColorSpace, OctahedronBufferGeometry, PlaneBufferGeometry, PolyhedronBufferGeometry, RingBufferGeometry, SRGBColorSpace, ShapeBufferGeometry, SphereBufferGeometry, TetrahedronBufferGeometry, TorusBufferGeometry, TorusKnotBufferGeometry, TubeBufferGeometry</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against db3ff7868570b05920c6a3503a4137ee6163b3e2
</p>

**Review by joshuaellis — CHANGES_REQUESTED** [review]
This should be opened in the 'three-TS-types' repo, when you open it there can you provide a link to the src code instead of the v old PR, helps validate its relevance. Thanks!

**Comment by mikkom** [comment]
> This should be opened in the 'three-TS-types' repo, when you open it there can you provide a link to the src code instead of the v old PR, helps validate its relevance. Thanks!

Thanks for the heads-up, I didn't know about the three-ts-types repo. I'll close this PR and create a new one there.
