### ISSUE TITLE
ramda tests fail to compile with tsc v2.4.2

### ISSUE THREAD

**Issue by LiamGoodacre** [DefinitelyTyped/DefinitelyTyped#18761]
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @donnut @mdekrey @LiamGoodacre @mrdziuban @sbking @afharo @teves-castro @1M0reBug 

```sh
~/git/DefinitelyTyped/types/ramda
➞  tsc --version
Version 2.4.2

~/git/DefinitelyTyped/types/ramda
➞  tsc
ramda-tests.ts(1396,9): error TS2345: Argument of type '(a: number[], b: number[]) => number[]' is not assignable to parameter of type '<T3, T4>(x: T3, z: T4) => T3 & T4'.
  Types of parameters 'a' and 'x' are incompatible.
    Type 'T3' is not assignable to type 'number[]'.
ramda-tests.ts(1404,9): error TS2345: Argument of type '(k: string, a: number[], b: number[]) => number[]' is not assignable to parameter of type '<T3, T4>(k: string, x: T3, z: T4) => T3 & T4'.
  Types of parameters 'a' and 'x' are incompatible.
    Type 'T3' is not assignable to type 'number[]'.
```

These are both usages of `mergeDeepWith`:

```typescript
() => {
    const a = R.mergeDeepWith(
        (a: number[], b: number[]) => a.concat(b),
        {foo: {bar: [1, 2]}},
        {foo: {bar: [3, 4]}},
    ); // => {foo: {bar: [1,2,3,4]}}
};

() => {
    const a = R.mergeDeepWithKey(
        (k: string, a: number[], b: number[]) => k === 'bar' ? a.concat(b) : a,
        {foo: {bar: [1, 2], userIds: [42]}},
        {foo: {bar: [3, 4], userIds: [34]}}
    ); // => { foo: { bar: [ 1, 2, 3, 4 ], userIds: [42] } }
};
```

These were added in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18177

In conflict with the comments on that pull request, I would suggest that the function type be `(a: any, b: any) => any`.  I.e:

```typescript
// before
mergeDeepWith<T1, T2>(fn: <T3, T4>(x: T3, z: T4) => T3 & T4, a: T1, b: T2): T1 & T2;

// after
mergeDeepWith<T1, T2>(fn: (x: any, z: any) => any, a: T1, b: T2): T1 & T2;
```

Any thoughts?  I'm not sure there's anything precise we can do here.  I doubt we can compute what the actual types would be based on the types `T1` and `T2`.

**Comment by LiamGoodacre** [comment]
Also, the `mergeWith` and `mergeWithKey` functions could be given precise types here.  But they currently are `(a: any, b: any) => any`.
