### ISSUE TITLE
[@types/googlemaps] Generic type 'MapHandlerMap<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by drcarmen** [DefinitelyTyped/DefinitelyTyped#48574]
Hello, 

I receive this error in the production build phase of my Angular10 project, I use @agm/core ver.3.0.0-beta.0. Everything was working fine until the new release of @types/googlemaps (3.39.14).

These are the errors:

ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).
51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;

node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).
51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
 
Thank you

**Comment by mnjaya** [comment]
I changed line 51 of node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts

from:       subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
to :     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap<any>>(eventName: N): Observable<google.maps.MapHandlerMap<any>[N]>;

and both the errors disappeared and compilation could be completed. Application is working. Not sure if it is a solution to this, though....

**Comment by drcarmen** [comment]
Thank you for your reply, 

Unfortunately, in a context of CI/CD, where everything is installed automatically, this solution won't work ...

**Comment by drcarmen** [comment]
I found a temporary solution, install an earlier version of @types/googlemaps in the package.json, I added @types/googlemaps: "3.39.12" to my devDependencies, now the production build works !

**Comment by RonRofe** [comment]
Same here. I received it after reinstalling the package.

**Comment by mnjaya** [comment]
> Thank you for your reply,
> 
> Unfortunately, in a context of CI/CD, where everything is installed automatically, this solution won't work ...

Certainly.
But there are two points.....
(1) In the said context of CI/CD, the solution should be incorporated into a new version of the package and distributed, which of course the package owner(s) needs to do. I have no idea as to when they will bring out a solution. So I keep a history of changes I locally makes and verifies upon an automatic version update, if the problem persists. It is only an activity of continuing / maintaining my application.
(2) Downgrading the package is certainly an alternative and waiting for the updated solution. In this case too, another package version upgrade can break ones' application.
Since the issue under consideration was found to be of minor nature (according to me), I thought of modifying package to save outage time of my application, and shared it, thinking that it may help someone or trigger the package developer to look into the issue....
Thank you...

**Comment by WaveMeUp** [comment]
Same issue here, downgrading to 3.39.12 resolved this problem.

**Comment by equinlan** [comment]
Same issue here, downgrading to 3.39.12 worked.

**Comment by cbodapati** [comment]
Didn't work for me :( 

"dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular/animations": "~10.1.5",
    "@angular/common": "~10.1.5",
    "@angular/compiler": "~10.1.5",
    "@angular/core": "~10.1.5",
    "@angular/forms": "~10.1.5",
    "@angular/platform-browser": "~10.1.5",
    "@angular/platform-browser-dynamic": "~10.1.5",
    "@angular/router": "~10.1.5",
    "@types/googlemaps": "^3.39.12",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.5",
    "@angular/cli": "~10.1.5",
    "@angular/compiler-cli": "~10.1.5",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }

Error - 
ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
    
can someone pls help?

thanks
Srikanth

**Comment by RonRofe** [comment]
> Didn't work for me :(
> 
> "dependencies": {
> "@agm/core": "^3.0.0-beta.0",
> "@angular/animations": "~10.1.5",
> "@angular/common": "~10.1.5",
> "@angular/compiler": "~10.1.5",
> "@angular/core": "~10.1.5",
> "@angular/forms": "~10.1.5",
> "@angular/platform-browser": "~10.1.5",
> "@angular/platform-browser-dynamic": "~10.1.5",
> "@angular/router": "~10.1.5",
> "@types/googlemaps": "^3.39.12",
> "rxjs": "~6.6.0",
> "tslib": "^2.0.0",
> "zone.js": "~0.10.2"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "~0.1001.5",
> "@angular/cli": "~10.1.5",
> "@angular/compiler-cli": "~10.1.5",
> "@types/node": "^12.11.1",
> "@types/jasmine": "~3.5.0",
> "@types/jasminewd2": "~2.0.3",
> "codelyzer": "^6.0.0",
> "jasmine-core": "~3.6.0",
> "jasmine-spec-reporter": "~5.0.0",
> "karma": "~5.0.0",
> "karma-chrome-launcher": "~3.1.0",
> "karma-coverage-istanbul-reporter": "~3.0.2",
> "karma-jasmine": "~4.0.0",
> "karma-jasmine-html-reporter": "^1.5.0",
> "protractor": "~7.0.0",
> "ts-node": "~8.3.0",
> "tslint": "~6.1.0",
> "typescript": "~4.0.2"
> }
> 
> Error -
> ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap' requires 1 type argument(s).
> 
> 51 subscribeToMapEvent(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
> ~~~~~~~~~~~~~~~~~~~~~~~~~
> node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap' requires 1 type argument(s).
> 
> 51 subscribeToMapEvent(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
> 
> can someone pls help?
> 
> thanks
> Srikanth

Hi,

Try erasing `node_modules` + `package.lock` and run again `npm install`.

**Comment by cbodapati** [comment]
thanks for the reply, but the problem is not resolved...

**Comment by RonRofe** [comment]
> thanks for the reply, but the problem is not resolved...

Did you make sure to stop ng process and run `ng serve` again?

**Comment by cbodapati** [comment]
> > thanks for the reply, but the problem is not resolved...
> 
> Did you make sure to stop ng process and run `ng serve` again?

Oh yes 

1) I stopped 
2) deleted node_modules & package-lock.json 
(tried with "@types/googlemaps": "^3.37.0", "@types/googlemaps": "^3.38.0" , "@types/googlemaps": "^3.40.0")
3) npm install 
4) ng serve

**Comment by cbodapati** [comment]
Thanks It worked with 3.39.12 :)

**Comment by trovend** [comment]
Tried with 3.38.0 and still getting the same error.
It has below line already.

subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;

to who ever it worked, what is your @agm/core package version?

**Comment by cbodapati** [comment]
> Tried with 3.38.0 and still getting the same error.
> It has below line already.
> 
> subscribeToMapEvent(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
> 
> to who ever it worked, what is your @agm/core package version?

"@agm/core": "^3.0.0-beta.0",

For you to get a specific version of @types/googlemaps 

set @types/googlemaps": "3.39.12" in package.json, and then do "npm install"

for more information on symbols used in package.json - https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/

hope this helps

**Comment by trovend** [comment]
thank you @cbodapati 
It worked with @types/googlemaps": "3.39.12"

Just for the benefit for others 
"@types/googlemaps": "3.39.12"

Instead of 
@types/googlemaps": "^3.39.12"

**Comment by vinogautam** [comment]
Thanks guys, It worked with 3.39.12

**Comment by jayantakarmakar03** [comment]
Solution

**Comment by jayantakarmakar03** [comment]
"@agm/core": "^3.0.0-beta.0",
    "@types/googlemaps": "^3.39.12",

**Comment by jayantakarmakar03** [comment]
I got ERROR : 
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

    51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

    51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;

SOLUTION: 
----------------------------------------------------------------------
just inastall 
npm install @types/googlemaps@3.39.12 --save-dev
npm install @agm/core --save

"@agm/core": "^3.0.0-beta.0",
"@types/googlemaps": "^3.39.12",  

the error  was resolved by using the small change in package version and its working fine now .

**Comment by Saireddy191** [comment]
ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;

please help me to rectify this error.

**Comment by JorgeAchulla** [comment]
si pude resolver instalando el plugin npm i @types/googlemaps@3.39.12
Gracias

**Comment by avtarapplify** [comment]
Hello,

I receive this error in the production build phase of my Angular9.1.12. project, I use @agm/core ver.3.0.0-beta.0.

These are the errors:



ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 
type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:93 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerMouseEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
                                                                                               ~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:129 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerChangeOptionEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;

Thanks

**Comment by JoniWaibs** [comment]
step by step to resolve this error.

1 - in the package.json change the types in devDependencies to "@ types / googlemaps": "3.39.12",
2 - Delete node modules,
3 - remove package.lock.json
4 - npm install
5 - ng serve
6 - ng build --prod

All of this should work properly.

**Comment by mathieu2em** [comment]
So the solution is to downgrade the package version ? Since how many months ? hmmm...

**Comment by lutonda** [comment]
> 3.39.12

Work 4 me

**Comment by japc78** [comment]
3.39.13 work for me

**Comment by mitsos1os** [comment]
> 3.39.12

Also worked for me  using Angular 11.1.1 and @agm/core 3.0.0-beta.0

**Comment by cbregantejs** [comment]
work for me:

1 - dependencies -> "@agm/core": "1.0.0", 
2 - devDependencies -> "@types/googlemaps": "^3.36.4",
3 - Delete node modules,
4 - Delete package.lock.json
5 - npm install
6 - ng serve

**Comment by pushpaklive** [comment]
I am using "@angular/core": "~10.2.0", and **issue is solved** after adding below dependencies & devDependencies:

Add below in dependencies in package.json.
**"_@agm/core" : "^3.0.0",
"@angular/google-maps": "^11.0.0",_**

Add below in devDependencies in package,json
"_@types/googlemaps" : "3.39.12_"

But previously adding _"@types/googlemaps" : "3.39.14"_ was giving error, but changing to _"3.39.12"_ compiled everything fine.

Other steps needed for earlier configuration:
Add "googlemaps" to types array in tsconfig.json, tsconfig.app.json files.

**Comment by eminvegan** [comment]
> thank you @cbodapati
> It worked with @types/googlemaps": "3.39.12"
> 
> Just for the benefit for others
> "@types/googlemaps": "3.39.12"
> 
> Instead of
> @types/googlemaps": "^3.39.12"

Thank you very much, worked for me!

**Comment by anugangrade** [comment]
Hi @jayantakarmakar03, I have same error. I spent lots of my time to resolve it. But now I resolved.
steps for resolution:
1. delete node_modules
2. delete package-lock.json
3. now npm install
4. then npm install @types/googlemaps@3.39.12 --save-dev
5. npm install @agm/core --save --legacy-peer-deps
6. then add "googlemaps" in tsconfig.app.json in types array
7. then ng serve
8. after that I see all errors gone.
9. Then try to build, ng build. 

Now everything working fine after 2 days suffer. Thanks for @jayantakarmakar03 I used your steps.

**Comment by hamzahsn** [comment]
I have the same issue, but a weird one, the normal build working fine for me with `ng build --prod` but when I build my Docker image then I have this issue! 

BTW:

```
"@types/googlemaps": "3.39.12",
"@agm/core": "^3.0.0-beta.0",
"@angular/core": "~10.1.1",
```

Any similar behavior?

**Comment by danilomr12** [comment]
With angular ~11.2.11 same error.
Solved with @types/googlemaps 3.39.12 too.

**Comment by hamzahsn** [comment]
@danilomr12 It was fixed by adding it into `dependencies` and not `devDependencies` also clean and install must be done and with using the version: "@types/googlemaps": "3.39.12".

**Comment by AdrianoRabello** [comment]
Nice... thanks @anugangrade !

**Comment by akbarjan** [comment]
Fixed the issue
changed 
    "@types/googlemaps": "^3.39.13"
to
    "@types/googlemaps": "3.39.12"

**Comment by umang195** [comment]
i am using angular13 and when i use agm core for google map I face below error

Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:93 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerMouseEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;


please anyone give me solution for it

**Comment by MustafaK01** [comment]
I'm using Angular 13.3.6,

After deleting the package-lock.json file and the node_modules folder, add **"@agm/core":"^3.0.0-beta.0" to package.json file, under "dependencies". Also add 
"@types/googlemaps": "3.39.12" in same file, under "devDependencies".**
then run **npm install --force**.

**Comment by stefann01** [comment]
Worked with 3.39.12. Thanks!

**Comment by albiorixvimal** [comment]
It's worked with the version 3.39.12!!
Why it's not worked with the latest version anyone have any idea?

**Comment by gst2322** [comment]
> Same issue here, downgrading to 3.39.12 worked.

Thank you man

**Comment by mahen23** [comment]
The   "@capacitor/google-maps": "^4.3.0" plugin is buggy, i had to revert back to agmCore because of this.

**Comment by mohit-realtimate** [comment]
> @types/googlemaps: "3.39.12"

The key is to not have `"^"` before `3.39.12`, it should look like:
`"@types/googlemaps": "3.39.12",`

**Comment by wangela** [comment]
This issue looks obsolete. Please comment if the issue persists in the latest version.
