### ISSUE TITLE
_.find causes compilation errors when using with instanced objects

### ISSUE THREAD

**Issue by trickeyone** [DefinitelyTyped/DefinitelyTyped#22114]
I'm getting a compilation error for `@types/lodash@4.14.88` when trying to use `_.find` on instanced objects.

e.g.
```js
class MyObject
{
  constructor(public value: number, public disabled: boolean) {}
}

const arr = [
    new MyObject(1, false),
    new MyObject(2, false)
];
let found = _.find(arr, {value: 2});
console.log(found.disabled);
```

When attempting to access a property of the returned value, I get this error. This did not occur with v4.14.77.
`Error:(240, 38) TS2339:Property 'disabled' does not exist on type 'number | (() => string) | { (...items: ReadonlyArray[]): MyObject[]; (...items: (MyOb...'.
Property 'disabled' does not exist on type 'number'.`

**Comment by andnp** [comment]
Just out of curiosity, does:
```
class MyObject
{
  constructor(public value: number, public disabled: boolean) {}
}

const arr = [
    new MyObject(1, false),
    new MyObject(2, false)
];
let found = _.find(arr, {value: 2});
found!.disabled
```
compile for you? Note the `!` after `found` on the last line. I can get this to compile with `@types/lodash@4.14.88` and with tsc `2.6.1` and `2.6.2`.

**Comment by aj-r** [comment]
@trickeyone what version of typescript are you using? I can't reproduce this either using `@types/lodash@4.14.106`. (Although I do get an "object is possibly undefined" error unless I use `found!.disabled`)

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
