### PR TITLE
[luxon] add singular units for duration object

### PR DESCRIPTION
**Pull request by gkurt**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://runkit.com/kurtgokhan/luxon-singular-unit-tests

If the API to pass singular units to Duration objects isn't deprecated, I ask them to be added back. I ran into compilation errors when migrating from v1 to v2 in a fairly big codebase.

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
For me that's ok. We want with this PR to allow normalized values (`hours`, `hour`) when creating Luxon objects.
Let's wait for others a while, thx!

**Comment by hugofpsilva** [comment]
Me likey 👍

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@KurtGokhan thx!

**Comment by KurtGokhan** [comment]
Ready to merge
