### PR TITLE
replace params 'any' type with index types

### PR DESCRIPTION
**Pull request by timruffles**
Params have [well-defined values](https://expressjs.com/en/guide/routing.html#route-parameters), so they're not `any`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://expressjs.com/en/guide/routing.html#route-parameters

### CODE REVIEW

**Review by kvcpr — APPROVED** [review]

**Review by MichalLytek — APPROVED** [review]

**Comment by 19majkel94** [comment]
Looks like some tests aren't passing due to old TS version? Typescript 2.2 is required to have [dotted properties with index signatures](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#dotted-property-for-types-with-string-index-signatures).

**Comment by paulvanbrenk** [comment]
Looks like there's 2 issues:

```
Error in express
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js --noLint
express-tests.ts(86,9): error TS2365: Operator '==' cannot be applied to types 'string' and 'number'.
express-tests.ts(86,9): error TS2365: Operator '==' cannot be applied to types 'string' and 'number'.
Error in i18n
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../node_modules/dtslint/bin/index.js 
/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/i18n/i18n-tests.ts
ERROR: 200:50  expect  TypeScript compile error: Property 'lang' does not exist on type '{ [namedParameter: string]: string; [captureGroup: number]: string; }'.
Package compiles in TypeScript 2.3 but not in 2.0.
```

**Comment by RyanCavanaugh** [comment]
@timruffles Please fix the failures indicated in the Travis CI log.

**Comment by andy-ms** [comment]
@timruffles Tests are failing on the following code: `req.params.id == 0`. Is it really true that `params` only has string values?

**Comment by timruffles** [comment]
Sorry for the slow reply. Was abroad and have just started a new role!

@andy-ms re whether it's a string: I think so but it's a great question. Reading the source code and param matching is handled via [RegExp.exec](https://github.com/expressjs/express/blob/9722202df964bfbfc0f579e4baeb5a4e1b43b344/lib/router/layer.js#L129), so `req.params` definitely starts out as string values.

In runtime terms we know `"0" == 0` so that's why the test passes at runtime for string values.

However - one potential complicating factor is some [rather complex stuff](https://github.com/expressjs/express/blob/7027b37764050c550366e808ea84fee1c58233ed/lib/router/index.js#L327) around the `app.param('name', fn)` code.

The good sign is from [the docs](https://expressjs.com/en/4x/api.html#app.param) and [the tests](https://github.com/expressjs/express/blob/9f019c8c6966736803a65eb4a96d0e7e87e85ede/test/app.param.js) there doesn't seem to be anything that suggests it actually mutates the `req.params` and thus changes it to a non-string. The code is fiddly enough that I could be missing something.

The worrying sign is that there is [a mutation](https://github.com/expressjs/express/blob/7027b37764050c550366e808ea84fee1c58233ed/lib/router/index.js#L372) of `req.params`, and I don't have time to figure out why that's happening, and whether it matters.

The other thing is the express examples folders are unfortunately full of mutations of `req.params` - so perhaps this is a popular pattern. That said, people using TypeScript may wish to avoid a pattern relying on mutation/implicit code anyway, and would welcome type errors warning them of it.

Due to the new role I won't have time to help beyond this reply for a week or two, so if anyone else is interested please do take over. @OliverJAsh you've been working with express's types lately - perhaps you can check my thinking above?

**Comment by timruffles** [comment]
@dougwilson would you be able to instantly confirm whether `req.params` is always presented to the user as an object with all string values? Is there anything apart from an explicit `req.param[x] = someNonStringValue` in user code that'd cause that?

**Comment by dougwilson** [comment]
Hi @timruffles yes, all values are strings by default. Users can use http://expressjs.com/en/4x/api.html#app.param to load in a non-string value (for example, parse an integer, load a model object, etc.), but unless they set that up, everything will be string values.

**Comment by dougwilson** [comment]
So, I also just finished reading you much larger comment right above your mention, so I think perhaps I can shed some extra light:

> The good sign is from the docs and the tests there doesn't seem to be anything that suggests it actually mutates the req.params and thus changes it to a non-string. The code is fiddly enough that I could be missing something.

That's correct, there is nothing in Express (not even a setting) that will make a value of `req.params` object be anything other than a string.

> The worrying sign is that there is a mutation of req.params, and I don't have time to figure out why that's happening, and whether it matters.

Basically what that does is a series of stashing and restoring, to support the `app.param('name', fn)` stuff for folks who mutate the `req.params` object within that function. There isn't any actual type changes occurring (it will restore the value to basically prevent invoking someone's model-loading `req.param(name, fn)` `fn` over and over again if they have many routes with the same `:name`, for example.

> The other thing is the express examples folders are unfortunately full of mutations of req.params - so perhaps this is a popular pattern. 

Yea, it was popularized by Express itself in the 3.x and prior era, but it is being downplayed these days, but I'm sure there are people doing it (not sure if they would really be Typescript users, though).

I hope these responses help :) !

**Comment by andy-ms** [comment]
Based on these responses, I would recommend changing the test to use `=== "0"`.

**Comment by timruffles** [comment]
@dougwilson really kind of you to provide such a detailed answer! Thanks!

File: types/express-serve-static-core/index.d.ts [hunk 1]
```diff
@@ -440,7 +440,10 @@ interface Request extends http.IncomingMessage, Express.Request {
 
     method: string;
 
-    params: any;
+    params: {
+        [namedParameter: string]: string;
+        [captureGroup: number]: string;
+    };
```
Comment (OliverJAsh) [inline types/express-serve-static-core/index.d.ts]: I thought we wouldn't need the `captureGroup: number` signature, because all object keys are strings?

Comment (19majkel94) [inline types/express-serve-static-core/index.d.ts]: https://expressjs.com/en/api.html#req.params

Comment (OliverJAsh) [inline types/express-serve-static-core/index.d.ts]: But all JavaScript objects only accept strings as keys? Number key lookups would be coerced into strings, e.g. `foo[1] === foo['1']`

Comment (19majkel94) [inline types/express-serve-static-core/index.d.ts]: I think that `Array` is an object but you can use numbers as index keys 😉 
You can check in the express source code what the req.params object really is.

**Comment by timruffles** [comment]
Was simply for documentation.

**Comment by timruffles** [comment]
That said, wonder if that's actually unhelpful? I can't think of a case
where TS would get confused off the top of my head (e.g for ... in,
Object.keys would all be string), but for a minor documentation benefit
it's probably still not worth it.

File: types/express-serve-static-core/index.d.ts (hunk 1 above)
Comment (19majkel94) [inline types/express-serve-static-core/index.d.ts]: @timruffles @OliverJAsh 
`req.params` is a normal object, not an array but when the route is wildcard (`/*`) the keys are numbers so you can do `req.params[0]`:

2017-07-19 12_41_27-server js test visual studio code

So we can't enforce people to use `["0"]` bracket notation.

Comment (OliverJAsh) [inline types/express-serve-static-core/index.d.ts]: @19majkel94 Numeric lookups would still work without the the numeric key signature, presumably because TypeScript knows the key will be coerced into a string:

``` ts
{
    const params: {
        [namedParameter: string]: string;
        // [captureGroup: number]: string;
    } = {};

    const v2 = params.foo;
    const v1 = params[1]; // no error
}
```

Comment (19majkel94) [inline types/express-serve-static-core/index.d.ts]: @OliverJAsh Thanks, good to know. So `[captureGroup: number]` is only required for arrays? Or it's currently unused by the language?

It's weird but this example has no error too:
```ts
const a: number[] = [1, 2, 3]
a["0"] = 0
a["five"] = "five" // no error
```

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.
