### ISSUE TITLE
Property 'dispose' does not exist on type 'Material | Material[]'

### ISSUE THREAD

**Issue by DonatoTotalSim** [DefinitelyTyped/DefinitelyTyped#26584]
I have a angular 6.0.5 running three.

All was working with three version 0.89.0 and @types/three version 0.84.3

I have updated to three version 0.93.0 and @types/three version 0.92.5

and everything is now broken. I get the following errors:

    Property 'dispose' does not exist on type 'Material | Material[]'.

    Property 'dispose' does not exist on type 'Material[]'.

and

    Property 'clippingPlanes' does not exist on type 'Material | 
    Material[]'.
    Property 'clippingPlanes' does not exist on type 'Material[]'.

and

    Property 'clippingPlanes' does not exist on type 'Material | 
    Material[]'.

    Property 'clippingPlanes' does not exist on type 'Material[]'.

and

    Argument of type '{ shading: Shading; side: Side; shininess: number; 
    color: number; transparent: true; opacity: num...' is not assignable 
    to parameter of type 'MeshPhongMaterialParameters'.

    Object literal may only specify known properties, and 'shading' does 
    not exist in type 'MeshPhongMaterialParameters'.
    my guess is that types and library are not compatible. Does anybody know how to fix this mess?

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
