### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by ypresto**
Fixes test failures in https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/201613345
It fails with below log:

```
Must specify "lib", usually to `"lib": ["es6"]` or `"lib": ["es6", "dom"]`.
```

#### Removing gaea-model

gaea-model has same error.
I found it has `"typings":` property in package.json since beginning of commit history while investigating.
Also, it seems part of the application (`gaea-editor`) and is not actual library.

#### Fixes react-css-modules

Testing react-css-modules fails on local:

```
Error in react-css-modules
Command failed: node /Users/yuya/github/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.0/node_modules/typescript/lib/tsc.js

../react/index.d.ts(171,34): error TS1005: ',' expected.
../react/index.d.ts(172,34): error TS1005: ',' expected.

Package compiles in TypeScript 2.1 but not in 2.0.
You can add a line '// TypeScript Version: 2.1' to the end of the header to specify a new compiler version.
```

----

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by zhengbli** [comment]
👍
