### PR TITLE
Update webgl-ext types to work with TS2.7+

### LINKED ISSUE #29897: [webgl-ext] error TS2430: Interface 'WebGLRenderingContext' incorrectly extends interface 'WebGLRenderingContextBase'
- [x] I tried using the `@types/webgl-ext` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @zenmumbler 

Here's a StackOverflow post that has the relevant information: https://stackoverflow.com/questions/52846622/error-ts2430-interface-webglrenderingcontext-incorrectly-extends-interface-w

### PR DESCRIPTION
**Pull request by zenmumbler**
* The previous commit dated from the TS 1.6 era and does not compile on TS 2.7+.
* The TS default lib now includes most of the extensions and such interfaces that are now built-in have been removed from here.

__BREAKING__: All interface names now use snake_case names like the built-in ones
__BREAKING__: Now requires TS 2.7 or newer

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This PR changes an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29897
- [x] Increase the version number in the header if appropriate. (Not there to begin with)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (Already there)

Fixes #29897

### CODE REVIEW

**Comment by zenmumbler** [comment]
BTW, a massive merge here caused GH to include some commits from 2015 (as that was the last time I updated my local fork 🤪), only the commits marked as verified are new. I also minimised some comments from that time that GH "helpfully" copied over.

**Review by rbuckton — APPROVED** [review]
