### PR TITLE
[jasmine] Add aliases for renamed interfaces

### PR DESCRIPTION
**Pull request by devoto13**
This adds almost (besides nullability of some fields, which I believe shouldn't be a problem in practice) backward compatible aliases for the interfaces, which were renamed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52004. As it [turned out](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52004#issuecomment-842171031) the change was disruptive for people using custom reporters and adding backward-compatible aliases should make upgrading easier.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52004#issuecomment-842171031
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by devoto13** [comment]
Testing this change against https://github.com/bcaudan/jasmine-spec-reporter, I still get 4 errors:

```
src/display/execution-display.ts:14:9 - error TS2345: Argument of type '{ id: string; description: string; fullName: string; duration: null; properties: null; }' is not assignable to parameter of type 'CustomReporterResult'.
  Type '{ id: string; description: string; fullName: string; duration: null; properties: null; }' is missing the following properties from type 'CustomReporterResult': failedExpectations, deprecationWarnings, status, passedExpectations, pendingReason

 14         {
            ~
 15           id: 'bar',
    ~~~~~~~~~~~~~~~~~~~~
...
 19           properties: null,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 20         },
    ~~~~~~~~~

src/display/execution-display.ts:117:13 - error TS2739: Type '{ description: string; fullName: string; id: string; properties: null; duration: null; }' is missing the following properties from type 'CustomReporterResult': failedExpectations, deprecationWarnings, status, passedExpectations, pendingReason

117       const topLevelSuite: CustomReporterResult = {
                ~~~~~~~~~~~~~

src/execution-metrics.ts:37:5 - error TS2322: Type 'string | number' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

37     this.seed = runDetails.order.seed
       ~~~~~~~~~

src/spec-reporter.ts:127:5 - error TS2739: Type '{ description: string; failedExpectations: { actual: string; expected: string; matcherName: string; message: string; passed: false; stack: any; }[]; fullName: string; id: string; duration: null; properties: null; }' is missing the following properties from type 'CustomReporterResult': deprecationWarnings, status, passedExpectations, pendingReason

127     return {
        ~~~~~~~~
128       description: 'Non-spec failure',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
142       properties: null,
    ~~~~~~~~~~~~~~~~~~~~~~~
143     }
    ~~~~~


Found 4 errors.
```

The one about `seed` is caused by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53431 and probably best to be fixed in the library.

The other three errors are because of the optionality of the fields in the mentioned interfaces. I'll need to look more into the `jasmine-spec-reporter` to understand what is the best course of action here. Probably make `CustomReporterResult` fully backwards compatible by making these fields optional as before.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by chivesrs** [comment]
I think this is a good starting point just to fix up some of the errors, the rest could be done in a second PR.

**Review by chivesrs — APPROVED** [review]

**Comment by chivesrs** [comment]
Ready to merge
