### ISSUE TITLE
@types/mongoose excludes explicitly defined 'id' property from document schema types

### ISSUE THREAD

**Issue by lincolnthree** [DefinitelyTyped/DefinitelyTyped#46066]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**

First, thanks for these typings, they are hugely helpful. I did find an issue that is somewhat problematic for custom schemas.

Using the latest `@types` definitions, currently version `@types/mongoose@5.7.30` (This previously worked in `@types/mongoose": "^5.7.21`):

Define any schema with an 'id' property, create a Model object with the appropriate types, then `create()` it or query via `lean()`. The 'id' field will result in compilation errors when attempting to call `Model.create({...})`, or use the result of `Model.findOne().lean()`

Example code:

```

import mongoose, { Mongoose } from 'mongoose';
import { Model } from 'mongoose';
import { Document } from 'mongoose';

export interface ExampleSchema {
  id: string;
  number: number;
}

const schema = new Schema<ExampleSchema>(
  {
    id: { type: String, required: true, unique: true },
    number: { type: Number, required: true },
  }, {
  timestamps: { createdAt: 'created', updatedAt: 'updated' },
  strict: true,
  id: false // <--- This has no effect, true or false
});

export function ExampleSchemaModelInitializer(mongoose, tableName = 'example_table') {
  return mongoose.model(tableName, schema) as Model<ExampleSchema & Document>;
}

export const ExampleSchemaModel = ExampleSchemaModelInitializer(mongoose);

ExampleSchemaModel.create({
  id: 'asdfasdf', // <---- Error here (see below)
  number: 1
});

const result = await ExampleSchemaModel.findOne().lean();
console.log(result.id); // <---- Error 2 here (see below)
```

Error 1:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ id: string; number: number; }' is not assignable to parameter of type 'Pick<{ number: number; _id: any; } & { _id: any; }, "number"> & { _id?: any; }'.
      Object literal may only specify known properties, and 'id' does not exist in type 'Pick<{ number: number; _id: any; } & { _id: any; }, "number"> & { _id?: any; }'.ts(2769)
index.d.ts(3277, 5): The last overload is declared here.
```

Error 2:
```
Property 'id' does not exist on type 'Pick<ExampleSchema & Document, KeysOfAType<Pick<ExampleSchema & Document, "number" | "_id">, number>>'.ts(2339)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The `id` property should not be excluded from result types if it is explicitly defined.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
 mongoose                               ^5.9.22 
 @types/mongoose                 ^5.7.30 
 @types/node                          ^14.0.21 

node -v
v12.13.0 (I know it doesn't match the `@types/node` types, not related to this issue afaik)


```

If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/xxxx` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....
//                   @horiuchi>
//                 @lukasz-zak 
//                 @jendrikw
//                 @ethanresnick
//                 @vologa 
//                 @jussikinnula 
//                 @ondratra 
//                 @alfirin
//                 @idandrd
//                @various89
//                @Fazendaaa
//                @NormanPerrin
//                @stablio
//                @emmanuelgautier
//                 @frontendmonster
//                @mingchen
//                @penumbra1
//                 @orblazer
//                 @HughKu
//                @niuware
//                 @vladmel1234
//                @jloveridge
//                 @grimmer0125
//                 @richarddd
//                @ToucheSir
//                 @borfig
//                @dinodeSimon
//                 @anthony-kenikh
//                 @iamchathu
//                @lkho
//               @tomyam1
//                 @nephix
//                @rlaace423
//                 @ChazEpps
//                @avaly
//                @JanNemcik
//                 @cl3dson
//                 @richardsimko
//                @ith
//                @jeremyben
//                 @andreialecu
//                 @tHBp

If you do not mention the authors the issue will be ignored.

**Comment by lincolnthree** [comment]
Originally filed here: https://github.com/Automattic/mongoose/issues/9228

**Comment by andreialecu** [comment]
While this may be an issue there are also some potential issues with this approach.

1) Every document must have an `_id` field. 
> In MongoDB, each document stored in a collection requires a unique _id field that acts as a primary key. If an inserted document omits the _id field, the MongoDB driver automatically generates an ObjectId for the _id field.

2) `.id` is just a virtual property added by mongoose to cast the `_id` to a string.

3) You can use `_id` in `.create({ _id: "yourstring" })` and also define `_id` as a `string` schema property. This is a better practice, as your custom string id can be the primary key of the collection.

My suggestion is to define your schema like:

```ts
  {
    _id: { type: String, required: true, unique: true },
    number: { type: Number, required: true },
  },
```

And to insert like `.create({ _id: "foo", number: 123 })`. Your returned document will have the virtual `.id` on it.

Also note that `.lean()` does not include `.id` in the result because lean does not process virtuals by default, see below for workarounds:
https://github.com/Automattic/mongoose/issues/3366
https://www.npmjs.com/package/mongoose-lean-id

It's likely mongoose itself will get confused by what you're trying to do.

Is there a reason you cannot use `_id`?

**Comment by lincolnthree** [comment]
Hi @andreialecu, thanks for your thoughts about this! 

Please see my responses to your questions/suggestions:

**"1. Every document must have an _id field."** --- Yes, they do. They also have a business 'id' field which is a GUID. The example I provided is a minimal reproduction designed to highlight the issue, and does not represent our full schema.

**"2. .id is just a virtual property added by mongoose to cast the _id to a string."** --- Not if it's explicitly defined in the schema, like we've done. Mongoose only adds the virtual ID property if you do not disable this feature. We have disabled this feature. See https://mongoosejs.com/docs/guide.html#id 

`id` is not a reserved word in Mongoose, and is treated as any other field name if 'id' virtuals are disabled. See https://mongoosejs.com/docs/api.html#schema_Schema.reserved and meets all criteria for a valid MongoDB property/field name, see https://docs.mongodb.com/manual/core/document/#field-names.

**"3. You can use _id in .create({ _id: "yourstring" }) and also define _id as a string schema property."** --- Yes, we could have done this, but we chose to have both a unique mongoid and business UUID for several reasons. Both are useful in different scenarios. 

Perhaps most importantly, this system is already built, and interacts with multiple outside systems. Additionally and independently, `id` does not reveal the underlying implementation of the database.

We could have converted the `_id` to an `id` field everywhere we expose the document, but then we would have missed some of the built-in features of the mongodb `_id` functionality, like built in document creation order and time-stamping, plus the optimization mongo has for its own ids in doing certain queries. 

But, this probably doesn't need to get into a debate over which ID strategy to use. The point is what we're doing is valid :)


**"4. Also note that .lean() does not include .id in the result because lean does not process virtuals by default"** ---  Correct, but it does include the non-virtual 'id' defined in our schemas/documents :)

**"5. It's likely mongoose itself will get confused by what you're trying to do."** --- It works fine. We have over 60 collections sharded across multiple databases, with millions of records, complex aggrigation pipelines, and have defined virtual properties for population using this ID property, etc etc.

**"6. Is there a reason you cannot use _id?"** --- Yes, we would have to re-write our entire system, updating every record in the database to transition from `id` to `_id` as a GUID, and either make modifications to all systems that communicate with it, or implement facades everywhere they do", and this change was introduced in a recent update to the `@types/mongoose` package, which is why I reported the issue to you here :)

**Comment by andreialecu** [comment]
Thanks for adding details, that makes it clearer.

I'm the author of the `.create()` types, so for those you can work around the issue with:

```ts
type WithId<T> = T & { id: string };

.create<WithId<ExampleSchema>>({ ... }
```

For `.lean()`, I'm not sure what the problem is as I haven't touched those.

**Comment by lincolnthree** [comment]
@andreialecu Thanks! I'll give that a shot as a workaround, but likely will just put a hold on upgrading until its resolved as what's there seems to work for us (and there would be *many* places to update). 

Glad this reached at least one of the right people. Wasn't sure who to include, as there were many authors listed in the `.d.ts` file. If you know who to speak with regarding `lean()` I'd be happy to provide any information required.

**Comment by andreialecu** [comment]
Which version were you using, back when this worked? Note that pre 5.7.21 (I think) `create` had no types, so essentially it was `.create(doc: any)`.

You can still get that behavior by using `.create<any>(doc)`.

**Comment by lincolnthree** [comment]
Oh hm. Looks like I forgot to paste that version in. My apologies. The version that works appears to be: `"@types/mongoose": "^5.7.21"`

**Comment by lincolnthree** [comment]
Now that you mention it, however. I believe the '.lean()' change came down a few versions prior. I don't know which one introduced it.

**Comment by MCarballido** [comment]
I am having the same issue with `.lean()` even with `@ŧypes/mongoose:5.7.21`. I had to downgrade all the way to `5.5.18` to make it work for `.lean()` returns `any` in that version.

**Comment by lincolnthree** [comment]
That sounds about right. I think the best possible compromise here would be to return the Schema type as defined. If really desired, it could demote the ID and Version fields to optional, but I don't see anything wrong with just returning the type as users have it defined. It's what they'd expect, IMO.

**Comment by lincolnthree** [comment]
Just checking in. This issue is still blocking us from upgrading. The typings file is fairly ... complex. Could you perhaps give some tips for what to change so I could send a PR?

**Comment by andreialecu** [comment]
Unfortunately I don't see an easy way to bring `.id` back here simply because the logic tries to exclude all mongoose added virtuals, of which `.id` is one of them. It's not possible to differentiate where it comes from.

However there is a workaround:

```ts
export interface ExampleSchema {
  id: string;
  number: number;
}

const result = await ExampleSchemaModel.findOne().lean<ExampleSchema>(); // override via type param
console.log(result.id); // should work now
```

**Comment by lincolnthree** [comment]
I think I figured it out. PR incoming.

**Comment by lincolnthree** [comment]
@andreialecu Would you mind taking a look at the PR above? I ...believe... I've taken all the necessary precautions and this should be backwards compatible. Tested it in my code and it does resolve the issue.

**Comment by andreialecu** [comment]
I took a quick look, the problem with that approach is that usually documents are defined like:

```ts
interface Submission extends mongoose.Document {
  name: string;
  fields: Record<string,string>;
}
```

And `mongoose.Document` already has `id?: any`. So your change will bring an `.id` to `.lean()` in every case, including the one above, which is probably incorrect. You can add a test to verify.

**Comment by lincolnthree** [comment]
Interesting, thanks for looking. I've put some more thought into this and come up with some, "probably controversial" thoughts. Apologies in advance if any of this comes across as indelicate --- I'm just trying to convey hopefully helpful thoughts. 

**What I'm proposing at allows default flexibility for more use-cases without restricting types to less than what users defined. And it also effectively resolves the breaking change that occurred when this new lean() typing was added back in `5.5.19+`, in a way that should not cause any compilation errors in the reverse direction (when people upgrade to this version).**

I do agree that the `id` optional property leaking through `.lean()` would be a side-effect of this change. That said, the returned `id?:...` property would be optional, and it does hint that it might not be defined, and anywhere it's specifically required in a type, it would cause a compile error to attempt an assignment (unless it's bypassed via direct assignment/access, e.g. `const id = leanResult.id` would work, but `const myVar:{ id } = leanResult` would not).

Example:
```
interface ModelWithoutDeclaredId extends mongoose.Document { 
}
var ModelWithoutDeclaredIdInSchema = mongoose.model<ModelWithoutDeclaredId>("ModelWithDeclaredId", {} as any);
ModelWithoutDeclaredIdInSchema.create({ id: 'a' }).then(created => { 
    console.log(created.id); 
});
var withoutId: Promise<ModelWithoutDeclaredId | null> = ModelWithoutDeclaredIdInSchema.findOne().exec();
var withoutIds: Promise<ModelWithoutDeclaredId[]> = ModelWithoutDeclaredIdInSchema.find().exec();
var leanWithoutId = ModelWithoutDeclaredIdInSchema.findOne().lean().exec();
var leanWithoutIds = ModelWithoutDeclaredIdInSchema.find().lean().exec();
leanWithoutId.then(found => {
    if (found) {
        var id = found.id; // <-- this is not a compile error
        // $ExpectError
        var obj: { id: any } = found; // <--- this is a compile error
    }
});
```

Additionally, but related... the fact that `MongooseDocument` extends `MongooseDocumentOptionals`  at all is extremely problematic, since it introduces the virtual/synthetic `id?:...` property in ALL interfaces, including 'create()', and other places where it has no effect, and also introduces this type on the user's schema (if they extend from mongoose.Document). Meaning you, the author of 'lean()'`s typings, have to subsequently remove it.

What you've done in creating lean's typings, and removing the 'id' property (along with other MongooseDocument schema definitions) is actually a reasonable (for some use cases) fix for that root issue, but you shouldn't have to do it, and users shouldn't be extending 'mongoose.Document' in the first place.

The default extension of `MongooseDocumentOptionals` in the core typings is basically so broken conceptually that leaking the virtual 'id' when it's not actually provided would essentially be par for the course.

Slightly off topic... my personal sentiment on this topic of inheriting from mongoose.Document (which is probably irrelevant since I understand that's how people have been doing things for a while) --- I'd argue that it is probably not a great object oriented design practice (it's fine to combine that Interface with your Schema definitions in function types and return value types, but I don't think it should be done at the root definition/schema level since it causes all kinds of issues with having to remove those types again later down the line in the typings, and prevents you from using your own type definitions as plain (non mongoose) objects, without going through a lot of hoops.) It's easy to extend an interface... not to easy to ... un-extend an interface, and this is a direct symptom of that.

That summarized, in short, I think users should get what they ask for. And if you define an 'id' in the schema, you should get an 'id'. If you extend `mongoose.Document` in your base Schema interface, you should get ALL those values back since you've essentially defined them in your DB schema. Methods possibly excluded, but any properties should remain.

Additionally, off topic/unrelated: I noticed the lean method also has the problem where when `.lean(false)` is passed, it still removes the mongoose types, which is incorrect. So, while this might be 'also slightly incorrect', I don't know that it's really ever going to be 100% correct without forcing users to address their type definitions.

That said, I'm looking for a way to remove the `MongooseDocumentOptionals` type inheritance in `MongooseDocument` and put it in the appropriate place instead. But I think this PR would be a good, non-breaking fix for the issue introduced in `5.5.19+`

**Comment by andreialecu** [comment]
> I do agree that the id optional property leaking through .lean() would be a side-effect of this change. That said, the returned id?:... property would be optional, and it does hint that it might not be defined, and anywhere it's specifically required in a type, it would cause a compile error to attempt an assignment (unless it's bypassed via direct assignment/access, e.g. const id = leanResult.id would work, but const myVar:{ id } = leanResult would not).

In that case, your PR can be much simpler and simply add `id` back without doing all the extra fancy logic. Because that's essentially what it does anyway 🙂 

However, the workaround I posted above seems simpler to implement, especially considering that having an `id` field actually persisted to documents should be extremely rare among users. 

Note that actually adding it back can result in either of these issues:
* a new user typing `.i` in VS Code will see it there and expect it to exist, but it would not be populated. This can result in additional support tickets being raised, and more confused users.
* someone already using a workaround for this will get a conflict and have to fix his code again

One thing to note is that all the virtuals from `MongooseDocument` do need to be excluded, otherwise you get all sorts of methods and unrelated properties on the result from `.lean()`.

Unfortunately Mongoose cannot be 100% translated into typescript types, as it has a lot of quirks like this, so unless someone creates a TypeScript native version at some point, we have to live with workarounds.

**Comment by andreialecu** [comment]
> Additionally, but related... the fact that MongooseDocument extends MongooseDocumentOptionals at all is extremely problematic, since it introduces the virtual/synthetic id?:... property in ALL interfaces, including 'create()', and other places where it has no effect,

Also note that all the virtuals and other properties defined on `MongooseDocument` are properly excluded from everywhere using similar logic to `.lean()` (this includes `.create()` and others).

Additionally, it's important to extend from `mongoose.Document` in order to retain methods such as `doc.save()` and others. If you look at all the tests, you will see they all extend from it. If you're curious what breaks without extending from it, feel free to play with it.

**Comment by lincolnthree** [comment]
```
someone already using a workaround for this will get a conflict and have to fix his code again
```

Hmm. How would that be the case? In what scenarios is this not backwards compatible? The compilation error scenario I referenced is _existing_ functionality.

```One thing to note is that all the virtuals from MongooseDocument do need to be excluded, otherwise you get all sorts of methods and unrelated properties on the result from .lean().```

Right, I agreed with you on that (never suggested otherwise.) All I'm suggesting is that removing  `MongooseDocumentOptionals` is incorrect.

```Unfortunately Mongoose cannot be 100% translated into typescript types, as it has a lot of quirks like this, so unless someone creates a TypeScript native version at some point, we have to live with workarounds.````

Agreed, and I think the original change to `lean()` to remove the `id` is just as problematic, and actually introduced compilation and code error changes. Anyone trying to upgrade from an old enough version (of this major version) will have to change their code.

This PR reverses that breaking change.

**Comment by andreialecu** [comment]
Was there an explicit change to remove `id`? Can you link the PR?

The version you were using prior to this simply had `.lean()` typed as `any` I think.

**Comment by lincolnthree** [comment]
> Was there an explicit change to remove `id`? Can you link the PR?
> 
> The version you were using prior to this simply had `.lean()` typed as `any` I think.

Yes, that's correct. Hence the ability to use and assign the 'id' property (which as we already discussed, is a valid schema document per mongodb and mongoose documentation) from `lean()` documents was removed at this point.

**Comment by andreialecu** [comment]
Someone took time to convert a type from untyped (`any`) to something that is useful. It's simply just a side-effect of how typescript and mongoose cannot 100% match in types. Sometimes workarounds are needed, it is what it is.

If you want it to be typed as `any` again, you can do a find and replace in all files:

* find `.lean(`
* replace with `.lean<any>(`

Problem solved :)

**Comment by lincolnthree** [comment]
> Also note that all the virtuals and other properties defined on `MongooseDocument` are properly excluded from everywhere using similar logic to `.lean()` (this includes `.create()` and others).

I somewhat agree with that. Those places do exclude the virtuals, but they also don't stop you from using `id` either. There are also places where `id` virtual leaks when even when it is not enabled. (e.g. in `create()`):

```
const result = await MyModel.create()
result.id // <--- this field exists even if it. has not been defined on the user's schema, even if virtuals are disabled.
```

Anywhere you create a new Model, you're going to get an 'id' on the type even if it's disabled, so this PR seems in line with that precedent.

> 
> Additionally, it's important to extend from `mongoose.Document` in order to retain methods such as `doc.save()` and others. If you look at all the tests, you will see they all extend from it. If you're curious what breaks without extending from it, feel free to play with it.

I disagree entirely. You do not need to extend from `mongoose.Document` to retain those methods. The definitions for those methods are automatically added by the typings (just like the methods are automatically added by mongoose). It is unnecessary and problematic to do so when creating a Model/Schema definition.

> 
> Note: I did not add the `.lean()` typings but in this case I don't see anything wrong with them.

Ahh gotcha, I misunderstood! 

> Someone took time to convert a type from untyped (any) to something that is useful. It's simply just a side-effect of how 
> typescript and mongoose cannot 100% match in types. Sometimes workarounds are needed, it is what it is.

You're not wrong. I'm just trying to make it a non-breaking change so people don't have to do that. It's still useful and provides type information.

**Comment by lincolnthree** [comment]
Also thank you for the tip about `<Type>lean()`, that's a very simple workaround to resolve the compilation errors introduced with the original change to this method. I should have deduced we could do the same thing there.

**Comment by andreialecu** [comment]
> I disagree entirely. You do not need to extend from mongoose.Document to retain those methods. The definitions for those methods can be added when creating a model. It is unnecessary and problematic to do so prior to Model instantiation.

Unless you want to rewrite the entire mongoose typings, the above affirmation is incorrect.

> Anywhere you create a new Model, you're going to get an 'id' on the type even if it's disabled, so this PR seems in line with that precedent.

The difference here is that **the default is to have an `.id`** on documents, but the `.id` does not show up by default in `lean()`. I'd rather not repeat again that this cannot really be expressed in TypeScript properly, because whether it exists or not depends on a configuration setting in Mongoose. 🙂 

Also I'm not sure what to think of the PR, especially as there is a type override which was created exactly for this purpose, and which I pointed out several times already.

For users stumbling upon this issue, I'm going to share the workaround here again:

```
export interface ExampleSchema {
  id: string;
  number: number;
}

const result = await ExampleSchemaModel.findOne().lean<ExampleSchema>(); // override via type param
console.log(result.id); // should work now
```

**Comment by lincolnthree** [comment]
> I'm the author of the `.create()` types, so for those you can work around the issue with:
> 
> ```ts
> type WithId<T> = CreateQuery<T> & { id: string };
> 
> .create<WithId<ExampleSchema>>({ ... })
> ```
> 

Also, just a heads up, the above does not appear to work. Create still removes the `id` property unless I am doing something wrong.

**Comment by lincolnthree** [comment]
> > I disagree entirely. You do not need to extend from mongoose.Document to retain those methods. The definitions for those methods can be added when creating a model. It is unnecessary and problematic to do so prior to Model instantiation.
> 
> Unless you want to rewrite the entire mongoose typings, the above affirmation is incorrect.

The example I provided in my last reply shows this working. How is it incorrect? (Seriously if I'm missing something I want to know.)

Here it is again. I renamed the interface for disambiguity:

```
interface TypeWithOptionalDeclaredId { 
    id?: string 
}
var ModelWithOptionalDeclaredIdInSchema = mongoose.model<TypeWithOptionalDeclaredId & mongoose.Document>("ModelWithOptionalDeclaredId", {} as any);
ModelWithOptionalDeclaredIdInSchema.create({ id: 'a' }).then(created => { 
    console.log(created.id); 
    created.save() // typing exists and works just fine.
});
```

> > Anywhere you create a new Model, you're going to get an 'id' on the type even if it's disabled, so this PR seems in line with that precedent.
> 
> The difference here is that **the default is to have an `.id`** on documents, but the `.id` does not show up by default in `lean()`. I'd rather not repeat again that this cannot really be expressed in TypeScript properly, because whether it exists or not depends on a configuration setting in Mongoose. 🙂

I'll grant you that, except if the user has specified 'id' in their schema, in which case the virtual 'id' is _not_ added. But I don't think we're going to agree on this point, as I think we both agree it is a fundamental flaw in the typings as they stand and would require a rewrite of much of it.

> Also I'm not sure what to think of the PR, especially as there is a type override which was created exactly for this purpose, and which I pointed out several times already.

All I'm overriding is the 'id', which is, consequently, the only actual schema property that receives special treatment in the typings (it is the only property in `MongooseDocumentOptionals`.

**Comment by lincolnthree** [comment]
Okay, I think I just realized part of where we're having a disconnect....

**Comment by lincolnthree** [comment]
It's a fundamental issue with the typings, again...

This line:
```var ModelWithOptionalDeclaredIdInSchema = mongoose.model<TypeWithOptionalDeclaredId & mongoose.Document>("ModelWithOptionalDeclaredId", {} as any);```

Should really be:
```var ModelWithOptionalDeclaredIdInSchema = mongoose.model<TypeWithOptionalDeclaredId>("ModelWithOptionalDeclaredId", {} as any);```

I really don't know why extending `mongoose.Document` is even necessary if nothing works without it. I think I conceptually don't grasp that aspect of the typings.

**Comment by andreialecu** [comment]
> Also, just a heads up, the above does not appear to work. Create still removes the id property unless I am doing something wrong.

```ts
type A<T> = CreateQuery<T & { id: string }>; // wrong
type B<T> = CreateQuery<T> & { id: string }; // ok
```

Make sure you didn't wrap your `id` with `CreateQuery`.

> I really don't know why extending mongoose.Document is even necessary if nothing works without it. I think I conceptually don't grasp that aspect of the typings as this could be added by the typings as part of the Model creation step above.

`mongoose.model<TypeWithOptionalDeclaredId & mongoose.Document>` does work in *some* cases. But there are methods that specifically have parameters that take a `mongoose.Document`. In that case you cannot pass your type directly.

Here's an example for hooks: https://github.com/lincolnthree/DefinitelyTyped/blob/mongoose-46066/types/mongoose/index.d.ts#L1005

It needs to disambiguate between various types. `Query`, `Document`(!), `Aggregate`, `Model`, and others. You cannot use most methods unless you extend Document, or you have to add even uglier workarounds to be able to do it.

**Comment by lincolnthree** [comment]
> Make sure you didn't wrap your id with CreateQuery.

Hmm, checking.

> It needs to disambiguate between various types. Query, Document(!), Aggregate, Model, and others. You cannot use most 
> methods unless you extend Document, or you have to add even uglier workarounds to be able to do it.

Right, but I think there's some conflation with the Schema definition and the Model definition. I'm defining the Schema definition as what is in the database collection/table. The Model/Document definition is the mongoose'ified version of that schema with methods, virtuals, etc.

So: 
```
import { Document, Model, Schema } from 'mongoose';

interface SchemaType { prop: string } // <-- Schema definition

const schema = new Schema<SchemaType>({ 
   prop: String 
}, {
   timestamps: false
});

var ModelType = mongoose.model<SchemaType & Document>('type_collection', schema)  as Model<SetSchema & Document>; // <-- Model definition

```

Note that `ModelType` above is the result of the call to mongoose.model. Which does not take any arguments of the type `SchemaType & mongoose.Document`, 

It has a final type of:

```
var ModelType: Model<SchemaType & Document, {}>
```

So if that's the case, why can't this:
```
  /**
   * Defines a model or retrieves it
   * ....
   */
  export function model<T extends Document>(name: string, schema?: Schema, collection?: string,
    skipInit?: boolean): Model<T>;
```

Be this? The following seems to better describe the actual behavior of the `model()` function. It takes a Type, (and the colleciton name & options) and returns a Typed Model object:
```
  /**
   * Defines a model or retrieves it
   * ....
   */
  export function model<T>(name: string, schema?: Schema, collection?: string,
    skipInit?: boolean): Model<T & Document>;
```


That's essentially the issue I think is at the root of this problem. The `Document` type is being required/enforced at the wrong level of type/Model definition, when it should instead be a _result_ of model creation.

It requires changing about 20 instances of <T> in model to be <T & Document>, but it would resolve the issue. I haven't looked much farther but I don't think it would be a breaking change, either.

**Comment by lincolnthree** [comment]
Note about the above. To make this really consistent over the entire package, many places would need to change to follow this paradigm, but I think it would worth it for the benefit in preservation of type information that allows for solving more complex scenarios like the one in this issue.

**Comment by lincolnthree** [comment]
That said, it also simplifies things significantly:

With Model defined like so:

```
  export function model<T>(name: string, schema?: Schema, collection?: string,
    skipInit?: boolean): Model<T & Document>;

.....

  export var Model: Model<any>;
  interface Model<T, QueryHelpers = {}> extends NodeJS.EventEmitter, ModelProperties {
```

The typings for `create()` (I think...) would look like this, and none of the fancy type manipulation would be required at all:

```
    /**
     * Shortcut for saving one or more documents to the database. MyModel.create(docs)
     * does new MyModel(doc).save() for every doc in docs.
     * Triggers the save() hook.
     */
    create(doc: T, options?: SaveOptions): Promise<T & Document>;
    create(doc: T, callback?: (err: any, res: T[]) => void): Promise<T & Document>;
    create(docs: T[], callback?: (err: any, res: T[]) => void): Promise<(T & Document)[]>;
    create(docs: T[], options?: SaveOptions, callback?: (err: any, res: (T & Document)[]) => void): Promise<(T & Document)[]>;
    create(...docs: T[]): Promise<T & Document>;
```

**Comment by andreialecu** [comment]
What you're proposing may or may not work, I suggest you try it out in the actual repo and see how the test suite reacts. However, it's extremely likely to have huge breaking changes, and it's also likely you're overlooking many other things.

But, like I said, if you want to rewrite the entire mongoose type definition library, please go ahead. 🙂 These types do have various issues and many things that could be done better. I would suggest you get more familiar with them before attempting such a huge undertaking.

I'm sure the `Mongoose` maintainers are looking for native TypeScript types to bundle with the package as well. But again, it's a huge undertaking, and it's often not as simple as you may think at first glance.

**Comment by lincolnthree** [comment]
Yeah, I'm sure it's a huge endeavor, no debate about that! I do think it can be done without breaking changes (I've been testing the refactoring here working in the repo, yes.) 

Also, agreed 100%. I have no illusions as to the simplicity or lack thereof regarding these typings. :)

My background is in Java, and I've spent years (for better or worse) creating ... massive, extensible... APIs in a strictly strongly-typed ecosystem. It's never as simple as you want it to be.

But also not sure how it would be received if I did finish and submit it. I've had limited interactions with the Mongoose team and last I checked they basically said, "not planning on it, not interested." So maybe that's changed. I'd be glad to hear it if that's the case.

**Comment by lincolnthree** [comment]
> > so, just a heads up, the above does not appear to work. Create still removes the id property unless I am doing something wrong.
> 
> ```ts
> type A<T> = CreateQuery<T & { id: string }>; // wrong
> type B<T> = CreateQuery<T> & { id: string }; // ok
> ```



> > Also, just a heads up, the above does not appear to work. Create still removes the id property unless I am doing something wrong.
> 
> ```ts
> type A<T> = CreateQuery<T & { id: string }>; // wrong
> type B<T> = CreateQuery<T> & { id: string }; // ok
> ```
> 
> Make sure you didn't wrap your `id` with `CreateQuery`.

Made sure this was the case. Does not appear to work. `id` is still not in the type. Does not look like this would work given the typings:

`TCreate` is always wrapped in CreateQuery, which, as I understand it will remove the 'id' property again. Maybe I'm still missing something?

```
create<TCreate = T>(doc: CreateQuery<TCreate>, options?: SaveOptions): Promise<T>;
    create<TCreate = T>(doc: CreateQuery<TCreate>, callback?: (err: any, res: T[]) => void): Promise<T>;
    create<TCreate = T>(docs: CreateQuery<TCreate>[], callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<TCreate = T>(docs: CreateQuery<TCreate>[], options?: SaveOptions, callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<TCreate = T>(...docs: CreateQuery<TCreate>[]): Promise<T>;
```

**Comment by andreialecu** [comment]
Indeed, I overlooked that part. Forgot it was wrapped internally. 🤔 

You may need to resort to using `any` via `.create<any>(...)` in this case. Not sure how to fix it otherwise.

**Comment by lincolnthree** [comment]
Hmm, thanks.

I think it could possibly be fixed like so, maybe?

```
    create<TCreate = CreateQuery<T>>(doc: TCreate, options?: SaveOptions): Promise<T>;
    create<TCreate = CreateQuery<T>>(doc: TCreate, callback?: (err: any, res: T[]) => void): Promise<T>;
    create<TCreate = CreateQuery<T>>(docs: TCreate[], callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<TCreate = CreateQuery<T>>(docs: TCreate[], options?: SaveOptions, callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<TCreate = CreateQuery<T>>(...docs: TCreate[]): Promise<T>;
```

I haven't tested this, just using a best-guess via how I think generic types work. Thoughts?

**Comment by andreialecu** [comment]
@lincolnthree that was my first attempt as well, but it doesn't work. The reason why it doesn't work is easier to see if you test it yourself :)

Basically, once you call `.create({ absolutelyAnything: "foo" })`, `TCreate` will take the type of what you passed in and just override the type parameter.

**Comment by lincolnthree** [comment]
Ah yes, of course. Alas... I'll think about it some more when I get some more time. Thanks again for bearing with my thought process.

**Comment by lincolnthree** [comment]
I **think** this might do it:

```
     */
    create<R, TCreate = R & CreateQuery<T>>(doc: TCreate, options?: SaveOptions): Promise<T>;
    create<R, TCreate = R & CreateQuery<T>>(doc: TCreate, callback?: (err: any, res: T[]) => void): Promise<T>;
    create<R, TCreate = R & CreateQuery<T>>(docs: TCreate, callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<R, TCreate = R & CreateQuery<T>>(docs: TCreate, options?: SaveOptions, callback?: (err: any, res: T[]) => void): Promise<T[]>;
    create<R, TCreate = R & CreateQuery<T>>(...docs: TCreate[]): Promise<T>;
```

**Comment by lincolnthree** [comment]
Not sure about side-effects.

**Comment by andreialecu** [comment]
Should be very easy run the test suite and open a PR if it works.

**Comment by lincolnthree** [comment]
Ha good call. Will do. 1 moment.

**Comment by lincolnthree** [comment]
Nope.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
