### PR TITLE
[three] 'webvr-api' is no longer needed.

### PR DESCRIPTION
**Pull request by nakagawa424**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Comment by devpaul** [comment]
Is there a reason to update to TS 2.8? It doesn't appear that any of the types have changed.

**Comment by nakagawa424** [comment]
TS 2.8 lib.dom.d.ts includes type definitions defined in @types/webvr-api.
TS 3.0 definitions are modified and are confliting with @types/webvr-api.

**Comment by efokschaner** [comment]
Hi @nakagawa424 , webvr-api is in an odd place for compatibility at the moment. While it is true it is not really needed for projects using typescript >= 2.8 I'm not sure whether it's time to drop support for versions < 2.8. I'm genuinely not sure, so if you have reasons to recommend it I'm listening. My instinct here is to be cautious and keep the majority of existing code working while we figure out how to proceed. On that note, I've tried to start some discussion here https://github.com/Microsoft/TypeScript/issues/26038#issuecomment-416083480 , maybe you'd like to have a look at those comments and can offer some thoughts?

**Comment by nakagawa424** [comment]
TS <2.8 users can explicitly add dependencies on @types/webvr-api.

**Comment by devpaul** [comment]
I was experimenting w/ A-Frame types, which use the Three types, and found that TypeScript 3+ types interfere w/ Three's usage. I'll see if I can find time to work up an example, but given that I'd recommend removing the reference to WebVR types.

Assuming most people who are up-to-date w/ three types would also be using up-to-date TypeScript compilers then it follows that this change should benefit most people. Users using < TS 2.8 can add WebVR types to restore compatibility.

**Comment by nakagawa424** [comment]
'webvr-api' is updated, so now:
@types/webvr-api@0.0.35 is incompatible with TS 2.8
@types/webvr-api@0.0.34 is incompatible with TS 3.0

**Comment by efokschaner** [comment]
@nakagawa424 are you certain that it no longer works with 2.8?
@RyanCavanaugh states here that it will work with 2.8: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28668#issuecomment-420314443

**Comment by nakagawa424** [comment]
[test-ts2.8.tar.gz](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2377658/test-ts2.8.tar.gz)
[test-ts3.0.tar.gz](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2377659/test-ts3.0.tar.gz)

tar x, then npm i

**Comment by nakagawa424** [comment]
> @nakagawa424 are you certain that it no longer works with 2.8?
> @RyanCavanaugh states here that it will work with 2.8: [#28668 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28668#issuecomment-420314443)

"(which I believe is 2.2 or 2.6)", not 2.8

**Review by efokschaner — APPROVED** [review]

**Comment by sandersn** [comment]
@efokschaner noted. @DanielRosenwasser this might be something we need to document in the handbook or with a blog post.

**Comment by adumesny** [comment]
so running typescript@~2.5.3 and adding @types/webvr-api didn't work for me. VS Code does find VRDisplay, but compiling gives me this error still. weird...

ERROR in node_modules/@types/three/three-core.d.ts(7800,18): error TS2304: Cannot find name 'VRDisplay'.

**Comment by nakagawa424** [comment]
> so running typescript@~2.5.3 and adding @types/webvr-api didn't work for me. VS Code does find VRDisplay, but compiling gives me this error still. weird...
> 
> `ERROR in node_modules/@types/three/three-core.d.ts(7800,18): error TS2304: Cannot find name 'VRDisplay'.`

[test-ts2.5.tar.gz](https://github.com/DefinitelyTyped/DefinitelyTyped/files/2436307/test-ts2.5.tar.gz)

no problem for me
