### PR TITLE
React:  SyntheticEvent.target.value should be generic on T

### PR DESCRIPTION
**Pull request by pzavolinsky**
When handling an event (e.g. `onChange`) it should be possible to access the changed value through `e.target.value`. 

The following example (adapted from [React's documentation](https://facebook.github.io/react/docs/forms.html#the-textarea-tag)) illustrates the scenario:

```jsx
class EssayForm extends React.Component<{}, { value: string }> {
  constructor(props:{}) {
    super(props);
    this.state = {
      value: 'Please write an essay about your favorite DOM element.'
    };
  }
  render() {
    return <textarea
      value={this.state.value}
      onChange={e => this.setState({value: e.target.value})}
    />;
  }
}
```

This currently fails in the `setState` line with:
> error TS2339: Property 'value' does not exist on type 'EventTarget'.

----

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react/docs/forms.html#the-textarea-tag
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Tests failed I'm afraid - could you take a look?

**Comment by pzavolinsky** [comment]
Hi @johnnyreilly , I'm not sure this failure relates to my change. The errors are a missing module in `draft-js` and broken declaration in `react-gravatar` and I haven't changed either of them.

I'm currently trying to run every single test locally without much success (lots of unrelated network errors like `connect ECONNREFUSED 151.101.92.162:443`).

Is there a way I could run only the tests for the modules that are failing?

**Comment by johnnyreilly** [comment]
Hi @pzavolinsky,

I'm a little confused - the build is passing. This suggests that there's something in your PR that is at issue... I'm afraid I can't really look at this and give anymore insight as I'm on my phone.

**Comment by pzavolinsky** [comment]
>  ...the build is passing. This suggests that there's something in your PR that is at issue

I just checked the following:
```shell
$ git clone git@github.com:DefinitelyTyped/DefinitelyTyped.git
$ cd DefinitelyTyped/
DefinitelyTyped (master)$ npm i
DefinitelyTyped (master)$ cd draft-js/
DefinitelyTyped/draft-js (master)$ ../node_modules/.bin/tsc --version
Version 2.2.0-dev.20170101
DefinitelyTyped/draft-js (master)$ ../node_modules/.bin/tsc
draft-js-tests.tsx(3,19): error TS2307: Cannot find module 'immutable'.
index.d.ts(7,28): error TS2307: Cannot find module 'immutable'.
```

How could this be working in `master`'s build?

> I'm afraid I can't really look at this and give anymore insight as I'm on my phone.

No worries, thanks anyway. Whenever you or any of the other authors have time to help me troubleshoot this I'll resubmit whatever changes I need to make to fix the build.

Cheers.

**Comment by andy-ms** [comment]
Test failure fixed by #13667.
But this has been done before and reverted. See #12239. Added note: #13668.

**Comment by johnnyreilly** [comment]
Ah - so this presumably shouldn't be merged

**Comment by pzavolinsky** [comment]
Oh, I see. Sorry about this.

I guess adding the comment suggested in #12239 would be a good idea since this is bound to happen again because:
 - React's [documentation](https://facebook.github.io/react/docs/forms.html#controlled-components) still uses `e.target.value`
- They even provide an [example](https://codepen.io/gaearon/pen/VmmPgp?editors=0010) using `e.target.value`.
- Trying these examples in typescript fails to compile.
- At least currently, googling for `react target.value` yields 2.7M results vs the 0.09M results for `react currentTarget.value`
