### PR TITLE
[mocha] Remove type overriding by NodeJS

### LINKED ISSUE #22510: Mocha's type definitions pollute and break other node modules
For example, it changes the return type of `setTimeout` and causes some errors.

```
node_modules/spica/throttle.ts(7,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/spica/throttle.ts(28,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

This is caused by #22112.

@aozgaa Can you revert that change?

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #22510

### CODE REVIEW

**Comment by falsandtru** [comment]
Mocha has been used in both environments of Client(Browser) and Server(NodeJS) but current definition breaks the client environment by types of NodeJS. You must remove the reference to NodeJS.

**Comment by mhegazy** [comment]
@mtraynham mind reviewing this change.

**Comment by mhegazy** [comment]
I am not sure there is one really.
