### ISSUE TITLE
[@types/react] Property "Required", "Name", "Placeholder" in TextField are not supported in 15.0.38

### ISSUE THREAD

**Issue by applelok** [DefinitelyTyped/DefinitelyTyped#20020]
- [ ] I tried using the `@types/react` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @....

`dependencies:
    "@microsoft/sp-core-library": "~1.2.0",
    "@microsoft/sp-webpart-base": "~1.2.0",
    "@types/jquery": "^2.0.48",
    "@types/jqueryui": "^1.11.34",
    "@types/react": "15.0.38",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "jquery": "^2.2.4",
    "jqueryui": "^1.11.1",
    "msal": "^0.1.1",
    "office-ui-fabric-react": "^4.21.4",
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "sp-pnp-js": "^2.0.6",
    "superagent": "^3.5.2"
  },`

Code:
`<TextField 
      label='Site name: ' 
      required={ true }
      name='siteName'
      disabled={ this.state.isSiteLinkValidating }
      placeholder='Please input the site name here.'
      value={ this.state.siteName }
      onGetErrorMessage={ this._getSiteNameErrorMessage }
      onChanged={ this._handleSiteNameChange }
      validateOnLoad={ false }
 />`
Typescript version: 2.5.2

**Expect behaviour:** 
The property "Required" , "Name", "Placeholder" in TextField are supported in @types/react 15.0.38. Are they deprecated? 

**Actual behaviour:**
1. It was working in @types/react 0.14.46, but now when run with "gulp serve", error occurred.  
Error message:
Error - typescript - src\webparts\sharepointRequestForm\components\SharepointRequestForm.tsx(516,12): error TS2339: Property 'required' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextField> & Readonly<{ children?: ReactNode; }> &...'.
2. The * next to the field label and placeholder are disappeared in the webpart UI.
3. Tried to update to the latest version of @types/react, 16.0.5, but still no luck

**Comment by andy-ms** [comment]
CC authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson @morcerf @tkrotoff @DovydasNavickas @onigoetz @richseviora

**Comment by tkrotoff** [comment]
Tested myself with `@types/react` version 16.0.7 (latest version) => no problem with regular HTML `<input />`

Obviously your `<TextField />` just does not accept HTML5 attributes, use a regular HTML `<input required />` instead and see if it works.

Are you using this: https://developer.microsoft.com/en-us/fabric#/components/textfield ?
Source code seems OK: https://github.com/OfficeDev/office-ui-fabric-react/blob/3e4e87a18c78032dc725773538e6e0e38af1aa80/packages/office-ui-fabric-react/src/components/TextField/TextField.Props.ts#L38 props inherits from `React.AllHTMLAttributes<HTMLInputElement | HTMLTextAreaElement>`

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
