### ISSUE TITLE
4.0.30 cause compilation error

### ISSUE THREAD

**Issue by BLRplex** [DefinitelyTyped/DefinitelyTyped#28323]
React-router does not compiles after update to 4.0.30. The compilation crashs with error "TS2315: Type 'Location' is not generic".
Next commit brokes all: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/cca37a570aecfd6af85c4586f3c0e993a1e537dc#diff-bc5f906a3af0cde1a95a8a23cb993e96

- [ ] I tried using the `@types/react-router` package and faced with building problem. Application crashs with TypeError. It's actual only for 4.0.30.
  - Authors: @johnnyreilly 

![2018-08-23 14-48-38](https://user-images.githubusercontent.com/2276644/44523729-a58bf500-a6e3-11e8-9af9-7da13382ef67.png)

**Comment by johnnyreilly** [comment]
Closing as this appears to be user's codebase being broken by a change in the type definitions; not a break in the type definitions themselves. See discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/cca37a570aecfd6af85c4586f3c0e993a1e537dc#commitcomment-30264610
