### ISSUE TITLE
node_modules/@types/restify/index.d.ts(735,5): error TS2717

### ISSUE THREAD

**Issue by enricodvn** [DefinitelyTyped/DefinitelyTyped#25944]
When I try to compile with typescript@2.8.3, I get this error:

    node_modules/@types/restify/index.d.ts(735,5): error TS2717: Subsequent property declarations must have the same type.  Property 'headers' must be of type '() => any', but here has type 'any'.
    11:25:47 - Compilation complete. Watching for file changes.

I have already tried to put `types: []` in the compilerOptions, exclude node_modules, etc... but the only solution was to install typescript@2.6.2.

Anyone else have also encontered this error?

**Comment by mgebundy** [comment]
Can you provide more information? Which version of `@types/restify` and `restify` are you using, and what are you calling?

**Comment by mgebundy** [comment]
I tried those versions in a bare project, and I don't get any errors. Have you tried deleting your `node_modules` and reinstalling your dependencies? `error TS2717` might be the result of old types hanging around.

If that doesn't work, can you provide your `tsconfig.json`, and maybe your `npm list`? Are you setting your own types for restify anywhere in your project?

**Comment by anvad** [comment]
I was able to reproduce this error with `@types/restify` `5.0.6` and `restify` `6.3.1`
`tsc` version: `3.3.3333`

I then upgraded `@types/restify` to `5.0.11` and the error went away.

See test repo https://github.com/anvad/restify-ts-test
running tsc with the initial commit of that test repo shows the error.
running tsc with the next commit of that repo shows error has gone away.

Perhaps this issue can be closed now?

**Comment by Jaquelaurenti** [comment]
I am also experiencing this problem in response headers I am using restify@6.3.4 @ types / restify @ 5.0.6

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
