### ISSUE TITLE
Incorrect typings for session object

### ISSUE THREAD

**Issue by pol905** [DefinitelyTyped/DefinitelyTyped#49941]
Adding a new property to the sessions object throws an error.
For example doing this: `req.session.userId` throws an error `Property 'userId' does not exist on type 'Session & Partial<SessionData>'.`

**Comment by BenoitGour** [comment]
I have de same error after doing an `npm ci` i get `Property 'token' does not exist on type 'Session | InitializedSession'.
  Property 'token' does not exist on type 'Session'.ts(2339)`

**Comment by dwheeler** [comment]
I've had to go back to `"@types/express-session": "1.17.0"` to resolve this issue. The `SessionData` interface changed from 
```ts
  interface SessionData {
      [key: string]: any;
      cookie: SessionCookieData;
    }```
to 
```ts
interface SessionData {
        cookie: Cookie;
    }
```

Without `[key: string]: any;` additional properties added by the application will throw errors.

**Comment by BenoitGour** [comment]
Thanks @dwheeler I just tried that and it works for me.

**Comment by qoobes** [comment]
Perhaps we should make a pull request to fix the error? I only stumbled upon this after 2 hours of pure pain trying to figure out why it was failing.

**Comment by BenoitGour** [comment]
Yes that would be usefull because for now we have to use `"@types/express-session": "1.17.0"`.

**Comment by qoobes** [comment]
I looked into the solution they offered in the comments on their files, but it completely fails. I don't have time right now, so I guess we'll just wait for one of the maintainers to catch sight of this. 
btw share the pr so it gets ranked higher on google, took me like 2 hours to find this

**Comment by qoobes** [comment]
I made a short post thingy here, I'm new to the platform so not sure if i horribly misused it, but hope it helps someone.

[Blog Post](https://dev.to/qoobes/express-session-failing-with-typescript-types-express-session-1ehk)

**Comment by pol905** [comment]
A quick fix for now would be to use `//@ts-ignore`

**Comment by wenhx** [comment]
I found a solution here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/59b7135266eae0dd9cdd65e5fd341209e810ccf0/types/express-session/express-session-tests.ts#L63
But if I put these codes in a separate file it won't work.
After I added two lines of code, it worked, but I don't know why. 
Can anyone tell me?

```
import session from "express-session";

export = session;

declare module 'express-session' {
    interface SessionData {
        views: number;
    }
}
```

**Comment by qoobes** [comment]
The example seems to be broken for the time being, just use the solution we proposed above or in other words the one i proposed 
 [here](https://dev.to/qoobes/express-session-failing-with-typescript-types-express-session-1ehk)

**Comment by emredalkiran** [comment]
@wenhx here is how I did it.

First, I edited` tsconfig.json` to include custom defined types.

```
{
//other config options

  "typeRoots": [
       "./src/types", // this is where you define your your types
       "./node_modules/@types" //this where npm packages containing types are located
     ]

   //other config options
 }
```
Within the file `index.ts` which is under `src/types` directory:
```
import { Session } from 'express-session'

declare module 'express-session' {
 interface Session {
    userId: string;
  }
}
```
I was able access all session properties plus the one I defined under `request.session` object.

Downgrading to previous `@types/express-session` module didn't make sense to me because I've read comments of the maintainers of the library and this is not a bug but an intended breaking change, which will be the default behavior from now on.

**Comment by pol905** [comment]
Ok that's weird. Should I close this issue then ?

**Comment by BenoitGour** [comment]
@wenhx do you have a link to the maintainers comments? or the proper recommended way to now use express-session?

**Comment by emredalkiran** [comment]
@BenoitGour take a look at the message at this [link](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r44195924) which is under the merge request for this change. 

You can also inspect `index.d.ts` file under `node_modules/@types/express-session` where they provide this information in the comments section under `class Session` if your `@types/express-session` package is version 1.17.1 or newer.

**Comment by BenoitGour** [comment]
@emredalkiran Thanks!

**Comment by wenhx** [comment]
@emredalkiran Thanks!
I have another question, since we can declare the additional properties by declaration merging in interface Session, why do they want to define another interface SessionData?

**Comment by emredalkiran** [comment]
@wenhx  In the previous versions, when you added custom properties to `request.session`, it was possible via `SessionData`interface. Check out the constructor signature of `Session` class and `SessionData` interface below :

```
class Session {
        private constructor(request: Express.Request, data: SessionData);
        // rest of class declaration
}

//old version
interface SessionData {
       [key: string]: any;
       cookie: Cookie;
}

//new version
interface SessionData {
       cookie: Cookie;
}

```

What they changed is the properties of `SessionData` interface. They argue that "having an index-type with type `any` simply paralysis type checking" therefore, it is removed. So, you were able to change session properties via `SessionData` interface in the previous versions as well.

**Comment by spenceradolph** [comment]
Ran into this issue today trying to use express-socket.io-session and similar packages. 
Caught me off guard since I was following the example code provided exactly, only with typescript enabled and took me a long time to narrow it down. 

Would be nice if there was an explicit typescript section on these example code sections that said something to the effect of 'if you plan on using TS with this package, please note that you should explicitly declare the expected types on this object, as newer versions no longer allow [key: string]: any;'
And show a nice clean example...etc

I can imagine myself liking the declaration merging, seems safe and well intended.

**Comment by wenhx** [comment]
@emredalkiran Thanks!

**Comment by silveoj** [comment]
I ca'nt fix it for 2 months)

`tsc` command works with 1.17.0 and 1.17.3
but `ts-node` package works only with 1.17.0. 

```
import 'express-session';

import { IMyInt} from '@interfaces/IMyInt';

declare module 'express-session' {
  interface SessionData { // I also tried just Session // I tried export interface ...
    myStr: string;  // Property 'myStr' does not exist on type 'Session & Partial<SessionData>'.
    myProp1?: IMyInt; // Property 'myProp1' does not exist on type 'Session & Partial<SessionData>'.
    // cookie: Cookie;
  }
}
```

doesn't work

**Comment by shaunstone0** [comment]
> @wenhx here is how I did it.
> 
> First, I edited` tsconfig.json` to include custom defined types.
> 
> ```
> {
> //other config options
> 
>   "typeRoots": [
>        "./src/types", // this is where you define your types
>        "./node_modules/@types" //this where npm packages containing types are located
>      ]
> 
>    //other config options
>  }
> ```
> 
> Within the file `index.ts` which is under `src/types` directory:
> 
> ```
> import { Session } from 'express-session'
> 
> declare module 'express-session' {
>  interface Session {
>     userId: string;
>   }
> }
> ```
> 
> I was able access all session properties plus the one I defined under `request.session` object.
> 
> Alternatively, instead of `Session`, you can import `SessionData` and change interface name to `SessionData`, it also works like that. I needed the session else where as a type, therefore I merged with `Session`.
> 
> Downgrading to previous `@types/express-session` module didn't make sense to me because I've read comments of the maintainers of the library and this is not a bug but an intended breaking change, which will be the default behavior from now on.

When I do this, I still get this error- even though I can access the userId object without an error.

**Comment by coderdix** [comment]
> > @wenhx here is how I did it.
> > First, I edited` tsconfig.json` to include custom defined types.
> > ```
> > {
> > //other config options
> > 
> >   "typeRoots": [
> >        "./src/types", // this is where you define your types
> >        "./node_modules/@types" //this where npm packages containing types are located
> >      ]
> > 
> >    //other config options
> >  }
> > ```
> > 
> > 
> > Within the file `index.ts` which is under `src/types` directory:
> > ```
> > import { Session } from 'express-session'
> > 
> > declare module 'express-session' {
> >  interface Session {
> >     userId: string;
> >   }
> > }
> > ```
> > 
> > 
> > I was able access all session properties plus the one I defined under `request.session` object.
> > Alternatively, instead of `Session`, you can import `SessionData` and change interface name to `SessionData`, it also works like that. I needed the session else where as a type, therefore I merged with `Session`.
> > Downgrading to previous `@types/express-session` module didn't make sense to me because I've read comments of the maintainers of the library and this is not a bug but an intended breaking change, which will be the default behavior from now on.
> 
> When I do this, I still get this error- even though I can access the userId object without an error.
> 
> Error: `Property 'userId' does not exist on type 'Session & Partial<SessionData>'`

same here, I had it working... got a new computer and now it's broke again :-(

**Comment by yoshua70** [comment]
I think this is coming from Ben Awad fullstack video. Using  @wenhx and @emredalkiran answer I was to able to fix it.
First create a new file `src/types/index.ts` :
```ts
import session from "express-session";

export = session;

declare module "express-session" {
  interface SessionData {
    userId: number;
  }
}
```

Then add the following options to the `tsconfig.json` : 
```json
{
  "compilerOptions": {
    "typeRoots": {
      "./src/types",
      "./node_modules/@types"
    }
  }
}
```

Finally run `yarn watch` or the command that you use to compile typescript files. `yarn watch` is a script that can be defined in `package.json` :
```json
{
  "scripts": {
    "watch": "tsc -w",
  },
}
```

**Comment by danepowell** [comment]
Answer from @yoshua70 fixed the issue for me when compiling natively but Mocha was still throwing errors on compilation. The solution here worked: https://stackoverflow.com/a/61450623

**Comment by yoshua70** [comment]
Glad you managed to fix it ! 👍🏾

**Comment by ffakira** [comment]
> Answer from @yoshua70 fixed the issue for me when compiling natively but Mocha was still throwing errors on compilation. The solution here worked: https://stackoverflow.com/a/61450623

For me, the solution worked once I've added in the `tsconfig.json`.  Along with @yoshua70 solution, also I've needed to add `skipLibCheck` since I am writing unit tests in `ts-jest` 

```json
{
  "ts-node:" {
    "transpileOnly": true
   },
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```

**Comment by pks99ing** [comment]
Hopefully this might help to some one.
Instead of doing all the changes , I would recommend to create an interface which extend Session
here is an example code

'''import { Session } from "express-session";

export interface CustomSessionData extends Session {
    user: {
        userName: string,
        email: string
    }
}'''
The user is the field which i want to attach to `req.session`.
How when you want to set the session
```
const session = req.session as CustomSessionData
session.user = user
'''
And for checking in the middleware 
'''
 if (req.session && (req.session as CustomSessionData).user) {
        // User is authorized
        return next()
    } else {
        // User is not authorized
        res.send('User is not authorized')
    }
'''
