### ISSUE TITLE
@types/node@10.10.1 throws Error: Cannot find name 'Set'

### ISSUE THREAD

**Issue by leeyeh** [DefinitelyTyped/DefinitelyTyped#28969]
- [x] I tried using the `@types/node@10.10.1` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @SimonSchick 

I have a SDK which does not use @types/node directly. I use `tsc@2.9.2` to validate the definition file (with no tsconfig.json). One of the dependencies (rollup@0.61.2) uses @types/node

Running `tsc play.d.ts` throws an Error: 

```
node_modules/@types/node/index.d.ts:804:38 - error TS2304: Cannot find name 'Set'.

804         allowedNodeEnvironmentFlags: Set<string>;
                                         ~~~
```

This change was introduced in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28918.

Downgrading to @types/node@10.9.4 fixes this Error.

To reproduce,  clone and checkout this branch https://github.com/onerain88/Play-SDK-JS/tree/fix_disconnect, then run `npm run lint`。

**Comment by SimonSchick** [comment]
What `lib`s did you include in your tsconfig?

**Comment by valeshino** [comment]
I'm having the same issue; our `lib` config is:
```json
  "compilerOptions": {
    "lib": [
        "dom",
        "es2017"
    ],
```

**Comment by SimonSchick** [comment]
I cannot reproduce the issue in my local codebases.

@valeshino fyi you should be using `@types/node@8.x.x`.
Now checking is this is a TS3.1 issue.

**Comment by SimonSchick** [comment]
Cannot repro in your version of TS or `@next`, please make sure that your `tsconfig.json` is loaded correctly.

**Comment by SimonSchick** [comment]
@RyanCavanaugh @Flarna is there a way to have typings require a minimum lib version of any kind? I _know_ that node@>= ship with Set, Map etc..

**Comment by Flarna** [comment]
As far as I know there is no way to specify this. For quite a while es5 was used at definitely typed but meanwhile it's es6. There are still some forward declarations in node typings to allow use of es5.

But @valeshino mentions that he is using es2017 which includes `Set` so I wonder why this happens. I tried locally and I get this error if I use es5 but not with es2017.

**Comment by uikolas** [comment]
Encoutered same problem. Update to [node js](https://nodejs.org/en/download/current/) 10 helped.

**Comment by SimonSchick** [comment]
If anyone would be able to supply a repro that would be helpful, right now we have to assume this is a user configuration error and unrelated to the typings themselves.

**Comment by leeyeh** [comment]
This commit should be affected: https://github.com/onerain88/Play-SDK-JS/tree/2d097e91beb0c9885947e683f4e3df6c17c747a6

run `npm run lint` to reproduce.

**Comment by SimonSchick** [comment]
@leeyeh you do not have a configuration for `tsc` therefor it falls back to es5.
Try using `tsc --lib es6` or higher.

**Comment by SimonSchick** [comment]
@leeyeh I cannot reproduce the issue in your repo either.
The commit you linked doesn't even contain `@types/node` and I cannot check it out after cloning it.
Your `master` branch does include them but doesn't reference them at all so they don't appear to be loaded and therefor don't break TSC either.

**Comment by leeyeh** [comment]
Thanks, @Simon. Here is some detail

1. The SDK does not use @types/node directly. One of the dependencies (rollup@0.61.2) uses @types/node. You can confirm this by `npm list`.
2. I use tsc (@2.9.2, also tried ~3.0, no luck) to validate the definition file. The tsconfig.json was not added on purpose to use the default configs(--target ES5 --lib DOM,ES5,ScriptHost)) as the SDK is ES5-targeted.

Is that possible that I'm doing something wrong?

**Comment by SimonSchick** [comment]
You might want to use --skipLibCheck in this case.

**Comment by SimonSchick** [comment]
Also please mind that you can use `--lib es6` just fine as it doesn't alter the resulting code.

**Comment by Flarna** [comment]
Maybe we should add forward declarations for `Set` in node typings - and switch to use `lib es5` in tests to avoid such issues.

**Comment by SimonSchick** [comment]
@Flarna this issue is only going to become worse, as node already implements ES2018, I don't think forward declaring everything is a long term solution.

See also: https://node.green/

**Comment by Flarna** [comment]
I know and I wonder also that such issues happen that frequent. As long as the forward declarations don't conflict with the real definitions it should be ok. The forward declarations just ensure that typescript is fine - you can't use them in real live as they don't offer any API in general.
There are a lot node uses out there which use only a small subset of node where it is simply don't care if they use lib es2018 or es5 and the default of typescript is still es5.

I think the correct solution would be a lib reference (introduces in typescript 3.0) - but as long as node typings have to stay compatible with TS 2.0 it's of no help.

**Comment by jsdevel** [comment]
I'm facing this as well with 10.10.2.  Here's my tsconfig:

```json
{
  "compilerOptions": {
    "declaration": true,
    "module": "CommonJS",
    "outDir": "dist",
    "sourceMap": true
  },
  "files": [
    "index.ts"
  ]
}
```

Downgrading to 10.9.4 fixed it.

**Comment by lx-931203** [comment]
To reproduce a bug:
* create empty directory
* yarn add typescript @types/node
* echo 'console.log("Works?")' >> index.ts
* yarn run tsc index.ts

**Comment by SimonSchick** [comment]
@andy-ms can we somehow indicate that typings need certain libs?

**Comment by andy-ms** [comment]
@SimonSchick That's what `/// <reference lib` (Microsoft/TypeScript#23893) directives were created for. We're currently working on the ability to support "typesVersions" (Microsoft/TypeScript#26568) on DefinitelyTyped so this can be used with node.
