### ISSUE TITLE
tsc: ERROR <filename> Cannot find name 'module' after upgrading to 0.8.17

### ISSUE THREAD

**Issue by michaelsanford** [DefinitelyTyped/DefinitelyTyped#18425]
- [x] I tried using the `@types/node` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @wwwy3y3

I have a woefully underspecified bug: in an angular 4 project, after upgrading from
```
"@types/node": "8.0.16"
```
to
```
"@types/node": "8.0.17"
```
I received a tsc (2.4.2) compile-time error:
```
ERROR <a-deeply-nested-component-file.ts> Cannot find name 'module'.
```

Why do I suspect `@types/node`?
- The error thrown seems completely unrelated to my actual code (at a location in an angular 4 `@Component` class decorator that had no changes since a previously-working build),
- Downgrading to `0.8.16` fixed the error with no code changes.
- [This now-canonical SO question](https://stackoverflow.com/questions/36700693/typescript-error-in-angular2-code-cannot-find-name-module) suggests that this error (albeit in a much older version) can be the result of not having `@types/node` installed at all.

**Comment by orta** [comment]
Hi thread, we're moving DefinitelyTyped to use [GitHub Discussions](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53377) for conversations the `@types` modules in DefinitelyTyped.

To help with the transition, we're closing all issues which haven't had activity in the last 6 months, which includes this issue. If you think closing this issue is a mistake, please pop into the [TypeScript Community Discord](https://discord.gg/typescript) and mention the issue in the `definitely-typed` channel.
