### ISSUE TITLE
@types/react-dom 15.5.2 causes typescript build break by adding @types/node dependency

### ISSUE THREAD

**Issue by richardspence** [DefinitelyTyped/DefinitelyTyped#18615]
Today my builds started failing because of a conflict between requirejs and node require

This is the compile error I received from typescript:
```
d:/a/1/s/node_modules/@types/node/index.d.ts(99,13): 
error TS2403: Subsequent variable declarations must have the same type.  
Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
```
Lookin at the npm install diff since last known good built showed that it was introduced from react-dom:
![image](https://user-images.githubusercontent.com/9914123/28945102-eb720cf8-7859-11e7-8858-4409e1aa336e.png)

15.5.1 didn't have the dependency to `@types/node`

**Comment by paranoidjk** [comment]
+1 same problem here

**Comment by paranoidjk** [comment]
```bash
node_modules/@types/node/index.d.ts(73,13): error TS2451: Cannot redeclare block-scoped variable 'global'.
node_modules/@types/node/index.d.ts(99,13): error TS2300: Duplicate identifier 'require'.
node_modules/@types/react-native/index.d.ts(9036,11): error TS2451: Cannot redeclare block-scoped variable 'global'.
node_modules/@types/react-native/index.d.ts(9037,14): error TS2300: Duplicate identifier 'require'.
```

**Comment by paranoidjk** [comment]
caused by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18493/files

cc @rikuayanokozy  @sheetalkamat

**Comment by teraton** [comment]
Same problem, we had to rollback to the previous version. Breaking setTimeout and other typical functions by assigning them the node types for ex. Node timer.

**Comment by rikuayanokozy** [comment]
track on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18773
cc @paranoidjk @teraton

**Comment by wezleytsai** [comment]
I'm running into this issue now. Looks like types/node got [added again](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20065/files#diff-fba7c51ec1999fa399fc3b7874ea5c4dR1) when react-dom was upgraded to v16.

**Comment by richardspence** [comment]
Yes I've noticed this has regressed again with `16.0.3`, @mhegazy can you reopen this?

**Comment by brunolemos** [comment]
@richardspence  can't you reopen?

I'm facing this as well.
