### PR TITLE
FEAT(koa): add ExtendableContext interface to extends context

### PR DESCRIPTION
**Pull request by zbinlin**
When developing a koa middleware, sometimes we need to extend ctx. We can extend it with BaseContext, but can't extend ctx instead of app.context. Now add a new interface to resolve it.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/koa/index.d.ts [hunk 1]
```diff
@@ -686,7 +686,7 @@ declare namespace Application {
         request: Request;
     }
 
-    type ParameterizedContext<StateT = any, CustomT = {}> = BaseContext & {
+    interface ExtendableContext extends BaseContext {
```
Comment (rbuckton) [inline types/koa/index.d.ts]: Is this necessary, or would you just augment `BaseContext` instead? It also seems like the purpose of `ParameterizedContext` is to add custom extensions to `BaseContext` (via `CustomT` and `Middleware`):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f59635899ed15815241c55bc795fe371393b469/types/koa/index.d.ts#L500-L502

Comment (zbinlin) [reply types/koa/index.d.ts]: I only want to add to `ctx`, but `BaseContext` will also add to `context`.

**Comment by esetnik** [comment]
FYI this PR breaks compatibility with `@types/koa-body`. Specifically `ctx.request.body` has `Property 'body' does not exist on type 'Request'.` See https://github.com/dlau/koa-body/blob/master/index.d.ts#L6

**Comment by feimosi** [comment]
It also broke [koa-passport](https://github.com/rkusa/koa-passport) context extension e.g. `ctx.logOut`

**Comment by zbinlin** [comment]
@esetnik I cannot reproduce it, could you upload minimum repo for me to reproduce it?

**Comment by zbinlin** [comment]
@feimosi It seems broken by #31704

**Comment by feimosi** [comment]
@zbinlin are you sure? The issue occurs only when I update `@types/koa` from 2.0.48 to 2.0.49 which is the latest version.

**Comment by zbinlin** [comment]
@feimosi I can't reproduce the error. Please give me minimum reproduced repo.

**Comment by feimosi** [comment]
@zbinlin I've tried updating it again and it works now.

**Comment by xr** [comment]
> FYI this PR breaks compatibility with [koa-body](https://github.com/dlau/koa-body). Specifically `ctx.request.body` has `Property 'body' does not exist on type 'Request'.` See https://github.com/dlau/koa-body/blob/master/index.d.ts#L6

@zbinlin @esetnik same problem with `koa-bodyparser` https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36999

**Comment by xr** [comment]
> > FYI this PR breaks compatibility with [koa-body](https://github.com/dlau/koa-body). Specifically `ctx.request.body` has `Property 'body' does not exist on type 'Request'.` See https://github.com/dlau/koa-body/blob/master/index.d.ts#L6
> 
> @zbinlin @esetnik @rbuckton same problem with `koa-bodyparser` #36999

fixed by upgrading other packages to the latest version.

**Comment by damianb** [comment]
I strongly suspect this is a re-emergence of #22568.
