### ISSUE TITLE
[@types/chai-as-promised] not cmpatible with @types/chai v4.0.7

### ISSUE THREAD

**Issue by DominikPalo** [DefinitelyTyped/DefinitelyTyped#21942]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jt000, @Kuniwak, @leonard-thieu, @jedmao, @Bartvds, @AGBrown, @olivr70, @mwistrand, @JoshuaKGoldberg, @shaunluttin, @Naktibalda 

I updated `@types/chai` to the latest version (4.0.7) and `@types/chai-as-promised` (0.0.31) fails to build with errors:
```
node_modules/@types/chai-as-promised/index.d.ts(23,33): error TS2304: Cannot find name 'LanguageChains'.
node_modules/@types/chai-as-promised/index.d.ts(23,49): error TS2304: Cannot find name 'NumericComparison'.
node_modules/@types/chai-as-promised/index.d.ts(23,68): error TS2304: Cannot find name 'TypeComparison'.
```

It works fine with `@types/chai` 4.0.6

**Comment by leonard-thieu** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21879#pullrequestreview-80716086 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21924.

**Comment by mhegazy** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21924
