### PR TITLE
node: Backport #59905 to ts4.8

### PR DESCRIPTION
**Pull request by meyfa**
Node.js types are currently out of sync between TS 4.9+ and TS <= 4.8 variants. Specifically, PR #59905 introduced many changes that were not copied over to ts4.8. This patch is an exact copy of that PR, but applied to ts4.8. The goal is that `@types/node` behaves the same on all versions of TypeScript.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
  * See #59905 for the source of this patch (compare the diff to this PR via the "Files changed" tab - they should be identical).
  * The `ts4.8` directories were introduced in #62375.

### CODE REVIEW

**Comment by meyfa** [comment]
CC @thw0rted are you okay with this change? Thanks for the great work on the original patch, by the way! Very awesome! :)

**Comment by thw0rted** [comment]
Thanks, I'm glad it's working out.  I just skimmed the diff but it looks good, as long as all the tests are passing and whatnot.

**Review by peterblazejewicz — APPROVED** [review]
@meyfa thanks!

**Comment by meyfa** [comment]
Ready to merge

**Comment by AviVahl** [comment]
v16.11.65 caused a regression on my end. Can be seen in https://github.com/wixplosives/pleb, by cloning, removing the lock file, and running `npm it`:
```
node_modules/@types/node/ts4.8/stream.d.ts:842:39 - error TS2304: Cannot find name 'Blob'.

842             static from(src: Stream | Blob | ArrayBuffer | string | Iterable<any> | AsyncIterable<any> | AsyncGeneratorFunction | Promise<any> | Object): Duplex;
                                          ~~~~

node_modules/@types/node/ts4.8/stream.d.ts:842:39 - error TS2304: Cannot find name 'Blob'.

842             static from(src: Stream | Blob | ArrayBuffer | string | Iterable<any> | AsyncIterable<any> | AsyncGeneratorFunction | Promise<any> | Object): Duplex;
```

Can be worked around by adding "dom" to tsconfig->lib, which kinda beats the purpose of this PR.

**Comment by thw0rted** [comment]
I think I see the issue.  In the updated tests, we check for `new`-able global `Blob` but not the type side (`const b: Blob`).  Conditional types were used to declare global interfaces for e.g. `Event` / `EventType` but not `Blob`, because `Blob` is a class but `Event` is not.

I put together a quick PR that will add the type-side of Blob (along with tests): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62654

**Comment by OpportunityLiu** [comment]
After upgrade to `@types/node@18.8.4`, `window` becomes a constructor.

image

image

image

**Comment by thw0rted** [comment]
[The spec for EventTarget](https://dom.spec.whatwg.org/#interface-eventtarget) says it has a constructor, so the type declaration for `EventTarget` is `new`-able.  [Window was already new-able](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L16668) before this PR.  I'm not sure I understand the issue here?

**Comment by OpportunityLiu** [comment]
`window` is not a function, `Window` is. After this PR, call `new window()` got an `EventHandler`
image

image

image

**Comment by OpportunityLiu** [comment]
And for `Event` & `EventTarget`
https://www.typescriptlang.org/play?#code/MYewdgzgLgBA7jAvDMBTBcCWYAmI4DcAUKJLKrMmggBTUx3owCiAbqmFACoCGATgHMKASmHFS0GKlZIUTRrXpsOUGgHJUa0es3aNWgkA

image

https://www.typescriptlang.org/play?&dtPR=62629&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBAbwL5wGZQiOAiAdhAEwFNsAoUgYwlwGd4B3OAXjlyMfuFwInoG5K1OnCLwWbRgAoJcaezgBRAG5FcMACoBDKAHNRASn2Da8Ikuat5cqTOWqYkgORFHhpy7fPXQA

image

**Comment by thw0rted** [comment]
OK, I think I'm going to need someone smarter than I am to explain why changing `? T` to `? T['prototype']` fixes this, but it seems like probably it does?  As you point out, the current syntax (`? T : ...`) makes *instances* of EventTarget (and all the other conditional types like this) recursively new-able, in a lib-dom environment.  I have no problem with making that change where appropriate, but even better would be to have some way of *testing* this behavior with dtslint.  I have no idea how to do that; I'm not sure if it's possible to make dtslint run against multiple tsconfig files.

**Comment by thw0rted** [comment]
Is anybody still looking at this?  Is there maybe a new issue?  I'm having a really hard time putting together a reliable reproduction.  I just want to add tests that say `/** @ts-expect-error */ new (new EventTarget())()` or something along those lines, for each interface that uses this conditional-type pattern, then have the test fail, then throw in the `['prototype]'` and watch the red lights go green.  I haven't been able to get it working yet, unfortunately.
