### ISSUE TITLE
[@types/dom-mediacapture-record] Angular Builds failing due to recent upgrade in @types/dom-mediacapture-record v1.0.12

### ISSUE THREAD

**Issue by ArunVenkata** [DefinitelyTyped/DefinitelyTyped#62465]
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62437

<div type='discussions-op-text'>

<sup>Originally posted by **ArunVenkata** September 27, 2022</sup>
Angular Version v13.3.0

Error:

```
Error: Error: node_modules/@types/dom-mediacapture-record/index.d.ts:48:5 - error TS2717: Subsequent property declarations must have the same type.  Property '"error"' must be of type 'MediaRecorderErrorEvent', but here has type 'Event'.

48     "error": Event;
       ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:9114:5
    9114     "error": MediaRecorderErrorEvent;
             ~~~~~~~
    '"error"' was also declared here.

Error: Error: node_modules/@types/dom-mediacapture-record/index.d.ts:64:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'onerror' must be of type '((this: MediaRecorder, ev: MediaRecorderErrorEvent) => any) | null', but here has type '((this: MediaRecorder, event: Event) => any) | null'.

64     onerror: ((this: MediaRecorder, event: Event) => any) | null;
       ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:9125:5
    9125     onerror: ((this: MediaRecorder, ev: MediaRecorderErrorEvent) => any) | null;
             ~~~~~~~
    'onerror' was also declared here.

```
Package.json:
```
{
"devDependencies": {
    ...
    "@types/dom-mediacapture-record": "^1.0.11",
    "typescript": "~4.5.2"
    ...
  }
}
```

To fix this I changed the package.json to the following for now:
`"@types/dom-mediacapture-record": "1.0.11"`</div>

**Comment by Semigradsky** [comment]
Looks like it was caused by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62428

@komyg can we have different types for different TypeScript versions? For example, how it works for `node`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b8fb2ccd5c298c527ddb0afb67709349a146ff03/types/node/package.json#L4-L6

**Comment by komyg** [comment]
> Looks like it was caused by #62428
> 
> @komyg can we have different types for different TypeScript versions? For example, how it works for `node`:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b8fb2ccd5c298c527ddb0afb67709349a146ff03/types/node/package.json#L4-L6

Sure, I just opened a PR with that. Could you help me with the review?

PS: I am sorry for inadvertently breaking these types.
